### ISSUE TITLE
Should we change the theme name? Have a nice name?

### ISSUE THREAD

**Issue by nana-4** [nana-4/materia-theme#137]
Originally, Flat-Plat was not a Material Design theme, was a _flat design_ theme. But Material Design was announced before or after releasing this theme and I liked it right away. Then, I immediately tried to apply it partially to Flat-Plat. Therefore in the past it was not completely compliant with the guidelines, but now it is almost properly in line with the guidelines. So I would like to break out of this old name. The reasons are:
- The current name includes the word "_Flat_". Flat design and material design are somewhat similar, but they are not the same.
- There is a project called [Flatpak](https://github.com/flatpak/flatpak). Since it is similar in name to Flat-Plat, I want to avoid confusion.
- I expected this name to be a easy-to-remember name, but I often see it being mistakenly called (like _Flat-pat_). I'm not a native English speaker, so I don't know if this name sounds good...

---

However, there are some concerns.
1. There are some packages for each distribution ([Arch](https://aur.archlinux.org/packages/flatplat-theme) and [Fedora](https://copr.fedorainfracloud.org/coprs/tcg/themes/)) by contributors.
  - It may require change of the package names?
2. It may cause other small confusions to folks. For example, if some document is written as "Flat-Plat", it may be necessary to change to a new name.
---

Based on these, **should we change the theme name, or not?**

Or, **do you have ideas of nice name?**

I would like to get your feedback. Thanks!

**Comment by coler706** [comment]
I believe we should change the name.

**Comment by Warmuser** [comment]
Uhm, "FlatShape"? :)

**Comment by coler706** [comment]
How about "Compulsive"?

**Comment by OriginalFannibal** [comment]
Would you consider *Materia*?

**Comment by nana-4** [comment]
Guys, thanks for your feedback! (and sorry for my late response.)

I think that the new name would be better to have a (preferably) simple name with a single word. :)

**Comment by nana-4** [comment]
@OriginalFannibal 
Exactly! I was also thinking to express "Material" in Latin. (e.g. _Materia_, _Materialis_, _Materiae_)
However, this problem is that the naming is quite simple, so the name will overlap with other projects:
- https://github.com/search?q=materia&type=Repositories&utf8=%E2%9C%93
- https://github.com/search?q=materialis&type=Repositories&utf8=%E2%9C%93
- https://github.com/search?q=materiae&type=Repositories&utf8=%E2%9C%93

**Comment by OriginalFannibal** [comment]
Well, if you really do like *Materia* or one of its variants then I say go for it. It is hard to find a name that's simple but not popular. As long as the name is unique within its niche (in this case GTK themes), I think it's fine for it to overlap with other projects.

Here are search results for some other really popular themes/icons:  
- [Arc](https://github.com/search?utf8=%E2%9C%93&q=arc&type=Repositories)
- [Paper](https://github.com/search?utf8=%E2%9C%93&q=paper&type=Repositories)
- [Vertex](https://github.com/search?utf8=%E2%9C%93&q=vertex&type=Repositories)  

So yeah, go for what you like. For what it's worth, I vote for *Materia*.

**Comment by nana-4** [comment]
@OriginalFannibal Thank you for your opinion! Surely you are right. Your opinion was very helpful. :)

**Comment by nana-4** [comment]
So, as @OriginalFannibal suggests, I currently regard **Materia** is the most suitable name for this theme.


However, if you have other opinions, I'd love to hear that.

If there are no other suggestions, I'd like to change the name theme to **Materia** (and the repository name to `materia-theme`) in a few weeks. 😃

**Comment by coler706** [comment]
Instead of the latin word for material which results in large amounts of overlap,
why not simplex (simple in latin) (has 1/28 the overlap)
or simpl**i**x (insert an i) (only 14 other results)

**Comment by coler706** [comment]
I change my vote to simplix because it is not only simple but unique fulfilling what @OriginalFannibal suggested looking for.

**Comment by nana-4** [comment]
@coler706 
Thank you for your opinion. It's nice to have a simple and unique name.

Although I'm always trying to write the code as _simple_ as possible, I think this theme is not necessarily _simple_ because it is based on [Material Design guidlines](https://material.io/guidelines/)...

**Comment by OriginalFannibal** [comment]
@coler706 While the names are nice, I would like to reiterate that the focus should be on what @nana-4 likes and not in avoiding an overlap. The project is not going to compete with those other projects, especially when they are in different fields and in that case overlapping with any number of projects, irrespective of the number wouldn't make a difference. 

What do you think?

**Comment by nana-4** [comment]
I would like to adopt a more natural and appropriate name for many people. I'm not good at English. Therefore I opened this issue and seeking opinions from people. :)

The reason why I currently think _Materia_ is most suitable name is because it can be understand at a glance that it is the Material Design theme.

**Comment by USBA** [comment]
Names: **Matt**, Material, Marshmallow

By the way, I need a help.

Hey @nana-4 , 
I'm currently maintaining a gnome shell theme called "Human"
[https://www.gnome-look.org/p/1171095/](url)

There are shadows behind text and shadows (panel-buttons) in the top panel. I tried but I'm failed to remove those shadows. Please tell me the style class to remove those shadows.

I know that this is not the right place to ask this. But I can't find any other place to contact you. 

Thank you.
Have a nice day.

**Comment by nana-4** [comment]
@USBA 
Third-party gnome-shell themes **must always** overwrite the _default_ (Adwaita) theme style. Otherwise the default theme style will be reflected in your theme. And your theme seems not to follow the changes of gnome-shell 3.26.

You can find the gnome-shell changes from here:
https://github.com/GNOME/gnome-shell/commits/master/data/theme

For sass: https://github.com/GNOME/gnome-shell-sass/commits/master

Panel text/icon shadows ware added with this commit: https://github.com/GNOME/gnome-shell/commit/447bf55e45b00426ed908b1b1035f472c2466956

So, to remove the shadows, you need to add `text-shadow: none;` and `icon-shadow: none;` like this commit of Flat-Plat: https://github.com/nana-4/Flat-Plat/commit/ecdf6bb68c3323b32db8e6e1943f0d7aa36ec8b0

Good luck. And thanks for suggesting of names. :)

**Comment by actionless** [comment]
something which will relate the theme to material-design style would be great, so if `materia` name is not used already it could be a good way to go

**Comment by USBA** [comment]
@nana-4 Thank you for helping me.

**Comment by skullscream** [comment]
I accidentally wrote "flatpak" when I tried installing it from AUR. Maybe that?

**Comment by nana-4** [comment]
Hi everyone,
As planned I now changed the theme name to **Materia**.

Your opinions were very helpful. I would like to THANK everyone who gave me advice and suggestions. 😄 

I close this now.

**Comment by actionless** [comment]
i'll update oomox accordingly soon

**Comment by nana-4** [comment]
@actionless Thanks!
