### ISSUE TITLE
new BudgiePopover widget is rendered incorrectly

### ISSUE THREAD

**Issue by biggles5107** [nana-4/materia-theme#139]
- Flat-Plat version: latest git
- GTK+ 3 version: 3.22
- Distribution: Solus
- Desktop environment: Budgie 10.4
- Related application: budgie-panel
- Steps to reproduce: open any menu/popover from the panel; looks ugly
- Screenshot(s)

![popover-1](http://i.imgur.com/8WcEI4Z.jpg)
![popover-2](http://i.imgur.com/jHIGoWF.jpg)

**Comment by nana-4** [comment]
Sorry for the delay in dealing.. It has now been fixed now.
Thanks for your reports. 👍
