### ISSUE TITLE
Slow Check & radio buttons animation in Popovers

### ISSUE THREAD

**Issue by archqob** [nana-4/materia-theme#148]
It takes alot of time to move throw radio buttons and check or uncheck check button in nautilus.

**- Flat-Plat:** Latest version
**- GTK+3:** 3.22.19
**- Distribution:** Fedora 26
**- Desktop environment:** GNOME 3.24.3
**- Related application:** Nautilus 3.24.2.1
**- Steps to reproduce:** Check and uncheck Check buttons and radio buttons
**- Screenshot:**
![screenshot from 2017-09-19 16-09-44](https://user-images.githubusercontent.com/21042432/30596849-02c0b78c-9d5e-11e7-9a01-300a41e92a7f.png)

**Comment by nana-4** [comment]
Thank you for the report.

Previously, I attempted to fix this bug, but it seemed not easy.
I suppose this is due to something upstream GTK+ bug.
In any case, we need a workaround for this bug.

**Comment by actionless** [comment]
mb to disable animation inside the menus?

**Comment by nana-4** [comment]
@actionless I'm thinking about a workaround close to that. But I have to do many testing for that. 😖
