### ISSUE TITLE
Text in buttons of Veracrypt is vertically cut off

### ISSUE THREAD

**Issue by lokesh-krishna** [nana-4/materia-theme#154]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- **Flat-Plat version**: v20170917
- **GTK+ 3 version**: 3.22.19
- **Distribution**: Fedora 26 Workstation
- **Desktop environment**: GNOME 3.24
- **Related application**: Veracrypt 1.21
- **Steps to reproduce:** Open Veracrypt. Most (but not all) of the buttons have some of the text cut off vertically.
- **Screenshot(s)**

This is what it looks like on Flat-Plat:

![screenshot from 2017-09-25 19-56-47](https://user-images.githubusercontent.com/20235646/31052125-7cbeeb56-a698-11e7-950f-922811d274f6.png)

This is what it looks like on Adwaita. I know that the problem being present in Adwaita as well makes it a likely upstream issue but then the problem is less prominent there and also, it looks fine on Arc.

![screenshot from 2017-09-30 07-39-41](https://user-images.githubusercontent.com/20235646/31052129-9aa43b12-a698-11e7-9e08-20a60c567e65.png)

And here is what it looks like on Arc:

![screenshot from 2017-09-30 07-39-23](https://user-images.githubusercontent.com/20235646/31052135-a2b177ac-a698-11e7-8152-6074a691c3e0.png)

**Comment by nana-4** [comment]
Thank you for your report.
Indeed it looks quite buggy, but I'm not sure I can deal this issue with the theme.
Anyway, I'll investigate whether this can be handled.

**Comment by nana-4** [comment]
I would like to close this - since I think it's hard to address the bug with this theme, and even upstream Adwaita has this problem.

If this bug is still a problem for you, please report it to the upstream Veracrypt.
