### ISSUE TITLE
materia theme - elementary os 0.4.1 - screenshots and bug of dialogs with OK and Cancel not perfect

### ISSUE THREAD

**Issue by fastrizwaan** [nana-4/materia-theme#158]
I'm glad that materia theme look amazing on elementary os, here are some screenshots with materia-light theme:

elementary store:
![screenshot from 2017-10-05 09-12-00](https://user-images.githubusercontent.com/1161682/31210291-d15504ca-a9ae-11e7-9857-9905ffcde032.png)

elementary music:
![screenshot from 2017-10-05 09-12-03](https://user-images.githubusercontent.com/1161682/31210294-da8cea12-a9ae-11e7-8c9f-d0da37531173.png)

elementary text editor (scratch):
![screenshot from 2017-10-05 09-12-08](https://user-images.githubusercontent.com/1161682/31210309-e5e278b4-a9ae-11e7-9648-10c49efab6ba.png)

elementary file manager:
![screenshot from 2017-10-05 09-12-29](https://user-images.githubusercontent.com/1161682/31210313-f2bad93c-a9ae-11e7-8c79-f28fb21d6f56.png)

elementary photos:
![screenshot from 2017-10-05 09-13-15](https://user-images.githubusercontent.com/1161682/31210315-fea5d756-a9ae-11e7-93d4-a25b339699aa.png)

elementary calendar:
![screenshot from 2017-10-05 09-14-49](https://user-images.githubusercontent.com/1161682/31210322-066666fe-a9af-11e7-91ad-ee956ef0e62e.png)

elementary settings:
![screenshot from 2017-10-05 09-14-00](https://user-images.githubusercontent.com/1161682/31210356-2d318ffc-a9af-11e7-9c60-de2539ab3fc0.png)

elementary geary (mail app)
![screenshot from 2017-10-05 09-17-39](https://user-images.githubusercontent.com/1161682/31210334-13cf2dee-a9af-11e7-8b0a-ef84832eed83.png)

elementary browser (epiphany/gnome-web):
![screenshot from 2017-10-05 09-20-08](https://user-images.githubusercontent.com/1161682/31210347-226997ae-a9af-11e7-8ad3-b018cf1d7387.png)

NOW THE BUG:

File open dialog: (buttons are cut at bottom)
![screenshot from 2017-10-05 09-19-21](https://user-images.githubusercontent.com/1161682/31210368-3dd368ee-a9af-11e7-9d31-cb42ebcd6cc3.png)

dialog with cancel/quit (nvidia settings): please observer buttons
![screenshot from 2017-10-05 09-19-59](https://user-images.githubusercontent.com/1161682/31210377-56d04e48-a9af-11e7-947c-402c6dd84de1.png)

Also the elementary shell needs a theme for materia. That's all.

This is the only theme which looks great in gnome, budgie, elementary os.

waiting for a qt5 version so that qt5 applications look great.

Thank you.

**Comment by nana-4** [comment]
Thanks for the report.
I think the drop-shadow issue is due to the bug of the upstream gtk+.
In any case this cannot be fixed by this theme.

Therefore I'd like to close the issue, sorry.

p.s.

Pantheon (elementary OS) and its apps are not officially supported yet, so please see the progress with #69.
