### ISSUE TITLE
4px roundness

### ISSUE THREAD

**Issue by fastrizwaan** [nana-4/materia-theme#159]
The corners are almost square and too pointed, could you please consider a little rounded corners on top left and top right for the window edges like adwaita and elementary theme, here's elementary window:

elementary style with a bit rounded window edges like adwaita:
![screenshot from 2017-10-05 09-32-02](https://user-images.githubusercontent.com/1161682/31210460-129a66fe-a9b0-11e7-8ea5-c371e5fdde94.png)

material light (easy to distinguish the edges)
![screenshot from 2017-10-05 09-32-47](https://user-images.githubusercontent.com/1161682/31210485-44a067c0-a9b0-11e7-9170-26b9ebdbf482.png)

**Comment by nana-4** [comment]
The window corners already have 2px `border-radius`.
`2px` is the recommended radius for many components in the [Material Design guidelines](https://material.io/guidelines/), so I don't want to change it.

Sorry but I won't fix it.

**Comment by gregor160300** [comment]
@nana-4 considering the recent changes in many Google products and material design, a larger corner-radius seems preferred these days.

**Comment by actionless** [comment]
@nana-4 sorry for a offtopic but i've read the updated material design guide and it seems what now they have a slightly different buttons design: https://material.io/design/components/buttons.html

**Comment by actionless** [comment]
also idk if Android-x86 could be referred (since it's not an official google project), but they also have square decorations:

![](https://www.linux.org.ru/images/18051/original.png)

**Comment by actionless** [comment]
also speaking of new material design and rounding -- it seems what for "main" windows it stay with round corners however for popups they now have big rounding as in buttons

**Comment by nana-4** [comment]
Hey @gregor160300 & @actionless, thanks for your suggestions. :)

I had already noticed the roundness change in the guidelines and tried adapting it to Materia. However, frankly speaking I'm quite hesitating about it because the 4px roundness may look too pop/soft:

![image](https://user-images.githubusercontent.com/9556384/41800663-7421d960-76b1-11e8-9879-4f2c238ed6d7.png)

(I made a test branch so you can easily try it:)

```
cd /tmp && wget -qO - https://github.com/nana-4/materia-theme/archive/4px-roundness.tar.gz | tar xz
cd materia-theme-4px-roundness
./install.sh -d ~/.themes -n Materia-4px-roundness -c standard -s standard
```

What do you think? I'm currently thinking I want to wait and see for now while watching the trends of other Material Design products (like [material-components-web](https://github.com/material-components/material-components-web) and [demos](https://material-components.github.io/material-components-web-catalog)). :wink:

**Comment by nana-4** [comment]
> it seems what for "main" windows it stay with square corners

I forgot about it. Thanks!

However, personally I'd much prefer the rounded top corners for main windows. To me the square corners (with headerbar) looks [out of place](https://user-images.githubusercontent.com/9556384/41802881-493f7f50-76bf-11e8-9a61-bb66b598fbe6.png). Even on Android P, [windows are rounded in the overview](https://user-images.githubusercontent.com/9556384/41803086-98b85aa6-76c0-11e8-9dd9-8ec868f3d1a1.png), so I would like to keep the rounded corners for main windows. :)

**Comment by gregor160300** [comment]
I am already enjoying this little extra roundness, also adding roundness to the bottom corners would be awesome (I know it is difficult for GTK 2). I have been using this theme too for a while: https://github.com/vinceliuice/Canta-theme I really like the corner radius on it, but it's compact version doesn't work so I can't keep using it. Also the material-components-web [demo](https://material-components.github.io/material-components-web-catalog/#/) already has new images on the overview page, showing it is going towards more roundness as well.

**Comment by actionless** [comment]
for that instead of using hardcoded roundness in-place, you could define some kind of roundness multiplier in _colors.sass and use it in every border-radius definition

**Comment by nana-4** [comment]
Now, converting the corner radius to 4px is almost done.

I'm closing this. Thanks for your feedback!

> personally I feel like 8px would be more in line with the new design Google uses

At least the guidelines do not recommend 8px corner radius to cards by default, so I will pass on that this time. :)
