### ISSUE TITLE
Error in Code for Arch Linux

### ISSUE THREAD

**Issue by M-a-r-s-h-m-a-l-l-o-w** [nana-4/materia-theme#162]
`yaourt -S flatplat-theme-git` **not** `sudo yaourt -S flatplat-theme`
! Do not run makepkg as sudo 
*Note I removed the sudo
**Nice themes btw

Tip: `yaourt -S flatplat-theme-git --noconfirm` for easier installation

P.S. correct me if I'm wrong (I'm pretty new to Arch Linux)

**Comment by nana-4** [comment]
I'm not a maintainer of the AUR package (its maintainer is @cthbleachbit) but, the package name `flatplat-theme` seems to be invalid because it was changed to `materia-theme`. A little while ago the package name was fixed with README. So then I'll remove `sudo`. Thanks for your info. :)

**Comment by M-a-r-s-h-m-a-l-l-o-w** [comment]
I used `flatplat-theme-git` and still got your themes. Now that's interesting...

**Comment by cthbleachbit** [comment]
Sorry for that... I'll update the git package in a few hours

**Comment by M-a-r-s-h-m-a-l-l-o-w** [comment]
It's not really something really important  |||-_-
I think you'll be fine even if you don't change it.

**Comment by nana-4** [comment]
@cthbleachbit No need to apologize. Thanks for your quick response. :)

**Comment by M-a-r-s-h-m-a-l-l-o-w** [comment]
@nana-4 Thanks for your great themes and quick responses! See ya!
