### ISSUE TITLE
[Feature] Customizable transparency intesity and color

### ISSUE THREAD

**Issue by SalahAdDin** [nana-4/materia-theme#163]
My system:
- Materia v20171005
- GTK+ 3 3.22.24
- Distribution Antergos  ISO-Rolling
- Kernel x86_64 Linux 4.13.5-1-ARCH
- Desktop Gnome 3.26

I used to use `xemlism-minimalist` theme because it seems like `OsX`, but overall has a full transparency and with light gray or white color.

I want to know if exist any way for put full transparency and light gray color like these theme in this theme.

Thank you!

And great work!

**Comment by nana-4** [comment]
I'm sorry for the late reply.

Sorry but i'm not exactly sure what you are pointing at.
Are you talking about the **top panel** of **GNOME Shell**?
If so, you can use this extension to control the transparency:
https://extensions.gnome.org/extension/885/dynamic-top-bar/

If you have CSS knowledge, you can also edit `gnome-shell.css` directly to change the color and transparency.

**Comment by nana-4** [comment]
BTW, I don't intend to give transparency to the menu of gnome-shell. Because this is a Material Design theme, not a Mac-like theme. :)

**Comment by SalahAdDin** [comment]
I understand it... but it could be nice.

**Comment by nana-4** [comment]
If you want to edit and change the CSS by yourself, I can advise if you indicate where and how you want to change specifically.

If not, would you close this issue?

**Comment by SalahAdDin** [comment]
@nana-4 Please.

**Comment by nana-4** [comment]
I don't know yet where you want to change.
Please specify exactly where you want to change.
(For example, _"I want to make the menu of gnome-shell translucent."_)

It would be better if you attach the screenshot(s) to make it clear.

**Comment by nana-4** [comment]
No response for a long time... I close this now.

**Comment by SalahAdDin** [comment]
@nana-4 I want to make the menu of gnome-shell translucent.
Just like this.

**Comment by SalahAdDin** [comment]
@nana-4 It*s all that ı want.

**Comment by cthbleachbit** [comment]
@SalahAdDin Use a [gnome shell extension](https://extensions.gnome.org/extension/1011/dynamic-panel-transparency/) to do this. This is not something a theme author should do, as gnome does not offer any built-in customization tool for installed themes.

**Comment by cthbleachbit** [comment]
Without an extension to process transparenct at runtime would require editing the theme files themselves. Such customizations shall be per-user, rather than project-wide.

**Comment by nana-4** [comment]
Sorry for the late reply. I understand. (It's a **panel** (or known as _top bar_), not **menu**, though...)

You can customize it by editing the source file as follows:
1. Open `src/gnome-shell/3.26/sass/_common.scss` and edit around `#panel` and `.panel-button` like this:
```patch
@@ -808,7 +808,7 @@ StScrollBar {
 /* TOP BAR */
 
 #panel {
-  background-color: $bg_color;
+  background-color: transparent;
   /* transition from solid to transparent */
   transition-duration: 250ms;
   font-weight: bold;
@@ -846,8 +846,8 @@ StScrollBar {
     -natural-hpadding: 12px;
     -minimum-hpadding: 6px;
     font-weight: bold;
-    color: $inverse_secondary_fg_color;
-    text-shadow: none;
+    color: $inverse_fg_color;
+    text-shadow: 0 1px 2px black;
     transition-duration: $longer_duration;
 
     .app-menu-icon {
@@ -860,17 +860,17 @@ StScrollBar {
     .system-status-icon,
     .app-menu-icon > StIcon,
     .popup-menu-arrow {
-      icon-shadow: none;
+      icon-shadow: 0 1px 2px black;
     }
 
     &:hover {
       color: $inverse_fg_color;
-      text-shadow: none;
+      text-shadow: 0 2px 2px black;
 
       .system-status-icon,
       .app-menu-icon > StIcon,
       .popup-menu-arrow {
-        icon-shadow: none;
+        icon-shadow: 0 2px 2px black;
       }
     }
```

2. Run `./parse-sass.sh` and then run `sudo ./install.sh` as well.

Note: `sassc` needs to be installed to run `./parse-sass.sh`. See [`HACKING.md`](https://github.com/nana-4/materia-theme/blob/master/HACKING.md) for details.
