### ISSUE TITLE
Package for debian

### ISSUE THREAD

**Issue by isaagar** [nana-4/materia-theme#164]
Hi , its nice to have this theme packaged in debian. Let me know if you need any help.

**Comment by thelearnerofcode** [comment]
Related: #44.

**Comment by nana-4** [comment]
Hi, sorry for the late reply.

I had previously planned to make packages for various distributions (including debian) using [Open Build Service](http://openbuildservice.org/), but for several reasons the plan has suffered a setback.

I still don't have enough knowledge of packaging, so I would like to ask for your help if possible. 😃

**Comment by nana-4** [comment]
Hi, @isaagar 

I see you are kindly trying to tackle this issue with https://github.com/isaagar/materia-theme.

Is there any news about this?
Or, is there something I can help with?

Thanks.

**Comment by isaagar** [comment]
@nana-4  really sorry for the delay. Now, I'm working on packaging . I'll let you know if I need any help .

**Comment by nana-4** [comment]
@isaagar No need to be sorry! Thanks for your working. :)

**Comment by isaagar** [comment]
@nana-4  Please, try this deb . https://github.com/isaagar/materia-theme/releases/download/20171130195028-883eb28/materia-theme_20171005_all.deb
Still , some small change required in debian files.

**Comment by nana-4** [comment]
Thank you for your work!
I tested it with Ubuntu 17.10 and it was successfully (un)installed!
![image](https://user-images.githubusercontent.com/9556384/33478554-03a0de22-d6cd-11e7-9a20-44b6626dd7fa.png)

**Comment by isaagar** [comment]
Working on packaging of theme https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888280
Let me know if any issues.

**Comment by nana-4** [comment]
@isaagar Thank you so much!!!
Looks very fine. :)

**Comment by isaagar** [comment]
@nana-4  I have done the packaging which you can see here https://salsa.debian.org/isaagar-guest/materia-gtk-theme . Its in new queue and will be available in Debian unstable in few days.
https://ftp-master.debian.org/new/materia-gtk-theme_20180110-1.html

**Comment by nana-4** [comment]
@isaagar Thanks a lot! 🎉 I'm so happy and can't wait it be available 😃 

BTW, what do you think about sending your [`isaagar/materia-theme`](https://github.com/isaagar/materia-theme) to this repo as a PR?  I thought it would make it easier to maintain the package, isn't it?

**Comment by isaagar** [comment]
@nana-4  Yeah, I'll have to update the debian packaging files before sending PR and it would be nice if you provide DEB files in github release itself.
Also , ftp-master rejected the package due to some missing license information. Here's the comment which I got now 
" Your debian/copyright is missing attributions for Red Hat, Intel, etc. etc. (I
stopped looking there so please look over your entire package.)"
In your repo's COPYING file , only GPL-2+ mentioned and if there are other licenses for some files then let me know I'll update it.

**Comment by nana-4** [comment]
@isaagar Thanks for your information. I'll try to provide DEB files in github release itself.

Sorry, but honestly I don't know what license information is missing. Yes, I licensed `materia-theme` with GPLv2+ only, and if my understanding is correct it should be fine. :/

**Comment by isaagar** [comment]
@nana-4  I have reuploaded package after adding missing attributions for redhat , intel.
I'll let you know about further status.

**Comment by nana-4** [comment]
@isaagar Thanks a lot!!

**Comment by isaagar** [comment]
@nana-4  Package now in unstable https://packages.debian.org/unstable/materia-gtk-theme

**Comment by nana-4** [comment]
@isaagar Awesome! Thanks 🎉

**Comment by isaagar** [comment]
@nana-4 See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892037
We'll need to change gnome-themes-standard to gnome-themes-extra. (for debian)
I'll update it in packaging files.

**Comment by nana-4** [comment]
@isaagar Exactly! So I'll update the README. Thanks!

**Comment by isaagar** [comment]
@nana-4  Uploaded new version v20180321 to the debian . Should we close this bug ?

**Comment by nana-4** [comment]
Yes, we should. I appreciate your cooperation to package in Debian. Thank you very much!
