### ISSUE TITLE
Chrome theme missing manifest file

### ISSUE THREAD

**Issue by RavanH** [nana-4/materia-theme#166]
Hi,

Trying to load the included Chrome theme file into Chrome 62.0.3202.62 (64bit) I get an error about a missing or unreadable manifest file. The theme is not added to the extensions.

To reproduce:
1. Install latest Chrome, version 62.0.3202.62 and go to chrome://extensions
2. Open the chrome folder on /usr/share/themes/Materia<-variant>
3. Drag and drop the .crx files onto the Chrome/Chromium Extensions page: chrome://extensions

**Comment by nana-4** [comment]
Sorry for the late reply, but I couldn't reproduce it.
This may be a problem specific to your environment:
https://askubuntu.com/questions/872572/when-i-try-to-start-chrome-i-get-a-message-that-says-failed-to-load-extension-f

Could you please test whether you can install other themes that are non-hosted on Chrome Web Store?
e.g. `arc-theme.crx`: https://github.com/horst3180/arc-theme/tree/master/extra/Chrome

**Comment by RavanH** [comment]
Strange. The Arc theme installed without issue and trying the crx files in the Materia dark compact directory again, all works just fine!

Can't explain, so closing this issue. Thanks for responding and keeping this beautiful theme alive!
