### ISSUE TITLE
[Grub-Customizer] change text issue

### ISSUE THREAD

**Issue by archqob** [nana-4/materia-theme#167]
- Materia version: Latest Git
- GTK+ 3 version: 3.22.21
- Distribution: Fedora 26
- Desktop environment: GNOME-Shell 3.24.3
- Related application: Grub-Customizer 5.0.6
- Steps to reproduce: Try to chage  Text Like the following Screenshots
- Screenshot(s):
Following Screen Shots will show differences between Materia and Adwaita while changing the text
![screenshot from 2017-10-20 16-44-03](https://user-images.githubusercontent.com/21042432/31828810-1198b6be-b5c4-11e7-9d8a-446897b57ac8.png)
![screenshot from 2017-10-20 16-44-17](https://user-images.githubusercontent.com/21042432/31828816-14903144-b5c4-11e7-810a-f038a3b92abe.png)

**Comment by archqob** [comment]
@nana-4 Hi, any updates on this ?

**Comment by nana-4** [comment]
@archqob So sorry for the late response. Now I've fixed it. Thanks for your report!
