### ISSUE TITLE
Checkboxes in Firefox are too large

### ISSUE THREAD

**Issue by lokesh-krishna** [nana-4/materia-theme#168]
- **Materia version**: v20171005 (Materia Compact)
- **GTK+ 3 version**: 3.22.24
- **Distribution**: Fedora 27 Workstation
- **Desktop environment**: GNOME 3.26
- **Related application**: Firefox 58.0a1
- **Steps to reproduce**: Bookmark any page and open the tags drawer in the pop-up. 

#### Screenshot(s)

![screenshot from 2017-10-25 07-00-38](https://user-images.githubusercontent.com/20235646/31976152-60b3c5ee-b953-11e7-8ccd-f9b5a5044203.png)

![screenshot from 2017-10-25 07-10-33](https://user-images.githubusercontent.com/20235646/31976215-c8a520bc-b953-11e7-9aa9-d4388b669c41.png)

Here is what things look like with Arc-Darker.

![screenshot from 2017-10-25 06-59-51](https://user-images.githubusercontent.com/20235646/31976182-858133ac-b953-11e7-81e5-73054356aa33.png)

![screenshot from 2017-10-25 07-11-08](https://user-images.githubusercontent.com/20235646/31976216-ccca15ee-b953-11e7-9293-35db3a082460.png)

I am not sure if this is an issue with the theme or with Firefox and I am sorry if it is the latter. The checkboxes used in the rest of Firefox are part of Firefox's Photon UI but these seem to use my GTK settings. Here is what checkboxes elsewhere in Firefox look like:

![screenshot from 2017-10-25 07-13-26](https://user-images.githubusercontent.com/20235646/31976265-123fc54c-b954-11e7-9e38-f0978edbd878.png)

**Comment by lokesh-krishna** [comment]
This seems to also affect radio buttons, that too those displayed by the webpage.

![screenshot from 2017-10-25 10-02-45](https://user-images.githubusercontent.com/20235646/31980678-c3826eb0-b96b-11e7-84bc-a4b41ea6706d.png)

Once again, things are a lot better with Arc-Darker.

![screenshot from 2017-10-25 10-03-53](https://user-images.githubusercontent.com/20235646/31980694-e230ec10-b96b-11e7-8fa3-e1476f6a44f4.png)

**Comment by rinaldus** [comment]
I agree, current checkboxes and radiobuttons look awful. I hope, that you will improve them.

**Comment by nana-4** [comment]
Hi, thank you for your report!
I finally confirmed this issue with Firefox **59.0a1** (and with the current _stable_ version it doesn't happen).
I'll fix this. :)

**Comment by lokesh-krishna** [comment]
Thank you so, so much!

**Comment by nermolov** [comment]
Confirming this is an issue for me as well!

**Comment by nana-4** [comment]
@nermolov I should have fixed this bug already. Do you still have this bug?

**Comment by nermolov** [comment]
@nana-4 shoot, I'm using the AUR package which is v20171112 which is out of date, I'll check with the latest version.

**Comment by nana-4** [comment]
@nermolov Please. It should be fixed in the latest release (v20171112).
