### ISSUE TITLE
Improvement of directory structure

### ISSUE THREAD

**Issue by nana-4** [nana-4/materia-theme#170]
Current complex directory structure (and symbolic links) should be simplified, especially for Sass.

The following two `_colors.scss` should be lumped together and all CSSs need to reference it.
- [`src/gnome-shell/3.18/sass/_colors.scss`](https://github.com/nana-4/materia-theme/blob/master/src/gnome-shell/3.18/sass/_colors.scss)
- [`src/gtk-3.0/3.22/sass/_colors.scss`](https://github.com/nana-4/materia-theme/blob/master/src/gtk-3.0/3.22/sass/_colors.scss)

**Comment by isaagar** [comment]
@nana-4 @n3oxmind  Could you make similar to https://github.com/snwh/paper-gtk-theme ?

**Comment by nana-4** [comment]
@n3oxmind Thank you! I appreciate your help!

@isaagar Sorry but I'm not sure what do you mean. `paper-gtk-theme` also has duplicate `_colors.scss` in each `Paper/gtk-3.*` directory...

**Comment by n3oxmind** [comment]
@nana-4, I think I already removed most of the duplicate files (*.scss, index-*.theme). i guess i can unify sass directory if the difference between others sass directories is minor.
