### ISSUE TITLE
Flatpak Theme

### ISSUE THREAD

**Issue by lokesh-krishna** [nana-4/materia-theme#174]
Flatpak apps do not pick up the system's GTK theme and the solution to this, presently, is to provide the theme as an extension to the GNOME runtime. 

Arc, Ambiance, Greybird and Breeze are currently available as Flatpak themes and it would be really nice if Materia too were available as one.

More information regarding this is available here: [Flatpak theming](https://tingping.github.io/2017/05/11/flatpak-theming.html).

**Comment by nana-4** [comment]
It would be great if Materia will support Flatpak, but I'm not sure how it works for now...

By the way, it also seems to work by just placing themes in `~./themes`, even without providing the theme as an extension:

```
ln -s /usr/share/themes/Materia* ~/.themes
```

I'm not sure which is a better solution, but the latter (placing themes in `~./themes`) seems more flexible to me. 😉

**Comment by Raytar** [comment]
I have made manifest files for all of the theme variants. You can find them [here](https://github.com/Raytar/Materia-Flatpak).

**Comment by nana-4** [comment]
@Raytar Sorry for the late reply. And thank you so much for your work! It looks very nice!!

Well, may I submit those files to Flathub (based on the [Submission Guidelines](https://github.com/flathub/flathub/wiki/Submission-Guidelines)) after adding some minor changes? (e.g. correct `metadata_license`, see https://github.com/flathub/flathub/pull/181#discussion_r155929308)

**Comment by Raytar** [comment]
Of course! Happy to help!

**Comment by nana-4** [comment]
@Raytar Thanks! I've submitted a pull request with https://github.com/flathub/flathub/pull/186. Cheers!

**Comment by nana-4** [comment]
Except for _compact_ variants, Materia theme variants are now available in Flatpak. ;)

```
flatpak remote-add flathub https://flathub.org/repo/flathub.flatpakrepo

flatpak install flathub org.gtk.Gtk3theme.Materia
flatpak install flathub org.gtk.Gtk3theme.Materia-dark
flatpak install flathub org.gtk.Gtk3theme.Materia-light
```

**Comment by hackel** [comment]
Thanks for working on this!  Any update on when the compact variants might be included in the Flatpak package?  At the very least, it would be nice if it could at least fall back to the regular Materia(-dark) theme until that happens.  (I imagine this is just a matter of adding a symlink to the build script?)

**Comment by nana-4** [comment]
@hackel I'm sorry for the delay in my response.

Please see flathub/flathub#186. I don't have permission to add the repos. So could _you_ request those repos  in that thread?

**Comment by oja** [comment]
Hi @nana-4 it seems that the *-compact variants of the theme are not in flatpak. I don't know if this is intentional or a mistake, but I would really appreciate it if they could be added. Thanks.
