### ISSUE TITLE
Dropdown box colour 

### ISSUE THREAD

**Issue by rudrab** [nana-4/materia-theme#175]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Materia version
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)
- Distribution (and version)
- Desktop environment (and version)
- Related application (and version)
- Steps to reproduce
- Screenshot(s)

**Comment by rudrab** [comment]
Hi nana-4,
Thanks for your beautiful theme. I discovered it yesterday. I have two questions, and for future purposes, I will create two different threads. First one: I have not found a way to alter the dropdown box from the notification bar(like the notification box). I am not sure if that is hardcoded in somewhere else, but it looks odd. May you have a look?
I am using your late version from git in fedora27.
Thanks,

rudrab
https://github.com/rudrab/Shadow

**Comment by nana-4** [comment]
Sorry but I'm not sure where you are talking about. What is "**dropdown box**"? Are you talking about the **notification box** of **GNOME Shell**? Can you provide a screenshot?

**Comment by rudrab** [comment]
nana-4,
yes, exactly. This is the screenshot: https://photos.app.goo.gl/YWuAS9NHnMolqug13 
Also check, the topbar  is black, as is supposed to be in adwaita. Is this intended?
rudrab
https://github.com/rudrab/Shadow

**Comment by rudrab** [comment]
Sorry, I agree I am an idiot. I have not activated the shell theme (i thought shell as bash.) Its working now.
