### ISSUE TITLE
chrome theme for incognito

### ISSUE THREAD

**Issue by rudrab** [nana-4/materia-theme#178]
Hi,
I have added the chrome theme extension. The problem is I can't see the theme in extension list, and hence, I can't enable the theme for incognito mode. 
Any help?

**Comment by nana-4** [comment]
Hi,

This chrome theme has a common appearance in normal windows and incognito windows. It is intentional.

**Comment by rudrab** [comment]
hi nana-4,
thanks for your reply. Problem is I am not getting the same appearance in incognito and normal window. 
In normal, i get the theme. Do you mean this is normal?

**Comment by nana-4** [comment]
Could you please attach a screenshot?

**Comment by rudrab** [comment]
Thanks, here you go.
BTW, I am not using the COPR (i am in f27). I am using the sourcecode from github.
normal window: https://photos.app.goo.gl/KyheqgHlq61kbQJZ2
incognito window: https://photos.app.goo.gl/ftkAxYG2KTKuqzjw2

**Comment by nana-4** [comment]
Thanks for the screenshots. It seems you have not installed (or not enabled for some reason?) the Chrome theme.

Here are my screenshots of Chromium 62.0.3202.89 with Materia-dark.

*Without* Chrome theme extension:

![image](https://user-images.githubusercontent.com/9556384/32991007-f38423d2-cd76-11e7-993d-6c857cd3a2e5.png)

*With* Chrome theme extension:

![image](https://user-images.githubusercontent.com/9556384/32991014-1bbf7b80-cd77-11e7-919d-9d3e14d37b1e.png)

Did you certainly install the Chrome theme as described in this section?:
https://github.com/nana-4/materia-theme#chrome-theme

**Comment by rudrab** [comment]
Hi nana-4,
Thanks again for your reply. I have added the crx in chrome extension page. Now, it does not show an option to add again, but the crx theme does not appear in extension list either.

**Comment by nana-4** [comment]
OK, I guess you dragged and dropped both extensions (`Materia-dark Theme.crx` and `Materia-dark Scrollbars.crx`) at the same time. You need to drag and drop `.crx` **one by one**.

By the way, any Chrome _theme_ extensions never appear in extension list. Instead you can uninstall the Chrome theme from `chrome://settings`

**Comment by rudrab** [comment]
nana-4, kindly help me with one more.
I have the theme installed in my home folder(~/.themes).
So, to change gdm theme, what should I do?
GTK_THEME=$(gsettings get org.gnome.desktop.interface gtk-theme | sed "s/'//g")
echo $GTK_THEME
Materia-dark-compact
So,
`sudo cp -v --backup /usr/share{/themes/$GTK_THEME,}/gnome-shell/gnome-shell-theme.gresource` for this line, can I do:
`sudo cp -v --backup ~/.themes/$GTK_THEME /usr/share/themes/gnome-shell/gnome-shell-theme.gresource`
?

**Comment by nana-4** [comment]
Well, have you resolved the Chrome theme problem?

Sure. It should work:
```
sudo cp -v --backup {~/.themes/$GTK_THEME,/usr/share}/gnome-shell/gnome-shell-theme.gresource
```

This is equivalent to:
```
sudo cp -v --backup ~/.themes/$GTK_THEME/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource
```

**Comment by rudrab** [comment]
No, I am still trying to find the tab under chrome settings to reinstall chrome theme

**Comment by nana-4** [comment]
You can uninstall chrome theme from "Use GTK+" button. (sorry for non-English screenshot)
![image](https://user-images.githubusercontent.com/9556384/32992289-26c80f82-cd8c-11e7-8338-e56d9a6b2e5d.png)

**Comment by rudrab** [comment]
unfortunately this is what i am getting: https://photos.app.goo.gl/NAfsrNYF2hrDxEi12

**Comment by rudrab** [comment]
done, and working. Thanks a lot

**Comment by nana-4** [comment]
Neat. So I close this.
