### ISSUE TITLE
Using a better way to refresh themes/GDM on GNOME 3

### ISSUE THREAD

**Issue by The-King-of-Toasters** [nana-4/materia-theme#179]
This isn't really a bug per se, but I read once somewhere that themes in GNOME 3 don't have to be refreshed by restarting Gnome Shell. In the [GDM Theme wiki page](https://github.com/nana-4/materia-theme/wiki/GDM-Theme) you state:

>Restart GNOME Shell. (If you are running GNOME on Xorg, press <kbd>Alt</kbd> + <kbd>F2</kbd> then type `r`.)

There is a better way to do this. Instead of just `r`, use `rt` (refresh theme) and you wont have to restart the shell. This method  works for using the custom GDM theme as well.

**Comment by nana-4** [comment]
Oh, I didn't know this, but it's very useful. 😄 
I've just updated the wiki page.

Thanks for teaching me this!
