### ISSUE TITLE
address and dropdown back ground in chrome

### ISSUE THREAD

**Issue by rudrab** [nana-4/materia-theme#180]
Hello,
Please, can you consider a darker address bar and matching address suggestion for chrome? 
using materia-dark theme in chrome, I get: https://photos.app.goo.gl/ANhsjM4PfRfFj2oF3
 which, in my taste and opinion, is not matching and it will be better if you kindly consider a darker back ground.

**Comment by nana-4** [comment]
> which, in my taste and opinion, is not matching

Completely agree with you. But unfortunately, when using the Chrome theme extensions, those colors will be hard-coded and cannot be changed.

I need to consider a way to improve the appearance without using the Chrome theme extension (for the dark variant).

**Comment by rudrab** [comment]
Hi,
One thing which you must have noticed is that if you are using Adwaita dark theme, and GTK theme in chrome, then the colours match. Maybe chrome is, in that case, recognises Adwaita's theme or something other (eg they both have same rgb value for dark theme). 

I am not sure and have no idea. I am just thinking loud. :)
