### ISSUE TITLE
Some color variables are defined outside of _colors.scss

### ISSUE THREAD

**Issue by actionless** [nana-4/materia-theme#183]
Here: https://github.com/nana-4/materia-theme/blob/aa9901ee200cbbdc9aae4de2ca2e0c37baafc130/src/gtk-3.0/3.22/sass/_common.scss#L1578-L1581

That's breaking recoloring the theme's highlighted dropdown.

**Comment by nana-4** [comment]
You are right. I'll bring those (and other remaining) color variables to `_colors.scss`.
Thanks for your report!
