### ISSUE TITLE
Window Titles overlap with top Panel in Overview screen

### ISSUE THREAD

**Issue by user501254** [nana-4/materia-theme#185]
When top bar is at the bottom of the screen (see [BottomPanel](https://extensions.gnome.org/extension/949/bottompanel/)), window titles overlap with the top bar in Overview screen.
This also happened with the default theme but only after updating to the last gnome version.

![screenshot from 2017-12-09 00-06-04](https://user-images.githubusercontent.com/6129517/33780239-1597ddde-dc76-11e7-8396-f029fbaf64a2.png)

- Materia version: 07b0650
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`): 3.22.26
- Distribution (and version): Fedora release 27 (Twenty Seven)
- Desktop environment (and version): GNOME Shell 3.26.2

**Comment by nana-4** [comment]
Thank you for your report. Now I added more space to the bottom of overview.

However, if this issue also happens with the _default_ gnome-shell theme, it would be better to report it to the [BottomPanel](https://github.com/Thoma5/gnome-shell-extension-bottompanel)'s issue tracker.
