### ISSUE TITLE
Do not install `gnome-shell-theme.gresource` by default (for less dependency)

### ISSUE THREAD

**Issue by nana-4** [nana-4/materia-theme#190]
Currently, `./install.sh` generates `gnome-shell-theme.gresource` by default, but this is completely unnecessary for people who don't need [**GDM theme**](https://github.com/nana-4/materia-theme/wiki/GDM-Theme). Also, since changing GDM theme has risks, it is treated as an _option_.

Therefore I'd like to stop generating `gnome-shell-theme.gresource` by the install script to reduce install dependency (`glib-compile-resources`). Instead, I'm going to describe how to generate `gnome-shell-theme.gresource` in the [wiki](https://github.com/nana-4/materia-theme/wiki/GDM-Theme).

Please let me know if you have an opinion. If there is no objection, I will remove `glib-compile-resources` command from the install script by the next release.

(_Note that this doesn't mean to stop supporting GDM theme._)

**Comment by DarthWound** [comment]
I agree, for the exact same reasons.
