### ISSUE TITLE
theme shrinks icons on xfce panel and cuts off left/right edges of start button

### ISSUE THREAD

**Issue by asqwerth** [nana-4/materia-theme#191]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Materia version - downloaded from your github page on 24 Nov 2017
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`) - gtk3.22.11
- Distribution (and version) - MX17-RC, Debian Stretch
- Desktop environment (and version) XFCE 4.12
- Screenshot(s)
![start-materia](https://user-images.githubusercontent.com/22598625/34009511-2ec53c34-e144-11e7-9ea3-de35b295266f.png)

- does not happen with Greybird:

![start-greybird](https://user-images.githubusercontent.com/22598625/34009543-4b79667a-e144-11e7-9051-5d8436162e92.png)

- nor Arc:
![start-arc](https://user-images.githubusercontent.com/22598625/34009567-5b19facc-e144-11e7-8616-72d889f4691b.png)

- nor Adapta:

![start-adapta](https://user-images.githubusercontent.com/22598625/34009581-6954db70-e144-11e7-8212-599b5831183e.png)

**Comment by nana-4** [comment]
Thank you for your report. Currently, Materia doesn't support Xfce. (see #60) But I receive many bug reports regarding Xfce, so I would like to support it as soon as possible. (If possible, next release?)

However, this duplicates with #60, so I would like to close this as `duplicate`.
