### ISSUE TITLE
Button color on modal dialogs

### ISSUE THREAD

**Issue by pintsel** [nana-4/materia-theme#194]
Hi,
Our custom Java app needs buttons enabled for modal dialogs, so we enable it like this:
In "/usr/share/themes/Materia/metacity-1/metacity-theme-2.xml" we change
<frame_geometry name="modal" title_scale="small" hide_buttons="true" parent="normal"> to
<frame_geometry name="modal" title_scale="small" **hide_buttons="false"** parent="normal">

This works fine with Materia Light and Dark, but not with default Materia. Default button color is then white and basically invisible:

Materia Light with example modal dialog (print dialog in Firefox):
![1](https://www.upload.ee/image/7833041/materia1.PNG)

Materia:
![2](https://www.upload.ee/image/7833042/materia2.PNG)

I wonder, which section in metacity-theme-2.xml defines this?

DE: Mate 1.18 on Ubuntu 17.10

-EDIT-
Found it - it's right at the beginning of the file, under "meaningful constants", but it's tied to the white title color (as all the main windows have dark title-bar and white titles). 
It's possible to play around with "C_title_focused" and "C_title_unfocused" with more gray shades, so the button becomes visible!

Considering the consistency - maybe these dialogs should also have the dark title-bar, like the rest of the windows (in default Materia theme)? 
Like this example from another theme:
![3](https://www.upload.ee/image/7834083/materia3.PNG)

**Comment by nana-4** [comment]
Hi, thank you for your report!

Certainly, it may be better to have a dark background with buttons in the modal dialogs as well.
So I will update it when I have time. :)
