### ISSUE TITLE
Menubar's colors does not match titlebar's.

### ISSUE THREAD

**Issue by chuutatsu** [nana-4/materia-theme#200]
- Materia version: Latest version from Github (manual install two days ago, following the readme)
- GTK+ 3: 3.22
- Distribution: Manjaro
- Desktop environment: Mate 1.18
- Problem: In latest Materia default theme, the menubar's colors does not match the titlebar's.

![screenshot at 2018-01-20 08-34-46](https://user-images.githubusercontent.com/24815847/35178551-5b7f4f72-fdbd-11e7-96cb-7a5c4d4dd9d8.png)

The Materia Dark and Light theme doesn't affected, though.

**Comment by nana-4** [comment]
It's by design.

Users can lower the window with middle-clicking the titlebar, but cannot with the menubar. So I've separated the colors. But in Materia dark and light, since menubars are already too dark, I used the same colors for the titlebars.

**Comment by chuutatsu** [comment]
Alright. Thanks for explaining.
