### ISSUE TITLE
[Question] Transparent Panel in Materia Light

### ISSUE THREAD

**Issue by chuutatsu** [nana-4/materia-theme#201]
I am using Mate Desktop. The panel in Materia and Materia Dark were dark and not transparent. But...

The panel was transparent in Materia Light. Is this intentional?
![screenshot at 2018-01-20 08-35-46](https://user-images.githubusercontent.com/24815847/35179254-29293aa4-fdc9-11e7-874c-cd0c7f155c2b.png)

Just asking.

**Comment by nana-4** [comment]
Yes. It is intentional. :)

**Comment by chuutatsu** [comment]
Alright. Thanks for explaining!
