### ISSUE TITLE
White border + no close button at the top of window manager theme (in dialog boxes

### ISSUE THREAD

**Issue by chuutatsu** [nana-4/materia-theme#204]
Longtime user of Materia here. I usually used the light version.

However, when I used Materia Dark version, a little tiny bug bothered me. I found out that some small dialog boxes (like below images) has white border on the top of its window manager. I am using Mate Desktop 1.19, GTK 3.22 and latest Materia from Github.

![screenshot at 2018-02-15 11-48-28](https://user-images.githubusercontent.com/24815847/36241003-305e967a-1246-11e8-95ac-f5fe4dec8ff4.png)

This bug also appeared on Materia's derivative theme Equilux. (https://github.com/ddnexus/equilux-theme/issues/16)

It also has no close window button too. (The screenshot used Materia Light theme)
![screenshot at 2018-02-15 11-46-35](https://user-images.githubusercontent.com/24815847/36240952-f4955c82-1245-11e8-8f93-70ddbbea97dc.png)

Here are my questions:
1. Are those white border intentional (by design)?
2. If not, please fix it. 
3. Will you readding those missing close buttons too?

Thanks in advance!

**Comment by nana-4** [comment]
Hi, thanks for your feedback, again. :)

1. The white border seems to be a bug.
2. So I'll fix that. :)
3. Probably it's a same issue as #194. I'm going to add buttons to the dialogs.

**Comment by chuutatsu** [comment]
Alright thanks! I'll wait for the theme to be updated.

**Comment by n3oxmind** [comment]
@chuutatsu @nana-4 
what cause this problem is `titlebar_highlight_color` in `_colors.scss` file; changing its value to `transparent` will fix the problem.
further investigation in `_common.scss` file its appear that this line causing the problem:
`1045   box-shadow: $shadow_1, inset 0 1px $titlebar_highlight_color;`

**Comment by nana-4** [comment]
Fixed. Please let me know if issues still remain in this window manager (Metacity/Marco).
