### ISSUE TITLE
Square side in gedit search button

### ISSUE THREAD

**Issue by flipflop97** [nana-4/materia-theme#209]
The 'next' button in the gedit search box has a square right side when hovered, which looks strange. The 'previous' button appears round as expected.

- Materia version
3.26.20180110
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)
3.22.28
- Distribution (and version)
Arch Linux
- Desktop environment (and version)
Gnome 3.26.2
- Related application (and version)
gedit 3.22.1
- Steps to reproduce
Search in gedit and hover the 'next' button
- Screenshot(s)
![gedit bug](https://user-images.githubusercontent.com/13943260/36998873-b1727430-20be-11e8-92e9-0f5ab73dc35c.png)

**Comment by nana-4** [comment]
I confirmed this bug. Thanks for the clear report!

**Comment by flipflop97** [comment]
Never mind, just noticed that flatpak apps use a different (older) version of the theme. All is fine with the native gedit.
