### ISSUE TITLE
Help With Creating a New Theme 

### ISSUE THREAD

**Issue by moriel5** [nana-4/materia-theme#213]
Hi, I want to create a new theme, that is based upon Materia and Arc, with a Adwaita's window controls (but slimmer and flatter).

So far, using the "Hacking.md" file, I was able to change the assets' accent color from Materia's pink to Arc's blue, however since I am not sure how to modify the PNG's, all I get is a Materia theme with a once-only momentary blue, which immediately reverts to pink.

If I may be so rude to ask, can I please recieve some help on this project, seeing as I have absolutely no experience in these matters (nor am I much of an artist, yet)?

In addition, I understand that I'll have to modify "arc-icon-theme" if I wish to have all that with Adwaita's window control's (I prefer a setup where Arc is the primary icon theme, with Faba relying on Adwaita (no Moka for me) as a backup)), I would also be very thankful for help on that front.

**Comment by nana-4** [comment]
> I am not sure how to modify the PNG's

Did you run `./render-assets.sh` in the `materia-theme` directory after editing `src/gtk/assets.svg`, `src/gtk-2.0/assets.svg` and `src/gtk-2.0/assets-dark.svg`? You also need to run `./install.sh` or `./test.sh` to see the changes on the theme.

> with a Adwaita's window controls (but slimmer and flatter)

I'm not sure what "Adwaita's window controls" is. Arc has special window control buttons (by PNG assets e.g. [this](https://github.com/horst3180/arc-theme/blob/master/common/gtk-3.0/3.20/assets/titlebutton-close.png)), but Adwaita and Materia have normal (flat) window control buttons. Can you clarify it with mockup etc?

**Comment by moriel5** [comment]
> Did you run `./render-assets.sh` in the `materia-theme` directory after editing `src/gtk/assets.svg`, `src/gtk-2.0/assets.svg` and `src/gtk-2.0/assets-dark.svg`? You also need to run `./install.sh` or `./test.sh` to see the changes on the theme.

Yes, I did, and `assets.svg` was updated accordingly.
And yes, I used `install.sh`.

Update: I did not edit `gtk-2.0/assets.svg`, nor `gtk-2.0/assets-dark.svg`, I'll fix that (although I do not use dark themes, so I did not think of editing the dark variant while testing).
>e.g. [this](https://github.com/horst3180/arc-theme/blob/master/common/gtk-3.0/3.20/assets/titlebutton-close.png)), but Adwaita and Materia have normal (flat) window control buttons. Can you clarify it with mockup etc?

That example mostly answers it.
I was hoping to use the normal window control buttons, however `arc-icon-theme` apparently modifies it to show a flat version of `arc-gtk-theme`'s window controls (I'll upload a screenshot when I'll be on my laptop, I am currently posting this from my phone).

And thank you very much for your consideration.

**Comment by nana-4** [comment]
> Yes, I did, and assets.svg was updated accordingly.
And yes, I used install.sh.

So, are your PNG assets in `/usr/share/themes/Materia/gtk-assets` properly changed to Arc's blue? If so, I guess you have installed Materia to both `~/.themes` and `/usr/share/themes`. You need to delete `Materia*` dirs from either one (pink one).

> I did not edit gtk-2.0/assets.svg, nor gtk-2.0/assets-dark.svg, I'll fix that (although I do not use dark themes, so I did not think of editing the dark variant while testing).

But if you don't need dark variant, you don't need to edit `gtk-2.0/assets-dark.svg` :)

> I was hoping to use the normal window control buttons, however arc-icon-theme apparently modifies it to show a flat version of arc-gtk-theme's window controls

I see. So I think you'll have to change the `window-*-symbolic.svg` [icons in `arc-icon-theme`](https://github.com/horst3180/arc-icon-theme/tree/master/Arc/actions/symbolic).

**Comment by nana-4** [comment]
Hmm, possibly you are misunderstanding about check boxes and radio buttons. In Materia, [`checkbox-checked.png`](https://github.com/nana-4/materia-theme/blob/master/src/gtk/assets/checkbox-checked.png) etc. are used only for **GTK+ 3.18**. For **GTK+ 3.20 or later**, [`checkbox-checked-symbolic.svg`](https://github.com/nana-4/materia-theme/blob/master/src/gtk/assets/scalable/checkbox-checked-symbolic.svg) etc. are used and recolored by CSS. So if you want to change the pink colors of `check`, `switch`, etc. for GTK+ 3.20 or later, you have to edit [`$accent_color`](https://github.com/nana-4/materia-theme/blob/master/src/_sass/_colors.scss#L69) to your color and run `./parse-sass.sh`.

**Comment by moriel5** [comment]
Actually, I did not check very deep into what I was changing, I just changed what was pink to blue.

**Comment by nana-4** [comment]
> the PNGs remain pink.

Strange. Do your PNG assets in `materia-theme/src/gtk/assets` also remain pink?

> How should I go about it?

I'm not an icon theme maker or `arc-icon-theme` user, so I don't know exactly. But I think it'll be okay if you download the source of the icon theme and change the SVGs then install the icon theme according to README.

**Comment by moriel5** [comment]
> Strange. Do your PNG assets in `materia-theme/src/gtk/assets` also remain pink?

Affirmative.

> I'm not an icon theme maker or `arc-icon-theme` user, so I don't know exactly. But I think it'll be okay if you download the source of the icon theme and change the SVGs then install the icon theme according to README.

I'll try that when I'll be on my laptop.

>Also can you attach a screenshot of `gtk3-widget-factory` applying your ongoing theme?

I'll be glad to, I'll just need to install it first.

**Comment by moriel5** [comment]
Sorry, I had fallen asleep last night.

In the end I did not have time to edit `arc-icon-theme`, however here are screenshots of `gtk3-widget-factory:
![screenshot from 2018-03-14 11 58 04](https://user-images.githubusercontent.com/20175297/37395744-ab5abe14-277f-11e8-92bb-f15cd3c01c64.png)
![screenshot from 2018-03-14 11 58 20](https://user-images.githubusercontent.com/20175297/37395746-ab88b1ca-277f-11e8-9d6a-2a7c1a73754a.png)
![screenshot from 2018-03-14 11 58 38](https://user-images.githubusercontent.com/20175297/37395748-abb158b4-277f-11e8-8fbd-0d73c4227116.png)

**Comment by moriel5** [comment]
It's fine, don't worry about it.
Actually, I am sorry for taking so much of your time.

If I'll be able to continue, I'll notify you.

**Comment by nana-4** [comment]
I don't know if you are still interested in this, but before closing I'll write down the detailed way to modify the PNGs:

0. First, remove installed Materia themes to make sure:

```
sudo rm -rf /usr/share/themes/Materia{,-dark,-light}{,-compact}
rm -rf ~/.local/share/themes/Materia{,-dark,-light}{,-compact}
rm -rf ~/.themes/Materia{,-dark,-light}{,-compact}
```

1. Clone `materia-theme` and move its directory in the terminal:

```
git clone https://github.com/nana-4/materia-theme.git
cd materia-theme
```

2. Open SVG files in text editor, then edit & save colors:

```
gedit src/gtk/assets.svg src/gtk-2.0/assets.svg src/gtk-2.0/assets-dark.svg
```

3. Confirm those SVG colors are changed with image viewer:

```
eog src/gtk/assets.svg src/gtk-2.0/assets.svg src/gtk-2.0/assets-dark.svg
```

4. Run `./render-assets.sh` to re-render PNG assets:

```
./render-assets.sh
```

5. Run `./install.sh` script:

```
sudo ./install.sh
```

6. Reload Materia theme.

---

If you couldn't succeed even with this, sorry but I can't help you anymore :/ Please ask in other community forums.

Closing.

**Comment by moriel5** [comment]
Thanks, I'll try this when I have the time.
I'm sorry about my late reply.
