### ISSUE TITLE
GDM glib-compile resources - link xml into all version folders

### ISSUE THREAD

**Issue by nathaneltitane** [nana-4/materia-theme#215]
I've just reinstalled and rebuilt the Materia theme on my Fedora 27 workstation edition. Steps are relatively clear as to do so in your wiki, but, when building, ii had to manually copy the gnome-shell.css out of the ./src/gnome-shell/3.26 folder back into /src/gnome-shell for glib to compile.

Would be nice to have an option in the install script to detect the currently installed main version of gnome-shell and have the gdm be replaced on install as well.

**Comment by nathaneltitane** [comment]
also, the glib-compile-resources binary is part of the glib2-devel install package on fedora. please indicate in wiki?

**Comment by nana-4** [comment]
Sorry, but I don't understand why you took such a method. If you are using `v20180311` or latest git of  `materia-theme`, you should not need to do more than written in the wiki.

Are you using an older version of Materia?

**Comment by nana-4** [comment]
> also, the glib-compile-resources binary is part of the glib2-devel install package on fedora. please indicate in wiki?

It should already have been written in the [Requirements](https://github.com/nana-4/materia-theme/wiki/GDM-Theme#requirements) section. :)

**Comment by elParaguayo** [comment]
I'm using 20180311 on Arch and I can't get the gdm lockscreen to work. As above, I've tried manually copying the css file but it doesn't seem to be working. The gresource file compiles okay and I move it to /usr/share/gnome-shell but reloading the theme and logging me out doesn't seem to have any noticeable effect.

The previous instructions worked before moving to gnome 3.28.

**Comment by nana-4** [comment]
I would like to close this - since there is no reply from the original reporter and

> Would be nice to have an option in the install script to detect the currently installed main version of gnome-shell and have the gdm be replaced on install as well.

was achieved with #231 :)

**Comment by nathaneltitane** [comment]
Works like a charm
