### ISSUE TITLE
Slow checkbox and radio buttons animations

### ISSUE THREAD

**Issue by Leva7** [nana-4/materia-theme#219]
Version info:
- Materia version: latest (cloned from repo)
- GTK+ 3 version: 3.22.25
- Distribution (and version): Ubuntu 17.10.1
- Desktop environment (and version): GNOME 3.26

The checkboxes and radiobuttons that are embedded in menu items seem to have slow animations - they don't play right away. The regular checkboxes are completely fine though.

![Here's a demo](https://user-images.githubusercontent.com/15035286/37671046-a709316c-2c8c-11e8-8b50-8d53b1c90250.gif)

**Comment by actionless** [comment]
can reproduce the same on Arch GTK 3.22.26-1

**Comment by nana-4** [comment]
Thanks for the report! This issue has already been reported in #148. So I'd like to close this as a duplicate.

(However I'd like to fix it as soon as possible... 💭)
