### ISSUE TITLE
old primary and secondary color with new accent color

### ISSUE THREAD

**Issue by rudrab** [nana-4/materia-theme#224]
Hi,
For me, the ideal combination is the old blue-blackish primary and secondary colour with the new accent colour. 
I tried the changecolor script, but  I don't know the old colour's value and where to put the output file.
(I am in fedora, with from the copr build).
Kindly help.

**Comment by actionless** [comment]
for fedora oomox GUI tool avalaible in COPR to configure the materia:
https://github.com/actionless/oomox/#centos-fedora-mageia

**Comment by nnnn20430** [comment]
sigh... i chose the theme cause i liked the combination of blue grey and pink, oh well imma go find another one

**Comment by n3oxmind** [comment]
@nnnn20430 Good luck finding another 1, not just because you didn't like the accent color you gonna abandon a theme. this theme is a mile better than any other theme i came across.

BTW, you can always open the _colors.scss file and change the colors before installing (take you like 30 sec).

**Comment by rudrab** [comment]
hi, thanks for your reply. problem is what was the exact colour?

**Comment by actionless** [comment]
@n3oxmind that won't change the color of image assets (for example, checkboxes) -- you need to use `change_color.sh` script to really change the palette of the theme

**Comment by rudrab** [comment]
@nnnn20430 , you can make your opinion heard by giving your suggestions at #220 . If you just keep hoping only for the fact that you don't like a certain feature of any certain software, you are not doing good to either you or open-source projects. believe me, oss developers love to hear any suggestions. Particularly, people involved in this project encourages forking and help a lot to make your ideal theme. Just ask. This is an absolute minimum requirement we, the developers expect from the users and try to do our best.

**Comment by n3oxmind** [comment]
@actionless, is that noticeable can you show me the difference if you can (maybe its hard for me to notice it #colorblind) that will be very helpful and will use it for my script.
just to make sure, are you saying that every time you change the bg color you need to render the assets based on the new bg color?

here is my accent color without rendering just changed the color in the _colors.scss and installed it. Do you see anything suspicious?
![3 20_003](https://user-images.githubusercontent.com/10103340/37940572-415080f0-311e-11e8-9c72-1c4cb24b158a.png)
![gnome tweaks_004](https://user-images.githubusercontent.com/10103340/37940578-492f88ac-311e-11e8-83ea-e6bc6898582b.png)

**Comment by actionless** [comment]
try to change radiobuttons(A-Z, Z-A, ...) to some different color without rendering assets

**Comment by actionless** [comment]
to see the difference you need to actually change it with change_color script as suggested above :-)

**Comment by actionless** [comment]
also if you colorblind you can use `compare` tool from imagemagick suite to compare images technically (or use something less sophisticated as `gpick`)

**Comment by n3oxmind** [comment]
thanks for the tools, can you answer this question for me please this will help me a lot.
when is rendering assets required ?

**Comment by actionless** [comment]
https://github.com/nana-4/materia-theme/issues/224#issuecomment-376370193

**Comment by n3oxmind** [comment]
hehehe, okay thanks

**Comment by nnnn20430** [comment]
@n3oxmind i already like another theme solarc

**Comment by n3oxmind** [comment]
@nnnn20430 , Cool I will check it out. just pick the one you like man its fine. if you like the old materia color scheme you still can download it and use it.
If you still struggling and cant find the color you looking for, write down the colors you like and I will see what i can do to help you.

**Comment by actionless** [comment]
@nnnn20430 wo-wo, don't be so indimidating, please :-)

**Comment by svnset** [comment]
@nnnn20430 why would you advertise another theme here? Stop doing this pls and move on to whatever you desire. (Even so we provide a script to choose whatever color you like...?!)

**Comment by svnset** [comment]
@nnnn20430 just like I said, use whatever you like. If you put it like in your last post, it's totally fine. My only point is that upstream issues are the wrong places to share information which are not related to the specific project. There are forums or other platforms to share this information. So the part about beeing unhappy with the new colorscheme is good, the part about posting another project not :P

**Comment by actionless** [comment]
Finally added all the Materia theme templates:

![2018-03-31--1522531870_2281x2098_scrot](https://user-images.githubusercontent.com/1655669/38167762-aed9f432-353b-11e8-935a-98b012ca358f.png)
![2018-03-31--1522531859_2281x2098_scrot](https://user-images.githubusercontent.com/1655669/38167771-eddc3d8e-353b-11e8-8e60-197c1e10ef1c.png)
![2018-03-31--1522531863_2281x2098_scrot](https://user-images.githubusercontent.com/1655669/38167772-f206ab24-353b-11e8-98d2-299d1d62b81b.png)
![2018-03-31--1522531866_2281x2098_scrot](https://user-images.githubusercontent.com/1655669/38167774-f4bbdab0-353b-11e8-875c-257406b1082b.png)
![2018-03-31--1522531942_2281x2098_scrot](https://user-images.githubusercontent.com/1655669/38167776-f6be540a-353b-11e8-8112-60794839d0ba.png)

**Comment by nana-4** [comment]
We've dropped the so-called _secondary color_. (See https://github.com/nana-4/materia-theme/issues/220#issuecomment-460316054 for details.) So this should have been obsolete now.

I'm gonna close this issue.
