### ISSUE TITLE
Wrong path inside gtk*.scss files of src/gtk/{3.18,3.20,3.22}

### ISSUE THREAD

**Issue by n3oxmind** [nana-4/materia-theme#227]
gtk*.scss files missing underscore.
here is a sample of the current paths:
$variant: 'dark';
$titlebar: 'dark';
$compact: 'false';

@import '../../_sass/gtk/variables';
@import '../../_sass/colors';
@import '../../_sass/gtk/drawing-3.20';
@import '../../_sass/gtk/common-3.20';
@import '../../_sass/gtk/apps-3.20';
@import '../../_sass/gtk/colors-public';

all paths missing underscore before {variables,colors,drawing ...}.

**Comment by n3oxmind** [comment]
update:
Error: File to import not found or unreadable: ../../_/sass/gtk/_variables.
       Parent style sheet: /home/n30x/GitRepos/materia-theme-20180321/src/gtk/3.22/gtk-light.scss
        on line 5 of src/gtk/3.22/gtk-light.scss
>> @import '../../_/sass/gtk/_variables';
_/saas should be /_sass

**Comment by svnset** [comment]
What are you talking about? Which version are you running there?

**Comment by n3oxmind** [comment]
My bad, gonna close this all paths are OK. for some reason I couldn't compile `sassc` the problem on my side.
