### ISSUE TITLE
The "Set shortcut" button's shadow is cut off

### ISSUE THREAD

**Issue by Leva7** [nana-4/materia-theme#229]
Version info:
- Materia version: latest (cloned from repo)
- GTK+ 3 version: 3.22.25
- Distribution (and version): Ubuntu 17.10.1
- Desktop environment (and version): GNOME 3.26

If you navigate to Settings > Devices > Keyboard and try to add a new shortcut, you'll be presented with a following popup:
![modal](https://user-images.githubusercontent.com/15035286/37975588-16c83bf8-31f9-11e8-90b2-a6ef028f76dd.png)

Here's the same popup, this time the button is under hover:
![modal on hover](https://user-images.githubusercontent.com/15035286/37975861-aab6606a-31f9-11e8-953d-0f280c0f9182.png)

The problem is that the shadow around the button seems to be cut off at the bottom. There are no issues with displaying this button in Adwaita (even though it obviously doesn't feature shadows), if that helps.

**Comment by nana-4** [comment]
Thanks for reporting the bug.

The drop-shadow problem sometimes occurs not only in that app. But sadly, it cannot be fixed by theme. :(
