### ISSUE TITLE
Cinnamon Theme for materia

### ISSUE THREAD

**Issue by smurphos** [nana-4/materia-theme#232]
@nana-4 @actionless 

Hi both,

Just a heads up that I've started work on making a Cinnamon theme for Materia. I'm following the design cues of the Gnome Shell theme and were applicable reusing the Gnome Shell assets and code for equivalent elements. I may take a peek at Adapta's Cinnamon theme for inspiration for any Cinnamon elements that don't exist in Gnome shell.

Just wanted to check that would be welcome before getting too far into it. All being well I'd expect to have an initial commit/PR in about a week or so for review. If there is anything you want me to consider specifically please let me know.

actionless - having done this I may well be in a position to do the reverse for the oomox-gtk-theme - port in a Gnome Shell theme using the existing Cinnamon theme as the design cue. Won't be quick - I've had a few weeks with plenty of spare time but that is coming to an end shortly.

**Comment by nana-4** [comment]
Thank you for trying to make the Cinnamon theme! Of course it's a big welcome!

> I'm following the design cues of the Gnome Shell theme and were applicable reusing the Gnome Shell assets and code for equivalent elements.

That's very good idea :+1:

Just one question (to be sure):

Which theme is you planning to use as a base for the Cinnamon theme?
Default Cinnamon theme? Oomox? Adapta? Or others?
In any case, it needs to be able to ship as GPL version 2 or later.

**Comment by nana-4** [comment]
@smurphos Sounds great! Thanks :D
