### ISSUE TITLE
Artefacts with Gnome TODO

### ISSUE THREAD

**Issue by randUsr** [nana-4/materia-theme#234]
The new redesigned Gnome TODO 3.28 has artefacts when unfolding tasks at the edges.

![GnomeTodoBug](https://user-images.githubusercontent.com/3942794/38492074-2354711c-3bee-11e8-8caf-ea400c7c758c.png)

Using Materia v20180321 on Archlinux with Gnome 3.28

**Comment by nana-4** [comment]
Thanks for the report!

I confirmed this. I'll fix it as soon as possible.
