### ISSUE TITLE
materia mate calculator button spacing is too close

### ISSUE THREAD

**Issue by LoveChocoCat** [nana-4/materia-theme#237]
i have issues with the mate calculator app button spacing si too close so it is a bit hard to see each different key
![screenshot at 2018-04-11 17-58-51](https://user-images.githubusercontent.com/37618453/38612831-172f1ed0-3db2-11e8-8ae5-15479e51c3c2.png)
this is the with one of default mate themes 
![screenshot at 2018-04-11 18-01-12](https://user-images.githubusercontent.com/37618453/38612909-575ffaec-3db2-11e8-8b9c-6dd1300098e2.png)
**the materia version is this materia-theme-git-r666.448d505-1**
**the gtk+ is 3.22.29**
**my distro is arch linux**
how to reproduce the problem step is just open the mate calculator app
can i have a suggestion i think you have to adjust the shadow and the spacing a little bit far from each button so it is more easy to see

**Comment by nana-4** [comment]
I reported this issue to the upstream app, since I thought this is rather an upstream issue.

Also this app doesn't have any specific style classes, so it's difficult to control the style by the theme.
