### ISSUE TITLE
Theme not working in top bar and login screen since latest update on Ubuntu 18.04

### ISSUE THREAD

**Issue by nomistrebla** [nana-4/materia-theme#238]
- Materia version: 20180321-1
- GTK+ 3 version: 3.22.29-3ubuntu1
- Distribution: Ubuntu 18.04 Beta
- Desktop environment: Gnome 3.28.0
- Steps to reproduce: Install latest updates on Ubuntu 18.04

![image](https://user-images.githubusercontent.com/17678744/38661863-9619c1d4-3e32-11e8-9939-0dce79b3ad1d.png)
![image](https://user-images.githubusercontent.com/17678744/38661888-b38bdb1c-3e32-11e8-92ac-6e5c3a024479.png)

Since the last system update on Ubuntu 18.04 Beta (unfortunately, I don't know what exactly changed), the top bar, the dock and the login screen are back to the default Ubuntu styles. The rest of the system still uses the Materia theme as before. I tried redoing the steps described in the wiki in order to install the GDK theme (overwriting the `gnome-shell-theme.gresource` file) but it had no effect. Any ideas on what's going on?

**Comment by nana-4** [comment]
Did you also change the `ubuntu.css` file as written in the wiki?

**Comment by nomistrebla** [comment]
> Did you also change the ubuntu.css file as written in the wiki?

I did that now and everything is back to normal :+1: Thank you!

I would suggest to change the following line in the wiki

> For Ubuntu 17.10, you also need to back up the following file:

so that it is clear that Ubuntu 18 users have to do this too.

**Comment by nana-4** [comment]
Yeah, you're right. :+1: I've added "**or later**" to the sentences. Thanks for your advice.

Closing.
