### ISSUE TITLE
GTK3.18 - references to missing assets.

### ISSUE THREAD

**Issue by smurphos** [nana-4/materia-theme#240]
If you report a bug or ask a question, please include the following information as required:
- Materia version - Master https://github.com/nana-4/materia-theme/tree/df190371a6c7f4f83be276343c75cd150876ee69
- GTK+ 3 version 3.18
- Distribution - Mint 18
- Desktop environment Cinnamon 3.6.7
- Related application N/A
- Steps to reproduce Set GTK3 theme and review x-session-errors
- Screenshot(s)

Hi,

Just noted a few references in the GTK3.18 theme to non-existent assets which are throwing xsession-errors.

They are `text-select-start*`, `text-select-end*`, `scale-horz-marks-before-slider*`

They are referenced in this section of scss - `_common_3.18.scss - lines 2286 to 2314`

**Comment by nana-4** [comment]
I've fixed it. Thanks!
