### ISSUE TITLE
No slider when adjusting brightness/volume under MATE

### ISSUE THREAD

**Issue by gabrc52** [nana-4/materia-theme#243]
- Materia 20180321-1
- Ubuntu MATE 18.04 (beta)
- MATE 1.20.1

When pressing brightness/volume keys:

![volume](https://user-images.githubusercontent.com/24363938/39332589-8cca5314-496d-11e8-9ccb-206242ca5adb.png)
![brightness](https://user-images.githubusercontent.com/24363938/39332597-90ca5b12-496d-11e8-9ccc-5dde2789a33c.png)

There should be a meter showing the volume/brightness level. This is how the default theme (Ambiant-MATE) looks like:

![screenshot at 2018-04-26 16-21-27](https://user-images.githubusercontent.com/24363938/39332762-0d733c6a-496e-11e8-8b1b-4c50906d9959.png)

**Comment by gabrc52** [comment]
![screenshot at 2018-04-29 16-07-55](https://user-images.githubusercontent.com/24363938/39411042-d5c1ef8a-4bc7-11e8-8fc3-c122dde9198a.png)
This is how Adapta looks like.

**Comment by nana-4** [comment]
I've fixed it. Thanks for your report!
