### ISSUE TITLE
Mate volume onscreen indicator doesn't show level while changing.

### ISSUE THREAD

**Issue by pyaazkaparatha** [nana-4/materia-theme#244]
Occurs with materia not menta
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

-  Materia 21/3/2018
- GTK+ 3 version 3.22.26
- Fedora Mate 27
- Mate 1.20.1

The screen volume indicator doesn't show the level while changing volume.

**Comment by nana-4** [comment]
Fixed. Thanks!
