### ISSUE TITLE
AUR package moved to Arch Community repo

### ISSUE THREAD

**Issue by protesilaos** [nana-4/materia-theme#245]
Just to note that the AUR package has been moved to the [Arch Community repo](https://www.archlinux.org/packages/community/any/materia-gtk-theme/). 

Your README needs to be updated accordingly. The link to the AUR page gives a 404 error. Installation can now be done with:

```sh
sudo pacman -S materia-gtk-theme
```

**Comment by ArchangeGabriel** [comment]
https://github.com/nana-4/materia-theme/pull/242

**Comment by protesilaos** [comment]
Ah missed that. Thanks!
