### ISSUE TITLE
Invalid ID attribute value

### ISSUE THREAD

**Issue by RazrFalcon** [nana-4/materia-theme#246]
By the XML/HTML/SVG [spec](https://www.w3.org/TR/html4/types.html#type-id) the `id` attribute
> must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").

But in the [src/gtk/assets.svg](https://github.com/nana-4/materia-theme/blob/1259e9f02bdccaf1c7f8499f9c3a6c9a3d5192c1/src/gtk/assets.svg) filter id's are set to `1` and `2` which is incorrect and may cause rendering errors. Also, rect's with `16x16`, `21x21`, etc.

There are a lot more warnings that you can check via https://validator.w3.org/.

**Comment by nana-4** [comment]
Now I've fixed it (except for Inkscape-specific error/warning which even pure Inkscape SVG has).

Thanks for pointing it out!
