### ISSUE TITLE
Add text shadow to increase contrast for light text on light backgrounds

### ISSUE THREAD

**Issue by AndreasBackx** [nana-4/materia-theme#248]
I'm creating my own theme based on Materia with the help from the `HACKING.md` file. Everything goes great (thank you for the great hacking guide), but I've got the feeling that Materia expects colors like the accent color to be a darker color so white text works on it. However my light text isn't really legible with a brighter background image. You can mostly get around this with using the inverse colors, but this doesn't always get used. For example in warning boxes the text remains the original foreground color, not the inverted foreground color. For this and to provide the option to use light foreground colors on bright background, I'd love it if it were possible to have some text shadow.

I did a small amount of searching and found that GTK supports CSS3's `text-shadow` property. However I couldn't get it to work. I tried to add it to the buttons, but it didn't seem to do anything.

Here's an example of where text shadow would be useful:

![Screenshot](https://i.imgur.com/X7OBU87.png)

When I looked at where I would have to add text shadow, it does look like I can use a bit of help as the amount of SCSS is huge. Where should I start with this, is this perhaps something that could make it into Materia itself?

**Comment by n3oxmind** [comment]
@AndreasBackx , try this script [customscheme](https://github.com/n3oxmind/materia-theme/tree/customschemes)  to change any part of the theme specially the problem that you have with the inverse_fg_color on the button.
user this option to change the button text
```sh
....
  --btn-fg            Change theme buttons text color
  --btn2-fg           Change theme action buttons text color(ex: rename button,..)
....
```

**Comment by AndreasBackx** [comment]
@n3oxmind Are you sure that will change this? This is not a button.

**Comment by nana-4** [comment]
@AndreasBackx I'm so sorry for the late reply. I was very busy these days...

Indeed, in the warning box (`infobar.warning`) the text isn't legible. But I'm not considering adding `text-shadow` into Materia - since in Material Design elements do not have `text-shadow` basically. So I'd prefer to change the background or foreground color to make it legible.

However, you can add `text-shadow` into your own theme. In the case of the warning box, you need to change

https://github.com/nana-4/materia-theme/blob/d74792e8c17fe3ab278db7ad3e8cfeeb628b76bf/src/_sass/gtk/_common-3.20.scss#L3120

to

```scss
  &.warning {
    background-color: $warning_bg_color;
    text-shadow: $shadow_1;
    -gtk-icon-shadow: $shadow_1;
  }
```

I'm also considering using Sass function to automatically change the foreground color according to the brightness of the background color. Although it's not easy because we have to consider the compatibility with oomox... :P

@n3oxmind Thanks for your efforts!

**Comment by AndreasBackx** [comment]
Thanks for the reply @nana-4. Adding 2 attributes everywhere will take quite a while because I'll have to figure out where I need to add it.

>  in Material Design elements do not have text-shadow basically. So I'd prefer to change the background or foreground color to make it legible.

That would also be great. I'm unsure whether GTK allows opacity in text, but then we could just set it to use the black with an opacity of 87% perhaps according to Material Design specs?

> Although it's not easy because we have to consider the compatibility with oomox... :P

I've tried to use oomox with this theme to create my own. But in my opinion the integration with oomox is a bit too lackluster currently to be useful. I had a hard time changing the settings to what I wanted them to be. I felt like materia-theme was adapting to oomox when imo it should be the other way around. Omoox should let you change the colors defined in the SASS files instead of having another less configurable layer on top of it.

I'll only be able to try the changes you mentioned next month as I'm currently studying for my finals till the end of June.

**Comment by nana-4** [comment]
> I'm unsure whether GTK allows opacity in text, but then we could just set it to use the black with an opacity of 87% perhaps according to Material Design specs?

Unfortunately GTK2 doesn't allow opacity in text, but in GTK3 and GNOME Shell, [it's already done](https://github.com/nana-4/materia-theme/blob/master/src/_sass/_colors.scss#L14-L41)!

> I've tried to use oomox with this theme to create my own. But in my opinion the integration with oomox is a bit too lackluster currently to be useful. I had a hard time changing the settings to what I wanted them to be. I felt like materia-theme was adapting to oomox when imo it should be the other way around. Omoox should let you change the colors defined in the SASS files instead of having another less configurable layer on top of it.

I can understand the complaint about it. Adaptability with Oomox is not yet perfect. But it is being improved step by step. I'm currently pretty busy so I cannot spare time on it for now, but [any contribution to that](https://github.com/nana-4/materia-theme/issues/218) is very welcomed.

So, can we close this now?

**Comment by AndreasBackx** [comment]
> So, can we close this now?

Feel free to, but I feel like this issue should perhaps be used to track the feature you described (or make a new issue):

> I'm also considering using Sass function to automatically change the foreground color according to the brightness of the background color. Although it's not easy because we have to consider the compatibility with oomox... :P

**Comment by nana-4** [comment]
Okay, that feature is already mentioned in #218 (not by me though) so I'll use the issue for tracking. :)
