### ISSUE TITLE
Bottom border for the toolbar in Google Chrome GTK theme

### ISSUE THREAD

**Issue by TechnoSparks** [nana-4/materia-theme#249]
_This is not a bug report, but rather an enhancement request_

Title may be confusing, as I was finding a hard time to describe this issue in a few words to write the title. But I will explain this further. To provide context, when I say "theme", or name of a theme, I am refering to the theme within Google Chrome (unless I specifically say otherwise)

Google Chrome, I don't recall from which version, introduced a better integration with the GTK environment by allowing a more integrated look with the host's DE and theme. [Here](https://www.omgubuntu.co.uk/2017/10/chrome-gtk-window-controls) is an article that describes the feature when it is still in developmental phase.

The changes work well really, for all themes that I have tried as far as I am concerned, including Flat Plat back then. I always wanted to use the default GTK theme as the colour scheme is still acceptable for me (it is slightly grey), but there is something bothering me: __The toolbar is missing a bottom border if I use the stock Chrome's GTK theme while the DE is using Materia.__ I have been using the Materia crx theme for so long now in patience, but I still crave to use the stock GTK theme from time to time. Especially for the look of window buttons, plus the ease of closing the chrome window by just sliding the cursor to the top right of the screen. Figured out I should drop a request, because for other themes, there are no problems at all.

To use GTK theme, open Settings, under category "Appearance" of the section "Theme", click on "Use GTK+"

Below are screenshots showing the missing bottom border for Chrome GTK theme. The bottom border is in fact visible for Classic and Materia.

__Chrome GTK__
![image](https://user-images.githubusercontent.com/6072210/39590420-69007014-4f33-11e8-8bc7-ceb45eddad30.png)
(Notice the slight grey compared to Materia below. I am fine with that, and it is not the point of this issue :v:)

__Materia__
![image](https://user-images.githubusercontent.com/6072210/39590318-1f817438-4f33-11e8-8a24-8795738c8ccc.png)

__Chrome Classic__
![image](https://user-images.githubusercontent.com/6072210/39590356-4086cad4-4f33-11e8-8857-b61194f8404a.png)

__Chrome GTK Maximised__
![screenshot from 2018-05-04 00-38-44](https://user-images.githubusercontent.com/6072210/39590473-938c73b4-4f33-11e8-8a59-fe97b1e50972.png)

__Chrome GTK (Adwaita on DE)__
![screenshot from 2018-05-04 00-50-17](https://user-images.githubusercontent.com/6072210/39591068-318adfb4-4f35-11e8-8a49-697ff1a534ed.png)

I have also included the look of it if I used Adwaita on my Gnome desktop, and the bottom border is present. Since Materia is based on Adwaita, I hope maybe something could aid in implementing the border in Materia

As always, feature requests are just "requests" and it is up to the developer to add it or not! 😄

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Materia version
_v20180321 (github)_
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)
_3.22.30_
- Distribution (and version)
_Manjaro Gnome (rolling release, 17.1.9)_
- Desktop environment (and version)
_Gnome 3.28.1_
- Related application (and version)
_Google Chrome (any supported)_
- Steps to reproduce
_As stated above_
- Screenshot(s)
_As shown above_

**Comment by nana-4** [comment]
Hey, thanks for the detailed report ;) I've addressed this issue finally.

However, Chrome's GTK+ theme integration is still not very good, so I'd still recommend using **Chrome theme** and enabling "**Use system title bar and borders**" so far...

**Comment by TechnoSparks** [comment]
One word: You are awesome! 😁

**Comment by mikkorantalainen** [comment]
I'm always using "Use system title bar and borders" even if Chrome did manage to draw the pixels using correct colors because it doesn't seem to pick up the behavior of the window manager. For example, I have my window title bars to open context menu with right button that has options to move the window to another desktop, force "Always on top" and clicking window title bar with middle mouse button will toggle maximize vertically. I often use every one of those options and non-system title bar misses every one of those.
