### ISSUE TITLE
Color emojis black and incomprehensible in Ubuntu 18.04

### ISSUE THREAD

**Issue by nplezka** [nana-4/materia-theme#250]
Hi, I saw this bug in standard and light theme using messaging programs... this isn't happening on dark variant. Can you fix it?
- Materia version: 20180321-1
- Distribution (and version) Ubuntu 18.04
- Desktop environment (and version) GNOME Shell
- Steps to reproduce: notify-send *anyemoji*
![schermata da 2018-05-09 21-45-03](https://user-images.githubusercontent.com/10550382/39836090-8eb6655e-53d2-11e8-96f1-efb5a88b5c70.png)
![schermata da 2018-05-09 21-44-52](https://user-images.githubusercontent.com/10550382/39836091-8ed83a4e-53d2-11e8-8919-770bbba3ca28.png)

**Comment by nana-4** [comment]
Thanks for the report.

It seems this bug happens in _any_ light gnome-shell themes and cannot be fixed by the theme, so I reported it to the upstream.

https://gitlab.gnome.org/GNOME/gnome-shell/issues/323
