### ISSUE TITLE
Reducing titlebar height

### ISSUE THREAD

**Issue by adalvigi** [nana-4/materia-theme#255]
I really love this theme, it is probably one of the best available for those looking for some GTK+ 3.18 compatible theme. You, my sir, are really a gentleman and a scholar for developing it. Alas, as a user of a low resolution monitor, I have to complain about one simple, yet bugging, issue: the titlebar on the Gnome 3 windows really takes too much vertical space, even in the compact version of the theme. I'm not criticizing your design choices, my sir, I'd never dream of it, but in order to have more vertical space available I'd really like a "more compact" option, with a much smaller titlebar and even a smaller Gnome top bar.

Thanks for everything you do for us users, and I'm looking forward to how you'll eventually (I know this may be a spare time project for you and I absolutely don't think we're entitled to telling you what to do) masterfully craft a "more compact" version.

**Comment by nana-4** [comment]
p.s.

> and I absolutely don't think we're entitled to telling you what to do

Suggestions are always welcomed to me. :)

**Comment by adalvigi** [comment]
>Are you using GTK+ 3.18.x? If so, what distro and version are you using?
Ubuntu Gnome 16.04 LTS. I don't want to migrate to newer versions of Gnome and GTK as this is my "stable" system I use for everything and reinstalling it all/migrating files and settings would be a mess. It sucks that most themes work poorly here but I would like to use it until the end of support at least since I have few time... and I think this version is still quite popular as 16.04 was the latest LTS and a lot of people (expecially those interested in customization/ricing) tended to prefer Gnome 3 over Unity. 
>Do you think the top bar of GNOME Shell is still high even if using the compact variant?
I did some tests and it seems the only things that change when I set GTK+ and Shell theme to the compact version is the top bar (window titlebars remain the same). While it was mostly the title-bar on the windows that I felt I would've preferred a bit smaller, themes like [Adapta Eta](https://github.com/adapta-project/adapta-gtk-theme) have a slightly smaller Top Bar than the compact version of Materia and it doesn't look bad (you could check that out as a reference to see what I mean). But since the compact version of Materia was in my opinion already a very tasteful choice you made, I think it wouldn't be right to completely replace it, and it would be better to just make a Materia-dark-very-compact version or something like that.

>What is the actual resolution of your monitor?
1366*768. The eternal resolution, dare I call it! 

If it's not possible for you to properly work on the titlebar size, don't worry, we won't ask you the impossible, sir. The theme is already great enough, and with the option for a smaller top bar it will be even more versatile!

**Comment by nana-4** [comment]
> But since the compact version of Materia was in my opinion already a very tasteful choice you made, I think it wouldn't be right to completely replace it, and it would be better to just make a Materia-dark-very-compact version or something like that.

I'm not planning to add any more variants, since supporting so many variants is very hard... I'm only thinking about making the current compact variant more compact so far.

Anyway, thanks for your nice feedback! Your opinions will be a good reference for the sizing of compact variant. :)

Closing.
