### ISSUE TITLE
GTK4 support?

### ISSUE THREAD

**Issue by kirbyfan64** [nana-4/materia-theme#256]
I couldn't find any mention of this, so I was wondering if there were any plans to support it.

**Comment by nana-4** [comment]
Of course, I will!

However, GTK4 is still under heavy development and there are still many API changes. So it's too early to start developing the theme. :)

But I will mention the GTK4 support at `TODO.md`.

**Comment by actionless** [comment]
as a side point i would also add what currently on arch both `gtk4` AUR packages are indeed building however none of demo apps is starting fine, at such point it's quite hard doing even any early adopting/research (i was attempting to do it for oomox gtk theme recently)

**Comment by kirbyfan64** [comment]
👍

**Comment by kirbyfan64** [comment]
FWIW, the [GTK+ 3.94 announcement post](https://blog.gtk.org/2018/06/26/gtk-3-94/) mentions:

> With GTK+ 3.94.0, it should be possible to start porting applications.

**Comment by codic12** [comment]
Hi, Gtk 4 is stable now, and gnome 40 with gtk4 is coming out soon, so any plans to add gtk 4 support? Just curious, thanks!

**Comment by actionless** [comment]
@codic12  did they already released documentation for or reference theme implementation CSS example?

**Comment by codic12** [comment]
The Adwaita theme is supported in GTK4. GTK4 themeing docs: https://developer.gnome.org/gtk4/stable/theming.html

**Comment by actionless** [comment]
im able to google gtk4 docs myself ;)

could you point to exact things i've asked about

**Comment by nana-4** [comment]
GTK 4 support has just landed :)

**Comment by actionless** [comment]
@nana-4 what did you used as a reference when you were working on it?

**Comment by nana-4** [comment]
@actionless Basically I only referred to [the upstream Adwaita code](https://gitlab.gnome.org/GNOME/gtk/-/tree/gtk-4.0/gtk/theme/Adwaita) and [its commit log and messages](https://gitlab.gnome.org/GNOME/gtk/-/commits/gtk-4.0/gtk/theme/Adwaita).

However, the theme changes in GTK 4 are too many, so if you are trying to port your theme to GTK 4, I'd recommend ignoring the commit log and rewriting the upstream GTK 4 Adwaita to your style.

**Comment by actionless** [comment]
i'm indeed planning to write a new oomox-inspired theme (now it's not a secret anymore :D)

**Comment by codic12** [comment]
That's awesome, thank you for your work!
> could you point (using direct links) to exact things i've asked about
I thought that was what you were asking about, sorry.
