### ISSUE TITLE
The texts in "Location" part was too dark.

### ISSUE THREAD

**Issue by chuutatsu** [nana-4/materia-theme#257]
![screenshot at 2018-06-06 20-21-43](https://user-images.githubusercontent.com/24815847/41041125-75f315ba-69c8-11e8-9f10-66e718cac88f.png)
![screenshot at 2018-06-06 20-24-53](https://user-images.githubusercontent.com/24815847/41041126-763a6b86-69c8-11e8-819b-8901fda9f748.png)

As the title says, the texts in "Location" part was too dark when using all variants of Materia theme. I am using Mate Desktop 1.21, GTK+3 3.22.28, and latest Materia version.

Please fix this, thank you!

**Comment by nana-4** [comment]
Thanks for the bug report. I'll fix it sooner. :)
