### ISSUE TITLE
FirefoxColor theme?

### ISSUE THREAD

**Issue by ArchangeGabriel** [nana-4/materia-theme#259]
Mozilla added a new TestPilot extension: https://mozilla.github.io/FirefoxColor/

I believe it must not be very hard to do a Materia theme (as well as dark one) for it, right? :)

**Comment by nana-4** [comment]
Yeah, that is definitely not hard. :)

However, I don't know what it's worth to publish for Materia theme. If you are using _Materia GTK+ theme_ then applied _Materia FirefoxColor theme_, visually almost nothing changes. Who is expected to use it for what? I can't imagine who will use the Materia FirefoxColor theme. :)

**Comment by nana-4** [comment]
Okay, in my understanding, FirefoxColor is to change the default color scheme to a _fancy_ color scheme. Cloning Materia color scheme to FirefoxColor would have no meaning.

So I would like to close this, but thanks for your suggestion. :)
