### ISSUE TITLE
Unexpected 1px transparency in terminator

### ISSUE THREAD

**Issue by luispabon** [nana-4/materia-theme#260]
I'm just trying out materia and the only issue I've found so far is a 1px completely transparent boundary between split terminals in Terminator (as per screenshot belows). This is not showing on other themes like dark numix or arc.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Materia version: 20180519-3-0ubuntu1~bionic1
- GTK+ 3 version : 3.22.30-1ubuntu1 
- Distribution: Ubuntu bionic
- Desktop environment: Unity 7
- Related application: Terminator
- Steps to reproduce: configure terminator as per screenshot below, and open a couple of split terminatls
- Screenshot(s)
![image](https://user-images.githubusercontent.com/6388823/41316622-bf552dee-6e8a-11e8-80bd-6b590043898c.png)

Terminator config:

![image](https://user-images.githubusercontent.com/6388823/41316976-be831cae-6e8b-11e8-9243-086c5c7c4103.png)

**Comment by luispabon** [comment]
It might be more than 1px actually as I'm on a 4k screen. Another example, perhaps more visible:

![image](https://user-images.githubusercontent.com/6388823/41317124-2f61290c-6e8c-11e8-9d07-b9933a0f2da0.png)

**Comment by nana-4** [comment]
Thanks  for the report! I'll fix this soon.
