### ISSUE TITLE
3.28.2 compatibile?

### ISSUE THREAD

**Issue by xzj8b3** [nana-4/materia-theme#262]
I'm testing on Fedora 28 cute, should only accentuate transparencies and use a little more modern buttons to achieve perfection!!!!

**Comment by nana-4** [comment]
Yes, Materia is compatible with GNOME 3.28.x.

(When opening an issue, _please_ clarify your problems or questions.)

Closing...

**Comment by xzj8b3** [comment]
Just wondered if it was compatible with Gnome-shell 3.28.2 and if it were possible to make the task bar slightly transparent and maybe use a little more modern buttons for Windows etc!!!!
