### ISSUE TITLE
Materia color scheme for Vivaldi

### ISSUE THREAD

**Issue by Reiddragon** [nana-4/materia-theme#267]
Title says it all. I've been looking for a Materia color scheme for Vivaldi so it could fit with the rest of my desktop, but I couldn't find anything (official or community).
Thanks for your time.
Cheers

**Comment by ckotte** [comment]
Looks like you can create a custom css: https://linuxcool.net/en/instructions/how-to-change-the-system-frame-in-vivaldi-to-match-the-gtk-linux-theme/
