### ISSUE TITLE
XFCE improvements needed

### ISSUE THREAD

**Issue by sergioad** [nana-4/materia-theme#269]
Hi friend could you theme Thunar's sidebar and remove the in desktop icon text backgrounds?

- Materia version = 20180519-3-0ubuntu1~xenial1
- GTK+ 3 version = 3.18
- Distribution = Ubuntu 16.04 Xenial
- Desktop environment = XFCE 4.12.3
- Related application = Thunar 1.6.11 and xfce4-panel 4.12.3
- Steps to reproduce: Log into your desktop and open Thunar
- Screenshot(s)

![captura de pantalla_2018-07-28_08-34-29](https://user-images.githubusercontent.com/5375145/43357204-7d35eb10-9243-11e8-8cca-ad4d62d5bb5f.png)
![captura de pantalla_2018-07-28_08-50-56](https://user-images.githubusercontent.com/5375145/43357205-7d56d1fe-9243-11e8-82f8-9c374329eaf1.png)
How the theme looks now

PS: the not matching titlebar and pathbar colors are not a theming issue, when I show the menus those are colored like the titlebar so that means the path bar is a separated item

**Comment by sergioad** [comment]
To make the text backgrounds disapear add to the gtkrc file

style "xfdesktop-icon-view" {
XfdesktopIconView::label-alpha = 0
XfdesktopIconView::selected-label-alpha = 170

base[NORMAL] = "#cccccc"
base[SELECTED] = "#4285F4"
base[ACTIVE] = "#cccccc"

fg[NORMAL] = "#ffffff"
fg[SELECTED] = "#ffffff"
fg[ACTIVE] = "#000000"
}
widget_class "*XfdesktopIconView*" style "xfdesktop-icon-view"

And by the way I made a simple TDesktop theme for Meteria light, if you want to adopt it here it is


[Materia light TDesktop.tar.gz](https://github.com/nana-4/materia-theme/files/2238277/Materia.light.TDesktop.tar.gz)

It is not fully polished so I recommend you to check it and tweak it to fit your design guidelines for a Materia theme

**Comment by nana-4** [comment]
So sorry for the delay in my response.

Thank you for your report and the tips.

Currently, Materia is not officially supporting Xfce. The issue tracker is #60. So could use it instead of opening a new issue for now?

> To make the text backgrounds disapear add to the gtkrc file

> And by the way I made a simple TDesktop theme for Meteria light, if you want to adopt it here it is

> It is not fully polished so I recommend you to check it and tweak it to fit your design guidelines for a Materia theme

Thanks! I'll check it when I have time for it. :)
