### ISSUE TITLE
Low contrast in Thunderbird between unread and read emails.

### ISSUE THREAD

**Issue by ArchangeGabriel** [nana-4/materia-theme#271]
Thunderbird was updated to version 60 today, and it now uses the GTK theme properly as Firefox does. However, the contrast between unread and read emails is way too low.

- Materia version: 20180519
- GTK+ 3 version: 3.22.30
- Distribution (and version): Arch Linux
- Desktop environment (and version): KDE Plasma 5.13
- Related application (and version): Thunderbird 60
- Steps to reproduce: choose Materia-dark as GTK3 theme.
- Screenshot(s):
![capture du 2018-08-08 20-04-11](https://user-images.githubusercontent.com/490531/43868226-2b6a6528-9b5c-11e8-91b3-578e95f5b41a.png)

I’m not sure if this is a Materia issue, GTK issue or Thunderbird issue though…

**Comment by nana-4** [comment]
I'm so sorry for the delay in my response...

In my environment, Thunderbird 60.2.1 looks like the screenshots below. Indeed on the **dark themes**, the contrast between unread and read emails looks too low. However, I don't think this is a Materia(-dark) specific issue. Also, as far as I know there is no way to change the read/unread style on Thunderbird with GTK themes.

I’d say this is rather a Thunderbird design issue.

Please let me know if my point is something wrong.

Materia:
![image](https://user-images.githubusercontent.com/9556384/49683149-512a4b00-fb03-11e8-87be-6e8b339beed4.png)

Materia-dark:
![image](https://user-images.githubusercontent.com/9556384/49683151-5ab3b300-fb03-11e8-90e8-fd051890586d.png)

Adwaita-dark:
![image](https://user-images.githubusercontent.com/9556384/49683152-6010fd80-fb03-11e8-922d-d590fac21fe1.png)

**Comment by actionless** [comment]
@ArchangeGabriel try using font where the difference between regular and bold characters will be more noticeable, it's not something to be fixed in gtk theme
