### ISSUE TITLE
GDM-Theme wiki page need to be updated

### ISSUE THREAD

**Issue by xanscale** [nana-4/materia-theme#272]
using ubuntu 18.04 following [GDM-Theme](https://github.com/nana-4/materia-theme/wiki/GDM-Theme) i receive this error

```
sudo glib-compile-resources --target=/usr/share/gnome-shell/gnome-shell-theme.gresource gnome-shell-theme.gresource.xml
Failed to open file “gnome-shell-theme.gresource.xml”: No such file or directory
```

**Comment by nana-4** [comment]
I'm sorry for the late reply.

Please tell me:

- Did you install `libglib2.0-dev` and `libxml2-utils` (as written in the wiki)?
- Do Materia theme directories exist in `/usr/share/themes`?

If you installed the themes in `~/.themes`, you'll need to change the command from
```sh
cd /usr/share/themes/${GTK_THEME}/gnome-shell
```
to
```sh
cd ~/.themes/${GTK_THEME}/gnome-shell
```

**Comment by eyal0803** [comment]
I'm also getting this error. I'm running Arch Linux and `glib2` (as the instructions state) is installed. I'm trying to do this for the [Adapta](https://github.com/adapta-project/adapta-gtk-theme) theme (Adapta-Nokto-Eta).

Seems like the `gnome-shell-theme.gresource.xml` should be there when it isn't.

**Comment by nana-4** [comment]
Since there is no reply from OP for a while, I'd like to close this issue.
