### ISSUE TITLE
Add the compact themes to the flathub

### ISSUE THREAD

**Issue by MischievousTomato** [nana-4/materia-theme#274]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Materia version : 20180519-1 (arch)
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`) 3.22.30
- Distribution (and version)  : Arch - everything updated
- Desktop environment (and version) :  Gnome 3.28.2
- Related application (and version)  : Everything related to GTK3 flatpaks

- Steps to reproduce 

- Install a GTK3 flatpak program, for example, Fragments.
- Select either of the -compact themes in the Tweak Tool
- See how Fragments has Adwaita instead of the -compact theme.
- Cry.
- Screenshot(s)

Can't upload ATM, sorry.

Thank you.

**Comment by nana-4** [comment]
Sorry for the late reply.

Since our PRs have been accepted in Flathub, compact variants are also now available. :)
