### ISSUE TITLE
Chromium/Chrome 69 support

### ISSUE THREAD

**Issue by varlesh** [nana-4/materia-theme#275]
On new Chromium/Chrome UI used light background on searchbar.
It's possible fixed for Materia Dark?
**Chromium 68**:
![image](https://user-images.githubusercontent.com/8083855/45094676-fc0a2200-b12c-11e8-8a02-1befdcfc3e58.png)

**Chromium 69**:
![image](https://user-images.githubusercontent.com/8083855/45094539-aa619780-b12c-11e8-8769-1ca7091b5e2d.png)

- Materia GTK 20180519-1 (Manjaro package)
- GTK 3.22.30-1
- Chromium 69

**Comment by actionless** [comment]
is there any theme in which that addressbar is colored differently? i am feeling like its color is hardcoded

**Comment by varlesh** [comment]
i don't know... but this possible disabled now on `chrome://flags/#top-chrome-md`  and set `normal`

**Comment by Coeur-Noir** [comment]
Mmm… just an opinion : I think it's ok as it is in Chromium 69.

**Comment by nana-4** [comment]
Looks like @actionless is right. The background color of Omnibox is hard-coded with `#F1F3F4` in all themes (including Adwaita, Adwaita-dark).

Unfortunately, we cannot do anything unless it's addressed by the upstream.
