### ISSUE TITLE
Materia-theme in Budgie with pixelsaver applet

### ISSUE THREAD

**Issue by Coeur-Noir** [nana-4/materia-theme#276]
Hello,

Materia-theme applies a background color to pixelsaver applet in Budgie.
That panel applet should have no background, to let only show panel background.

That « problem » occurs with many themes, it has been fixed in Adapta and Pocillo
https://discourse.ubuntubudgie.org/t/adapta-and-pixel-saver-applet/661
I think it's here : https://github.com/adapta-project/adapta-gtk-theme/commit/649e2dd1b2cdf978d5e7aff00433a4649fc61c2a

Screenshots give the global idea + a potential panels overlap issue ( I did not dig further there )

- Materia version = 20180321-1
- GTK+ 3 version = 3.22.30-1ubuntu1
- Distribution = UbuntuBudgie 18.04
- Desktop environment = budgie 10.4+git20171031.10.g9f71bb8-1.2ubuntu1
- Related application =  budgie-pixel-saver-applet 4.0+git20171102.30c1f94-0ubuntu1~bionic
- Steps to reproduce = just activate pixelsaver in a panel, and apply materia-theme.

![capture du 2018-09-12 20-10-37](https://user-images.githubusercontent.com/1895947/45444625-3c871400-b6c8-11e8-9d91-a1cb10f42445.png)

![capture du 2018-09-12 20-11-03](https://user-images.githubusercontent.com/1895947/45444642-4872d600-b6c8-11e8-95fe-0406ca11b7a5.png)
There should not be solid grey background.

But anyway and over all, thanks for that beautiful theme !

**Comment by Coeur-Noir** [comment]
For avoiding overlaps issues with panels, height of top panel needs at least 53 px.

**Comment by nana-4** [comment]
Thanks for the bug report. I confirmed this problem.

I'll fix it soon. :)
