### ISSUE TITLE
Weird line in Budgie raven

### ISSUE THREAD

**Issue by FFY00** [nana-4/materia-theme#278]
- Materia version: 20180922
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`): 3.24.1
- Distribution (and version): Arch Linux
- Desktop environment (and version): Budgie v10.4-123-gf2dbc215
- Steps to reproduce: Open "Raven" in budgie
- Screenshot(s)
![materia-issue-budgie](https://user-images.githubusercontent.com/11718923/45930446-635f0900-bf58-11e8-8d3d-cddfc1313490.png)

**Comment by nana-4** [comment]
Hi, I guess you're enabling the "Built-in theme" option. Please try disabling it.

![image](https://user-images.githubusercontent.com/9556384/46001345-04c79580-c0e6-11e8-9eef-02d743bb1544.png)

**Comment by rolurq** [comment]
@nana-4 I have the settings as you specify but it stills shows the weird line as @FFY00 says

**Comment by rolurq** [comment]
Is there a tweak I can add to the theme that shows raven with the default theme and not having that weird line?

**Comment by nana-4** [comment]
@rolurq Yes.

If you have knowledge of SCSS, edit [this line](https://github.com/nana-4/materia-theme/blob/master/src/_sass/gtk/apps/_budgie.scss#L381) from `32px` to `0` then run `./parse-sass.sh`.

If you want to change the CSS directly, open the CSS and edit [these four](https://github.com/nana-4/materia-theme/blob/master/src/gtk/3.22/gtk.css#L5915-L5929) `32px` to `0`.

**Comment by nana-4** [comment]
This is not the theme bug, and I won't (can't) add a workaround for the "Built-in theme".

So I would like to close this issue.

**Comment by rolurq** [comment]
@nana-4 Thanks! I do have knowledge of SCSS, nevertheless your instructions are clear so I guess anyone could follow them.

**Comment by FFY00** [comment]
Just curious, making such changes will break anything? Or change the intended behavior in other cases?

**Comment by rolurq** [comment]
@FFY00 I made the changes to the theme, so far everything's ok. I guess @nana-4 will have more insights about this.

**Comment by nana-4** [comment]
@FFY00 That `margin` is an area for Materia to draw Raven's `box-shadow`. That change only loses the shadow from Raven if you turn off the "Built-in theme" option.
