### ISSUE TITLE
[info] A matching (dark) VSCode theme is available

### ISSUE THREAD

**Issue by m-thorsen** [nana-4/materia-theme#279]
Just thought I'd mention it here.

I've published a VSCode theme based on [Material Theme](https://github.com/equinusocio/material-theme), with tweaks to match various Linux themes, including Materia Dark.

Note that this theme is a work in progress, but it should be fairly complete, and the token colors have been updated to match https://material.io/design/color/the-color-system.html.

Suggestions are welcome!  
If this is in any way inappropriate, feel free to close this and/or let me know.

Available here: https://marketplace.visualstudio.com/items?itemName=m-thorsen.vscode-material-mt  
Source: https://github.com/m-thorsen/vscode-material-mt

Screenshot: 
![screenshot from 2018-09-24 22-40-21](https://user-images.githubusercontent.com/14907694/45978483-c92cbd00-c04c-11e8-8893-2ec1f95dc7b4.png)

The background is *slightly* darker than Materia's terminal bg in the screenshot, but this has been reverted and it's once again #303030

**Comment by nana-4** [comment]
Thanks for the info! It looks very nice :+1: :100: 

I'll add your VSCode theme's links to the README :wink:

**Comment by m-thorsen** [comment]
FYI:  
I've added a fork with only the Materia variants including a rework of the token color palette.  
Over time I might revert the previous theme back to being a "basic" variant of the original Material Theme, as originally intended. 

https://github.com/m-thorsen/vscode-materia  
https://marketplace.visualstudio.com/items?itemName=m-thorsen.vscode-materia
