### ISSUE TITLE
[enhancement] Сompatibility with Papirus and KDE Theme

### ISSUE THREAD

**Issue by varlesh** [nana-4/materia-theme#282]
@nana-4 Hi. You know, we port your great theme for KDE and integrate Papirus icon theme.
On near future we want doing Materia and Papirus more integrated and for our projects, but we have trouble with some colors:
- panel symbolic icons (on Gnome, Cinnamon and etc) and not symbolic icons (for Mate, XFCE and etc)
 Materia Dark used `#bdbdbd` color for that, but this  color darker and not good looking with Plasma Theme, because highlight color `#4285f4` not good readable with layering `#bdbdbd`
How about more lighter color, for example `#dfdfdf`:
![default](https://user-images.githubusercontent.com/8083855/46254200-76179780-c49c-11e8-8a20-40052778c2ee.png)

**Comment by nana-4** [comment]
Hi @varlesh, thanks for filing this! I'm happy to see the port to KDE and the integration into your great icon theme. :)

> Materia Dark used `#bdbdbd` color for that

No, actually Materia (dark) is using `rgba(255, 255, 255, 0.7)` for flat buttons, inactive tabs, hint text, etc. It is `#FFFFFF` with transparency, _not_ an opaque color:

![image](https://user-images.githubusercontent.com/9556384/46345058-21337700-c67e-11e8-9e72-b2ba5a20e72f.png)

**Using text opacity** is based on the [Material Guidelines](https://material.io/design/color/text-legibility.html#text-backgrounds). Also that guideline says "*Avoid using opaque gray text that isn’t legible on colored surfaces*".

BTW, the value of `rgba(255, 255, 255, 0.7)` is based on the (previous) [Material Guidelines](https://material.io/archive/guidelines/style/color.html#color-usability), so I don't really want to change the color value.

Therefore, I think there are two options:

- Change the opaque `#bdbdbd` to `rgba(255, 255, 255, 0.7)`, if possible.
- If translucent colors are not available on the Plasma theme, use `#C6DAFC` when its background color is `#4285f4`.

**Comment by SmartFinn** [comment]
@nana-4 is it possible to make the color for panel a bit brighter, `rgba(255, 255, 255, 0.8)` for example? The other gtk themes use bright colors for the panel:

![image](https://user-images.githubusercontent.com/819186/46348559-08b06600-c658-11e8-882c-652130f20d93.png)

We choosen `#dfdfdf` as the color for panel icons, it looks fine with other themes, but not with Materia:

![screenshot_20181002-15-16-43](https://user-images.githubusercontent.com/819186/46348171-c0dd0f00-c656-11e8-9936-d76ca08d9efb.png)
![screenshot_20181002-15-17-08](https://user-images.githubusercontent.com/819186/46348172-c175a580-c656-11e8-8c6d-79bf9c840389.png)

**Comment by nana-4** [comment]
Hi @SmartFinn  

To be honest, I'm reluctant to do it. Because: 

- Regardless of any other gtk/icon theme, I'd like to follow the **Material Guidelines first**. The guidelines recommended 70% opacity for light secondary text, and Google's `material-components-web` also has [adopted it](https://github.com/material-components/material-components-web/blob/master/packages/mdc-theme/_variables.scss#L61).
- To me `rgba(255, 255, 255, 0.7)` works **very well** as a secondary text color. Materia actually used `rgba(255, 255, 255, 0.8)` before, but it was sometimes a bit too bright.

However, in my honest opinion, I think Papirus' panel icon color and Materia's panel text/icon color are almost matched. It doesn't bother me :)

**Comment by nana-4** [comment]
BTW, materia-kde seems to use `#4285f4` as the background color when hovering items, but I highly recommend to use `rgba(255, 255, 255, 0.08)` (or similar darker gray) instead, as Materia gtk/gnome-shell theme does:

![image](https://user-images.githubusercontent.com/9556384/46354126-d5da9200-c698-11e8-8fec-e6e7bb7746c6.png)

**Comment by varlesh** [comment]
@nana-4 Thx for clarification, but KDE impossible use RGBA for colorschemes. Available only RGB. Also we not use opacity on Papirus, because it's hard for development.

**Comment by varlesh** [comment]
Some widgets used as text on KDE and we can't added RGBA for this - it's impossible.
For example (blue icons/text from colorscheme):
![image](https://user-images.githubusercontent.com/8083855/46361236-24c6fe00-c67e-11e8-8d32-ef9999569422.png)

**Comment by actionless** [comment]
@nana-4 , just small sidenote, if you'll be changing any of default colors please also update them here:
https://github.com/nana-4/materia-theme/blob/master/change_color.sh#L181-L220 (mb that note should be also added to HACKING.md?)

**Comment by varlesh** [comment]
> Avoid using #4285f4 for background color as much as possible

You not understand. I can modify all SVG-elements (icons , buttons opacity). But problem with text. Text not support Alpha Channel. I can set text more lighter, but it will be out of style

**Comment by nana-4** [comment]
> I can modify all SVG-elements (icons , buttons opacity). But problem with text. Text not support Alpha Channel.

I already understand it. And the actual problem of this report should have been this:

> ... and not good looking with Plasma Theme, because highlight color `#4285f4` not good readable with layering `#bdbdbd`

So I suggested changing the background color (``#4285f4``) instead of the text color for Plasma Theme. The combo of `#bdbdbd` fg-color and dark gray bg-colors looks much better, isn't it?

![image](https://user-images.githubusercontent.com/9556384/46457569-c456ce80-c7ed-11e8-9a97-eb7f38448450.png)

Am I still misunderstanding something?

**Comment by nana-4** [comment]
P.S. I don't mind even if you set the text brighter in your Plasma Theme _as a workaround_.
But I won't do that in the GNOME/GTK+ themes because they support Alpha Channel for text and symbolic icons. 🙂

**Comment by varlesh** [comment]
Ok i'm understand. Sorry for disturb you.
