### ISSUE TITLE
Firefox: Text in pop-up menu has no vertical padding

### ISSUE THREAD

**Issue by PJSingh5000** [nana-4/materia-theme#284]
There is no padding above and below text in the Firefox right-click (pop-up) menu.
This is not the case for other applications such as Chrome, gedit, etc.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Materia version
90efd4d 

- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)
3.22.30

- Distribution (and version)
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

- Desktop environment (and version)
GNOME Shell 3.28.3

- Related application (and version)
Firefox 62

- Steps to reproduce
1. Right-click on the Firefox main window area.
2. Compare this to right-clicking in other applications such as gedit, terminal, or Chrome.

- Screenshot(s)
![firefox popup menu 2018-09-29-02](https://user-images.githubusercontent.com/19394936/46321605-4490f000-c5b2-11e8-9906-a0ea96c33ee3.png)

**Comment by nana-4** [comment]
Thanks for the report.

But all sizing of Firefox is hard-coded. (Chrome is the same as well.) With GTK+ themes, we cannot add padding to the Firefox menus.
