### ISSUE TITLE
Gtk Switchs are streched horozintally

### ISSUE THREAD

**Issue by PJSingh5000** [nana-4/materia-theme#285]
In some applications, the GtkSwitch widget is stretched horizontally, so the circular button looks more like an oval. (See screenshots).

I've encountered this in two separate applications:

1. Clipboard Indicator Gnome Shell Extension settings dialog
    https://extensions.gnome.org/extension/779/clipboard-indicator/
2. Printers Gnome Shell Extension settings dialog
    https://extensions.gnome.org/extension/1218/printers/

The GtkSwitch widget may be stretching to fill the available horizontal space. A GtkSwitch should never stretch; it should always stay the same size.

Although this also happens in other themes as well, I wonder if this can be easily remedied in materi-theme?...

Would it be possible to specify left and right padding for this specific widget in the materia-theme, so the padding stretches to fill available space, instead of the widget itself?

If this is not possible, please go ahead and close this issue report.
(I will also report directly to the maintainers of the above applications).

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Materia version
90efd4d

- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)
- Distribution (and version)
Distributor ID: Ubuntu
Description: Ubuntu 18.04.1 LTS
Release: 18.04
Codename: bionic

- Desktop environment (and version)
GNOME Shell 3.28.3

- Related application (and version)
1. Clipboard Indicator Gnome Shell Extension settings dialog
    https://extensions.gnome.org/extension/779/clipboard-indicator/
2. Printers Gnome Shell Extension settings dialog
    https://extensions.gnome.org/extension/1218/printers/

- Steps to reproduce
1. Install the Clipboard Indicator extension or the Printers extension in Gnome Shell.
2. Open the settings dialog for either application.
3. Notice the Gtk Switches are stretched.

- Screenshot(s)

![screenshot from 2018-10-01 19-52-14](https://user-images.githubusercontent.com/19394936/46322249-d817f000-c5b5-11e8-878a-55d59f29c252.png)

![screenshot from 2018-10-01 19-51-54](https://user-images.githubusercontent.com/19394936/46322260-e2d28500-c5b5-11e8-8365-5b60badc8257.png)

**Comment by nana-4** [comment]
Thanks for the bug report. This seems to occur only when the `GtkSwitch` is in the `GtkGrid`.

Indeed it looks pretty bad, but it seems not easy to fix the problem by the theme.

> Would it be possible to specify left and right padding for this specific widget in the materia-theme, so the padding stretches to fill available space, instead of the widget itself?

That is possible with `grid > switch { margin-left: 105px; }` (you can try it by pasting the code to the GTK+ Inspector), but it will unnecessarily affect other apps (e.g. [gnome-notes' performance window](https://user-images.githubusercontent.com/9556384/46467643-3ee11780-c809-11e8-9c99-7662bf487a42.png)).

This problem happens even in the upstream Adwaita, so I'd like to close this as an upstream issue.

**Comment by PJSingh5000** [comment]
Here is the upstream bug report:

https://gitlab.gnome.org/GNOME/gtk/issues/1387

**Comment by PJSingh5000** [comment]
FYI...

The developer of the Printers extension has fixed this issue and is currently awaiting approval for the extension to be published. See: https://github.com/linux-man/gnome-shell-extension-printers/issues/9#issuecomment-427508951

No response for the Clipboard Indicator extension, but I have posted a fix here, in case anyone wants to fix this on their own system: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/141#issuecomment-427615665

**Comment by nana-4** [comment]
@PJSingh5000 Thanks for your reports. :)
