### ISSUE TITLE
close button missing in the dialog window

### ISSUE THREAD

**Issue by florentbr** [nana-4/materia-theme#287]
Version : 3.20

The close button in the title bar is missing in a dialog window.

Preference dialog from GEdit:
![capture du 2018-10-03 14-09-47](https://user-images.githubusercontent.com/918557/46409574-630ffc00-c716-11e8-9e8e-aa53dbcd2dba.png)

The issue lies in [metacity-theme-2.xml#L532](https://github.com/nana-4/materia-theme/blob/3.20/metacity-1/metacity-theme-2.xml#L532). The style is explicitly disabling the buttons with `geometry="nobuttons"`.

Note that the close button is present with themes like Adapta, Arc or Vertex.

**Comment by nana-4** [comment]
What desktop environment and version are you using?

I couldn't reproduce it on MATE 1.20.3 or GNOME Shell 3.28.3.

**Comment by pintsel** [comment]
Hello!
I reported this also back in 2018.
Just found out, that the issue is still present with official Debian packages! 
Debian 10, Mate 1.20.4, Package materia-gtk-theme 20190201-1 (also Debian 11 materia-gtk-theme 20200320-0.1)
To fix this, change geometry="nobuttons" to geometry="modal".
