### ISSUE TITLE
Wrong color in the path bar of nautilus

### ISSUE THREAD

**Issue by OliverLew** [nana-4/materia-theme#288]
This happens after the latest update of nautilus, so I am not sure if this is upstream issue or they are changing it forever.
And this only appears when you resize the window large enough so that the pathbar is aligned centrally and has a border.
I am using archlinux, nautilus version is 3.30.1-1, theme version is 20180928-1.

![screenshot from 2018-10-04 22-19-01](https://user-images.githubusercontent.com/12032219/46480333-97251300-c823-11e8-9864-1a4846613f98.png)

![screenshot from 2018-10-04 22-19-11](https://user-images.githubusercontent.com/12032219/46480334-97251300-c823-11e8-85b0-47d3a5cc452e.png)

**Comment by Scindix** [comment]
I can confirm this issue. I have the same nautilus and theme version. Also on Arch Linux.
Doesn't look like an upstream issue to me as it looks perfectly fine in Adwaita.

**Comment by nana-4** [comment]
Thanks for the report.

I’d say this is an upstream issue. And I've reported this to the upstream:
https://gitlab.gnome.org/GNOME/nautilus/issues/674

**Comment by ArchangeGabriel** [comment]
Upstream said it’s a theme issue. Also the Dark theme is affected too, but the other way around: the middle part has a darker background than its surrounding. BTW, it looks to me as the background color of the left pane.
