### ISSUE TITLE
render-assets.sh script prints a copyright notice

### ISSUE THREAD

**Issue by PJSingh5000** [nana-4/materia-theme#289]
The `render-assets.sh` script prints the following copyright notice to the terminal while running.

> Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:
>
> O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
> ;login: The USENIX Magazine, February 2011:42-47.
>
> This helps funding further development; AND IT WON'T COST YOU A CENT.
> If you pay 10000 EUR you should feel free to use GNU Parallel without citing.
>
> To silence this citation notice: run 'parallel --citation'.

Would it be appropriate to use the `--citation` flag inside this script, as suggested in the notice?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:

Materia version
90efd4d

GTK+ 3 version (You can check it with pkg-config --modversion gtk+-3.0)

Distribution (and version)
Distributor ID: Ubuntu
Description: Ubuntu 18.04.1 LTS
Release: 18.04
Codename: bionic

Desktop environment (and version)
GNOME Shell 3.28.3

Related application and version:
parallel  version 20161222-1

**Comment by actionless** [comment]
please file a PR

**Comment by nana-4** [comment]
Maybe a stupid question, but my only concern is whether we can really silence the citation without paying 1000 EUR.

Are `materia-theme`, `oomox`, or their distro packages really not treated as the "publication"?
I'm not 100% sure because I'm not good at English.

**Comment by actionless** [comment]
i think by "publication" it was meant "publication of scientific research in magazine" but idk for sure

**Comment by actionless** [comment]
especially since word "citing" was used


but if you still think what gtk theme could be counted as that kind of publication -- you can "cite" parallel authorship in the end of authors section

**Comment by nana-4** [comment]
> i think by "publication" it was meant "publication of scientific research in magazine"

Aha, your're right. I ran `parallel --citation` and it says:

> If you use programs that use GNU Parallel to process data for an article in a
> **scientific publication**, please cite:

However, adding `--citation` flag in the script was meaningless. It returned

> parallel: Warning: --citation ignores all other options and arguments.

and didn't generate the assets. Instead, `--will-cite` flag is available to silence the citation notice in the script, but [`man parallel`](https://www.gnu.org/software/parallel/man.html#citation) says:

> --citation
>
> Print the citation notice and BibTeX entry for GNU parallel, silence citation notice for all future runs, and exit. It will not run any commands.
>
> If it is impossible for you to run --citation you can instead use --will-cite, which will run commands, but which will only silence the citation notice for this single run.
>
> If you use --will-cite in scripts to be run by others you are making it harder for others to see the citation notice. The development of GNU parallel is indirectly financed through citations, so if your users do not know they should cite then you are making it harder to finance development. However, if you pay 10000 EUR, you have done your part to finance future development and should feel free to use --will-cite in scripts.



 So I won't add `--will-cite` flag in the script. Users will need to run `parallel --citation` by yourself in order to silence the citation notice.

**Comment by actionless** [comment]
mb with the time we'll refactor render-assets as a `make` destination :-) (which implies parallelism by default for processing multiple targets within one destination)
