### ISSUE TITLE
Materia Theme alters the color of the App Grid Icon.

### ISSUE THREAD

**Issue by PJSingh5000** [nana-4/materia-theme#292]
Materia theme alters the color of the App Grid Icon.
This makes it impossible to use any icon, except the default "grid of boxes" icon.

Can the Mateia theme be modified to allow the use of a custom colored view-app-grid-symbolic.svg icon, instead of the monochromatic default icon?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you report a bug or ask a question, please include the following information as required:
- Materia version
585521f

- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)
3.22.30

- Distribution (and version)
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

- Desktop environment (and version)
Gnome-Shell

- Related application (and version)
Glade (sudo apt install glade)
Cubic (https://launchpad.net/cubic)

- Steps to reproduce

1. Copy the text for the SVG file below, and save it as `view-app-grid-symbolic.svg` in your `~/Downloads` folder.
2. Install the Papirus theme. You can use any icon theme, but these instructions assume you have the Papirus theme installed.
```
sudo apt-add-repository ppa:papirus/papirus
sudo apt install papirus-icon-theme
```
3. Use Gnome Tweaks to set Papirus as your desktop theme.
4. Change to the custom App Grid Icon. Execute the following in your terminal.
```
cd /usr/share/icons/Papirus/symbolic/actions/
sudo mv view-app-grid-symbolic.svg view-app-grid-symbolic.svg.original
sudo cp ~/Downloads/view-app-grid-symbolic.svg view-app-grid-symbolic.svg
```
5. Restart Gnome-Shell.
Press <kbd>ALT</kbd>-<kbd>F2</kbd> keys.
Type <kbd>r</kbd> key.
Press <kbd>Enter</kbd> key.

---
If you'd like to test, here is the corresponding SVG file for a custom App Grid icon (save it as `~\Documsnts\view-app-grid-symbolic.svg`)...
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100">
<circle fill="#5294E2" cy="50" cx="50" r="45"/>
<circle fill="none" stroke="#ffffff" stroke-width="8.55" cx="50" cy="50" r="21.825"/>
<g id="friend"><circle fill="#5294E2" cx="19.4" cy="50" r="8.4376"/>
<path stroke="#5294E2" stroke-width="3.2378" d="M67,50H77"/>
<circle fill="#ffffff" cx="19.4" cy="50" r="6.00745"/></g>
<use xlink:href="#friend" transform="rotate(120,50,50)"/>
<use xlink:href="#friend" transform="rotate(240,50,50)"/></svg>
```
---
- Screenshot(s)

This is what the custom icon looks like...

![screenshot from 2018-10-08 21-14-01](https://user-images.githubusercontent.com/19394936/46641332-1b86d700-cb3f-11e8-93b0-bf6b7279091f.png)

Here is what the custom icon currently looks like in the Dock using the Materia theme. The blue circular background is washed out.

![screenshot from 2018-10-08 20-28-03](https://user-images.githubusercontent.com/19394936/46640715-98b04d00-cb3b-11e8-8148-0ccd2b29b04a.png)

Here is what the custom icon should look like in the Dock.

![screenshot from 2018-10-08 21-05-15](https://user-images.githubusercontent.com/19394936/46641128-e2019c00-cb3d-11e8-9413-daa0e6348e0e.png)

**Comment by nana-4** [comment]
> Materia theme alters the color of the App Grid Icon.
> This makes it impossible to use any icon, except the default "grid of boxes" icon.

It should be an expected behavior. The [GNOME's icon doc](https://developer.gnome.org/ThemedIcons/) describes:

> Symbolic icons have a simple form, and can be used much like text. The will be recolored according to the context in which they are used. By convention, symbolic icons are named with a -symbolic suffix.

So `*-symbolic.svg` can't have custom colors (except for [specific `warning`, `error` and `success` classes](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/blob/master/README)). We cannot allow the use of such a custom colored symbolic icon, while supporting the regular symbolic icon.

Instead, by editing your `gnome-shell.css` you can use the custom colored icon.

1. Move your custom colored icon to `${THEME_DIR}/gnome-shell/assets` directory.
2. Edit `${THEME_DIR}/gnome-shell/gnome-shell.css` as follows:

```diff
 .show-apps .show-apps-icon {
-  color: rgba(255, 255, 255, 0.7);
+  color: transparent;
+  background-image: url("assets/view-app-grid-symbolic.svg");
+  background-size: contain;
 }

 .show-apps:hover .show-apps-icon,
 .show-apps:active .show-apps-icon,
 .show-apps:checked .show-apps-icon,
 .show-apps:focus .show-apps-icon {
-  color: white;
+  color: transparent;
   transition-duration: 150ms;
 }
```

3. Reload the theme.

It should look as you expected.

Anyway I have no plan to use a custom App Grid Icon in this theme for now, so I'd like to close this as WONTFIX.
