### ISSUE TITLE
How to make the title-bars of non-CSD windows smaller

### ISSUE THREAD

**Issue by devnullul** [nana-4/materia-theme#294]
Version: master
GTK+-3.0: 3.22.30
Distribution: Fedora
Desktop: GNOME 3.28.3

Hi, 

I would like to start by thanking you for this wonderful material theme you've created. It is one of, if not the, best I've seen.

This isn't so much an issue as it is me asking for help with customizing the theme

I've read your HACKING.md help file in-depth, and have spent hours changing values in _common.scss, but I am unable to figure out how to make the titlebars of windows smaller. Could you perhaps shed some light on this please? I am not concerned with windows using CSD, as I'm sure that gets complicated, though if there is a change that can be made to shrink those as well, I wouldn't complain :) 

I've tried generic solutions to shrink them, using files in ~/.config/gtk-*.0/gtk.css, but it seems they either don't play nice with the theme, or are outdated altogether, seeing as they all say they are for "3.20+". Any help you could offer would be greatly appreciated.

**Comment by nana-4** [comment]
> title-bars of non-CSD windows

That's defined with the `.default-decoration` style class:

https://github.com/nana-4/materia-theme/blob/9d95a6112d27c52ca8d48fd8e80400453368c591/src/_sass/gtk/_common-3.20.scss#L1187-L1201

To reduce the padding, edit `padding: $container_padding;` (e.g. to `padding: 2px;`)
If you want to shrink its button as well, edit the two `min-height: $small_size;` and one `min-width: $small_size;`

Then you'll need to reload GNOME Shell (Mutter) for non-CSD titlebars. Press <kbd>Alt</kbd> + <kbd>F2</kbd> then type `r`.

**Comment by devnullul** [comment]
You're awesome. Thank you so much. I appreciate your time.
