### ISSUE TITLE
Text displacement in nautilus path-bar 

### ISSUE THREAD

**Issue by hexauniverse** [nana-4/materia-theme#297]
- Materia v20180928
- GTK+ 3 version: 3.24.1
- Arch, 4.18.12
- Gnome 3.30

![gif](https://i.imgur.com/4ydvFY0.gif)

Normal behaviour:
![gif](https://i.imgur.com/zbgB21g.gif)

**Comment by nana-4** [comment]
Good point. :-) I'll fix it later. Thanks for the report.
