### ISSUE TITLE
dconf Editor path-bar

### ISSUE THREAD

**Issue by hexauniverse** [nana-4/materia-theme#299]
- Materia v20180928
- GTK+ 3 version: 3.24.1
- Arch, 4.18.12
- Gnome 3.30

Only Materia & Materia-compact:
![gif](https://i.imgur.com/e5ITrcy.gif)

**Comment by PJSingh5000** [comment]
In the Adwaita and Adwaita-dark themes, when path-bar text is made inactive in a header bar, it becomes slightly darker.

In the Materia theme, the path-bar text becomes very dark.
However, buttons or labels in the header bar are OK, so this only affects path-bars.

**Comment by nana-4** [comment]
Thanks for the report. It seems to be an upstream issue and can't be fixed by the theme.

I've reported to the upstream: https://gitlab.gnome.org/GNOME/dconf-editor/issues/7
