### ISSUE TITLE
Please provide a better way to distinguish the active, focused window

### ISSUE THREAD

**Issue by hackel** [nana-4/materia-theme#301]
As much as I love this theme, the one consistent complaint I have is that it's extremely difficult to determine which window actually has focus.  As far as I know, there are currently only two indicators:
- Focused windows have a dark shadow around them (not visible on dark backgrounds)
- Inactive windows have grey title bar text, while focused windows are white

I often have to alt-tab a couple times just to notice which text is brighter and thus which window I can interact with (since I primarily use the keyboard).  Ideally, inactive windows would have a darker (or perhaps just less saturated) background colour on the title bar.  I don't know how this would fit into the material colour palette, but I'm sure there's a way.

Unfortunately there are still apps that do custom CSDs (like Firefox) which don't indicate whether they have focus in any way whatsoever, making this problem even more difficult to solve, but this would at least be a start.

**Comment by nana-4** [comment]
I'm sorry for the delay in responding.

Finally, I've handled this by darkening the inactive window's title bar :smiley: 

Before:

![image](https://user-images.githubusercontent.com/9556384/57562126-3f5b1580-73cb-11e9-8559-72a854f7a976.png)

After:

![image](https://user-images.githubusercontent.com/9556384/57562147-51d54f00-73cb-11e9-8168-80496a068412.png)

I'm not sure if this change is enough for you, but I think the distinction between active and inactive windows has been significantly improved now.

**Comment by hackel** [comment]
Thanks, this will help a lot!  I wasn't seeing any change after installing the latest master.  After quite some time fiddling, I finally realized that the CSS files in master haven't been recompiled since 7 April.  

For anyone wanting to see the latest changes, you need to run:

    sudo apt-get install sassc
    ./parse-sass.sh
    ./install.sh ...

Now it even works with Firefox!
