### ISSUE TITLE
GDM customization Wiki needs to be updated

### ISSUE THREAD

**Issue by ddnexus** [nana-4/materia-theme#303]
Hi @nana-4,

In Ubuntu 18.10 the command to copy the css would be different, since `gdm3.css` alias to the alternatives, point back to the `Yaru/gnome-shell.css`. Not sure how to document that, so I let it to you. Here are the commands to customize Ubuntu 18.10.

```
sudo cp -av /usr/share/gnome-shell/theme/Yaru/gnome-shell.css{,~}
sudo cp -v gnome-shell.css /usr/share/gnome-shell/theme/Yaru/gnome-shell.css
```
And for restore:
```
sudo mv -v /usr/share/gnome-shell/theme/Yaru/gnome-shell.css{~,}
```
Also... someone should confirm this, in order to exclude that it might be different on different Ubuntu installations/contexts.

**Comment by nana-4** [comment]
@ddnexus Thanks a lot for pointing it out! I've confirmed it and updated the wiki. :)

**Comment by nana-4** [comment]
@PJSingh5000 Sounds interesting. But I don't think it'll work well, because we need to replace `/usr/share/gnome-shell/gnome-shell-theme.gresource` as well in order to change the GDM theme.

However, if you confirm that it works well, please let me know.

**Comment by PJSingh5000** [comment]
nana-4, ddnexus,

How about something like this?
I think it is more elegant than overwriting files.

The user can install as many themes as he/she wants and easily switch between them.
This approach allows the user to use a GUI to chose which theme he/she wants to use.

(I listed the commands in steps 1, 3, and 4 explicitly, just to make it clear. Ideally, a bash `for` loop can be used to reduce the number of lines).

(1)
Compile each theme
```
cd /usr/share/themes/Materia/gnome-shell/
sudo glib-compile-resources --target=gnome-shell-theme.gresource gnome-shell-theme.gresource.xml

cd /usr/share/themes/Materia-compact/gnome-shell/
sudo glib-compile-resources --target=gnome-shell-theme.gresource gnome-shell-theme.gresource.xml

cd /usr/share/themes/Materia-dark/gnome-shell/
sudo glib-compile-resources --target=gnome-shell-theme.gresource gnome-shell-theme.gresource.xml

cd /usr/share/themes/Materia-dark-compact/gnome-shell/
sudo glib-compile-resources --target=gnome-shell-theme.gresource gnome-shell-theme.gresource.xml

cd /usr/share/themes/Materia-light/gnome-shell/
sudo glib-compile-resources --target=gnome-shell-theme.gresource gnome-shell-theme.gresource.xml

cd /usr/share/themes/Materia-light-compact/gnome-shell/
sudo glib-compile-resources --target=gnome-shell-theme.gresource gnome-shell-theme.gresource.xml
```

(2)
Rename the original gnome-shell-theme.gresource
```
sudo mv /usr/share/gnome-shell/gnome-shell-theme{,-original}.gresource
```
(3)
Setup alternatives for top bar, dash, and lock screen (gnome-shell-theme.gresource)
```
path=/usr/share/gnome-shell/gnome-shell-theme-original.gresource
sudo update-alternatives --install /usr/share/gnome-shell/gnome-shell-theme.gresource gnome-shell-theme $path 100

path=/usr/share/themes/Materia/gnome-shell/gnome-shell-theme.gresource
sudo update-alternatives --install /usr/share/gnome-shell/gnome-shell-theme.gresource gnome-shell-theme $path 101

path=/usr/share/themes/Materia-compact/gnome-shell/gnome-shell-theme.gresource
sudo update-alternatives --install /usr/share/gnome-shell/gnome-shell-theme.gresource gnome-shell-theme $path 102

path=/usr/share/themes/Materia-dark/gnome-shell/gnome-shell-theme.gresource
sudo update-alternatives --install /usr/share/gnome-shell/gnome-shell-theme.gresource gnome-shell-theme $path 103

path=/usr/share/themes/Materia-dark-compact/gnome-shell/gnome-shell-theme.gresource
sudo update-alternatives --install /usr/share/gnome-shell/gnome-shell-theme.gresource gnome-shell-theme $path 104

path=/usr/share/themes/Materia-light/gnome-shell/gnome-shell-theme.gresource
sudo update-alternatives --install /usr/share/gnome-shell/gnome-shell-theme.gresource gnome-shell-theme $path 105

path=/usr/share/themes/Materia-light-compact/gnome-shell/gnome-shell-theme.gresource
sudo update-alternatives --install /usr/share/gnome-shell/gnome-shell-theme.gresource gnome-shell-theme $path 106
```

(4)
Setup alternatives for GDM (gdm3.css)

```
path=/usr/share/gnome-shell/theme/gnome-shell.css
sudo update-alternatives --install /usr/share/gnome-shell/theme/gdm3.css gdm3.css $path 100

path=/usr/share/themes/Materia/gnome-shell/gnome-shell.css
sudo update-alternatives --install /usr/share/gnome-shell/theme/gdm3.css gdm3.css $path 101

path=/usr/share/themes/Materia-compact/gnome-shell/gnome-shell.css
sudo update-alternatives --install /usr/share/gnome-shell/theme/gdm3.css gdm3.css $path 102

path=/usr/share/themes/Materia-dark/gnome-shell/gnome-shell.css
sudo update-alternatives --install /usr/share/gnome-shell/theme/gdm3.css gdm3.css $path 103

path=/usr/share/themes/Materia-dark-compact/gnome-shell/gnome-shell.css
sudo update-alternatives --install /usr/share/gnome-shell/theme/gdm3.css gdm3.css $path 104

path=/usr/share/themes/Materia-light/gnome-shell/gnome-shell.css
sudo update-alternatives --install /usr/share/gnome-shell/theme/gdm3.css gdm3.css $path 105

path=/usr/share/themes/Materia-light-compact/gnome-shell/gnome-shell.css
sudo update-alternatives --install /usr/share/gnome-shell/theme/gdm3.css gdm3.css $path 106
```

(5a) Select which theme you want to use (commandline technique)
```
sudo update-alternatives --config gnome-shell-theme

sudo update-alternatives --config gdm3.css

1. The new theme is now set.
2. To see the changes, restart gnome-shell (Alt-F2 r) or simply log-out and log back in.

```
(5b) Select which theme you want to use (GUI technique)
```
sudo apt install galternatives
```
1. Launch Alternaives Configurator
2. Click on gnome-shell-theme.gresource and select which theme you want for top bar, dash, and lock screen.
3. Click on gdm3.css and select which theme you want for GDM.
4. The new theme is now set.
5. To see the changes, restart gnome-shell (Alt-F2 r) or simply log-out and log back in.

![screenshot from 2018-11-12 21-59-25](https://user-images.githubusercontent.com/19394936/48388137-517f2400-e6c6-11e8-9965-cbface286e51.png)

![screenshot from 2018-11-12 21-59-39](https://user-images.githubusercontent.com/19394936/48388142-53e17e00-e6c6-11e8-80e2-8b2bf4f6fd8d.png)

Notes:

If you see a "Commit failed" warning, this is normal and means you need to enter your admin password.
1. Click the "Close" button on the warning dialog.
2. An "Apply" button will appear at the bottom of the Alternatives Configuraor window.
3. Click the "Apply" button.
4. Enter your admin password when prompted and click "Authenticate".


A system update may reset the top bar, dash, and lock screen theme.
This will happen whenever the package gnome-shell-common is updated.
To correct this, simply execute the following:
```
sudo mv /usr/share/gnome-shell/gnome-shell-theme{,-original}.gresource
sudo ln -s /etc/alternatives/gnome-shell-theme /usr/share/gnome-shell/gnome-shell-theme.gresource
```

**Comment by nana-4** [comment]
@PJSingh5000 Thank you for your great research!

Well, I tried your installation method on Ubuntu 18.10 VM, but unfortunately it doesn't work for me. :(
Maybe I just made some mistake, but both default gnome-shell theme and GDM theme are still Yaru.

> How about something like this?
> I think it is more elegant than overwriting files.

I'm still not sure if I'd agree with it, even if I could successfully change the theme.
I want to judge it after reviewing your script.

When you refine your script, please note that the `/usr/share/gnome-shell/theme/gdm3.css` is a Ubuntu specific file. Other distros don't have it. (IIRC, it is a file for Ubuntu to have a unique GDM theme.)

Also, can you implement a function to uninstall it completely in your script?

Finally, I have a small concern about renaming `/usr/share/gnome-shell/gnome-shell-theme.gresource` for security risks. What do you think about this?

**Comment by nana-4** [comment]
Oh... I just noticed that Arch Linux doesn't provide `update-alternatives` package. See:

https://www.archlinux.org/packages/?sort=&q=update-alternatives

and AUR too:

https://aur.archlinux.org/packages/?O=0&SeB=nd&K=update-alternatives&outdated=&SB=n&SO=a&PP=50&do_Search=Go

So we shouldn't rely on `update-alternatives`. It's biased towards Debian/Ubuntu.

Is it possible to achieve it without using `update-alternatives`?

**Comment by PJSingh5000** [comment]
I do install gnome-session, so that may be the part that you were missing when you tested?

I'll investigate if there is a nice way to do this without update-alternatives, and I'll share if I come up with something useful.

**Comment by nana-4** [comment]
> I do install gnome-session, and and then choose Gnome Session on the GDM screen.
That may be the part that you were missing when you tested?

Yes, I didn't install `gnome-session` on the VM. Maybe it is the cause. :)

> I'll investigate if there is a nice way to do this without update-alternatives, and I'll share if I come up with something and let you guys judge if it's worthwhile.

Thanks a lot!

**Comment by nana-4** [comment]
> I ended up with two scripts. Please let me know what you think?

IMHO, this seems too complicated to adopt within this repository. (Additional dependencies, complex method/steps, and support for other third-party themes...) And to be honest, it does not look much user-friendly than the current method.

I think such extensive and complex method/scripts should be managed in another repository. (FYI, there is already a GDM theme manager in GUI called [Loginized](https://github.com/juhaku/loginized) for similar purposes. Although I have never tried it.)

Even though I appreciate your efforts and hard work, I can't adopt it. To adopt within this repository, it needs to be simpler and more user-friendly. Sorry.

**Comment by nana-4** [comment]
Of course, we can link [Loginized](https://github.com/juhaku/loginized) and/or your scripts' repository in our doc to introduce alternative methods, though.

**Comment by ddnexus** [comment]
@PJSingh5000: it looks like a lot of work!

As @nana-4 suggested it would be more appropriate to put it in its own repository, where it will be likely also useful for other themes. And indeed it looks quite intimidating for simple theme-users.
