### ISSUE TITLE
Toolbar Color?

### ISSUE THREAD

**Issue by sxnaprkhr** [nana-4/materia-theme#304]
Not really an issue. Just wanted to know the color of the top toolbar(the one that is the background of the three icons(min, max, close)).

![screenshot from 2018-11-01 23-47-04](https://user-images.githubusercontent.com/29610365/47870926-adc58680-de30-11e8-9202-50e6557dff61.png)

**Comment by actionless** [comment]
it's dark gray

**Comment by sxnaprkhr** [comment]
Hex Code?

**Comment by actionless** [comment]
why can't you use color picker?

**Comment by nana-4** [comment]
@sxnaprkhr If you are talking about the button's foreground color, that's [`rgba(255, 255, 255, 0.7)`](https://github.com/nana-4/materia-theme/blob/07c0a8a3e48a4b17573330b91a57d859b26b5b89/src/_sass/_colors.scss#L28).
(and on hovering `#FFFFFF`)

**Comment by sxnaprkhr** [comment]
@nana-4 I wanted to know the color of top toolbar, not that button, but I got to know the background color of top toolbar using Gpick. Anyways, thanks for reaching out.
