### ISSUE TITLE
Budgie's Raven Panel Bug

### ISSUE THREAD

**Issue by jmauss** [nana-4/materia-theme#305]
- Version: 20180928-2
- GTK+ 3 version: 3.24.1
- Distribution: Arch Linux (latest)
- Desktop environment: Budgie-desktop 10.4
- Related application: Raven (side panel for budgie)
- Steps to reproduce: Apply any of the Materia themes in Budgie, and the colors/fonts are messed up in the raven panel
![ss](https://user-images.githubusercontent.com/11668753/47875999-0de30b00-dde6-11e8-95f8-b7b5ab6da00c.png)

(specifically the two buttons on the top are blue which doesn't match the theme and doesn't show the buttons themselves, and the text below with a yellow line underneath. The line is under one of two options that should have text above it)

**Comment by Jacalz** [comment]
Same issue here on Solus when using what will become Budgie 10.5, would like to get this fixed...
