### ISSUE TITLE
Apply correct style to cinnamon 4's grouped window list

### ISSUE THREAD

**Issue by luisfpg** [nana-4/materia-theme#310]
#### Reporter Info

- Materia version: 20180928-2
- GTK+ 3 version: 3.24.1
- Distribution (and version): Arch Linux
- Desktop environment (and version): Cinnamon 4.0.1-1

#### Actual Issue

A new default widget in Cinnamon 4 is the grouped window list, which is as a dock.
It seems that default Cinnamon style is applied.

#### Steps to Reproduce

1. Install Cinnamon in Arch Linux, or version 4.0.0 in some other rolling-release distro
2. Make sure the panel has a grouped window list applet
3. See the ugly style ;)

Here is an example in a vertical panel, which I prefer (note the icons are not horizontally-centered):
![image](https://user-images.githubusercontent.com/1183737/48630436-6ea44300-e9a3-11e8-9c51-81e33c751fc1.png)

And here is an example in a horizontal panel:
![image](https://user-images.githubusercontent.com/1183737/48630499-8ed40200-e9a3-11e8-9205-b2a470614c94.png)

**Comment by actionless** [comment]
cc @smurphos

**Comment by smurphos** [comment]
Materia and Oomox are on my to-do list...hopefully this weekend...
