### ISSUE TITLE
Selection widgets by touchscreen are not themed correctly

### ISSUE THREAD

**Issue by hexauniverse** [nana-4/materia-theme#313]
Materia v20181115
GTK+ 3 version: 3.24.1
Arch, 4.18.12
Gnome 3.30

![](https://i.imgur.com/D9SLPH7.png)

![](https://i.imgur.com/8AIelQD.png)

![](https://i.imgur.com/1sWRsJR.png)

**Comment by nana-4** [comment]
Thanks for the report. 

Unfortunately, I cannot reproduce this because I have not installed GNOME on the touch devices.

Does anyone know how to show the selection widget on non-touch device?

**Comment by hexauniverse** [comment]
i have no idea(

**Comment by flipflop97** [comment]
@nana-4 The GTK debugger has an option to simulate touch input with the mouse under Visual -> Simulate touchscreen.

**Comment by nana-4** [comment]
@flipflop97 Wow, thank you so much!! I didn't know the feature despite I use the inspector every debugging the theme 😂

**Comment by monday15** [comment]
@nana-4 i assume gtk trying to fit larger image to smaller area and artefacts appers, probably, changing this can help (height to 30):
https://github.com/nana-4/materia-theme/blob/6386a791691e15ae0307836d134a05e91dd8ecbf/src/_sass/gtk/_common-3.20.scss#L17-L18
also, you're using wrong asset for "insertion-cursor" - arrow should be pointed to top 



> ![](https://camo.githubusercontent.com/05c38d24e8c4b62aec6b4b04d912b3471fad05e4/68747470733a2f2f692e696d6775722e636f6d2f384149656c51442e706e67)

i guess you need to set another asset here
https://github.com/nana-4/materia-theme/blob/6386a791691e15ae0307836d134a05e91dd8ecbf/src/_sass/gtk/_common-3.20.scss#L3414-L3421

**Comment by nana-4** [comment]
@monday15 Thanks for your help. Now I've addressed this issue :)
