### ISSUE TITLE
Entry & combo button on headerbar not visible

### ISSUE THREAD

**Issue by PJSingh5000** [nana-4/materia-theme#316]
#### Reporter Info

- Materia version: 64f258dd42059d9764daf2bfc2beb50867c42dec
- Materia version: 577ca37cb18a31fc5e1fde2d8b4ce69cdd81c585
- GTK+ 3 version: 3.24.1-1ubuntu2 
- Distribution (and version): Ubuntu 18.10
- Desktop environment (and version): GNOME Shell 3.30.1
- Related application (and version): GNOME nautilus 3.26.4

#### Actual Issue
Font in Nautilus path-bar is not visible when the path-bar is in edit mode (enabled using <kbd>Ctrl</kbd>-<kbd>L</kbd>).

This occurs when using the Materia theme, but not with the Materia-dark or Materia-light themes.

#### Steps to Reproduce
1. Select Materia theme
2. Launch Nautilus
3. Press <kbd>Ctrl</kbd>-<kbd>L</kbd>keys to make the path bar editable
4. Notice the text is dark against a dark background.

![screenshot from 2018-11-26 16-18-36](https://user-images.githubusercontent.com/19394936/49042743-ff92cf80-f196-11e8-95f5-fdf8b0f0addb.png)

**Comment by nana-4** [comment]
Right, restyling of `entry` & `button.combo` is still WIP on `master` branch...

**Comment by PJSingh5000** [comment]
OK, thx! :)

**Comment by IgorHordiichuk** [comment]
Hi! Epiphany (aka WEB) has the same issue
![screenshot from 2018-11-30 00-51-55](https://user-images.githubusercontent.com/34414563/49257258-64ba1f80-f43a-11e8-896b-d129abbc6c0f.png)

**Comment by darcn181** [comment]
I was gonna report the issue and had a little surprise, i was using tilix and noticed it with  the dark theme. The text entries look weird.
![2018-12-01_18-38](https://user-images.githubusercontent.com/28988467/49333661-2edf7d00-f599-11e8-8d4f-2907f5c35326.png)
So i went in to the inspector and tried to fix it by myself and this is what i got.
![2018-12-01_18-37](https://user-images.githubusercontent.com/28988467/49333656-13747200-f599-11e8-9ebb-c543db5646d4.png)
It follows the Material Design guidelines the only thing shady is the code, but since only i use it, i don't care.

Here's the code i used in the inspector
```

headerbar box.linked.horizontal entry {
	color: white;
	background-color: alpha (CurrentColor, 0.1);
	box-shadow: none;
        border-bottom: 2px solid white;
	border-radius: 2px 0px 0px 0px;
}

headerbar box.linked.horizontal button.popup {
	color: white;
	background-color: alpha (CurrentColor, 0.1);
	border-radius: 0px 2px 2px 0px;
        border-image: radial-gradient(circle closest-corner at center calc(100% - 1px), white 100%, transparent 0%) 0 0 2/0 2 2px;

}
```
That's only for tilix and some apps though, if you want them to look like that globally i think it should work with this

```
headerbar entry {
        color: white;
	background-color: alpha (CurrentColor, 0.1);
	box-shadow: none;
        border-bottom: 2px solid white;
	border-radius: 2px 0px 0px 0px;
}

```

**Comment by PJSingh5000** [comment]
darcn181,

For me, this bug has been a major usability issue; most annoyingly, it shows up on the "Save As" dialog box, since you can't see the name or location of the file you are about to save.

Your tip above has helped to at least make the text color white, so I can see it.

In the file, `/usr/share/themes/Materia-Papirus/gtk-3.0/gtk.css`, I changed the following lines...

```
headerbar entry,
headerbar spinbutton,
headerbar button {
  margin-top: 6px;
  margin-bottom: 6px;
}
```
...to...
```
headerbar entry,
headerbar spinbutton,
headerbar button {
  margin-top: 6px;
  margin-bottom: 6px;
  color: white;
}
```

I'm really looking forward to this getting fixed properly. :)

**Comment by PJSingh5000** [comment]
...Humm, this doesn't affect the entry field of the `filechooser`  (Save As Dialog) headerbar.

Any suggestion on what I can tweak to fix that?

**Comment by darcn181** [comment]
I think it should be fixed if you add it to ~/.config/gtk-3.0/gtk.css instead of the theme's original file.
But if that doesn't fix the issue try the code in the gtk inspector under the css tab. I can't test it myself since i don't have those headerbars because i use xfce.

**Comment by nana-4** [comment]
Thanks guys for your help. I've addressed this issue. Now you can try it out from latest `master` :)
