### ISSUE TITLE
Toolbar font color is incorrect

### ISSUE THREAD

**Issue by IgorHordiichuk** [nana-4/materia-theme#317]
#### Reporter Info
- Materia version: v20181125
- GTK+ 3 version: how to find it for Fedora?
- Fedora 29;
- Gnome v.3.30.2
- Visual Studio Code v.1.29.1, Avocode v.3.6.4

#### Actual Issue
 Black font color in some applications toolbar with Materia and Materia-compact

#### Steps to Reproduce
 Open application

VS code:
![screenshot from 2018-11-29 23-21-52](https://user-images.githubusercontent.com/34414563/49260313-c16f0780-f445-11e8-9e68-340253aac855.png)

Avocode:
![screenshot from 2018-11-29 23-23-46](https://user-images.githubusercontent.com/34414563/49260290-9dabc180-f445-11e8-81c7-880571df4805.png)

**Comment by nana-4** [comment]
Thanks for your report.

I looked at the problem for a while, but it seems to be rather a bug of **Electron**.
See https://github.com/electron/electron/issues/15823.

(Therefore it also occurs with Atom as well.)

Electron doesn't seem to read the `menubar > menuitem` color of GTK+ theme properly, so we can't fix this by the theme, unfortunately.

**Comment by IgorHordiichuk** [comment]
Ok. Thanks
