### ISSUE TITLE
Volume and brightness sliders invisible with GDM theme installed

### ISSUE THREAD

**Issue by babba22** [nana-4/materia-theme#325]
#### Reporter Info

- Materia version: v20181115
- GTK+ 3 version: 3.22.30
- Distribution (and version): Solus
- Desktop environment (and version): Gnome 3.28
- Related application (and version): -

#### Actual Issue

I installed the GDM theme as explained [here](https://github.com/nana-4/materia-theme/blob/master/src/gnome-shell/README.md) and it worked flawlessly. Problem is that now both audio and brightness bars show only the green dot, but not the slider:

![screenshot from 2018-12-09 14-12-02](https://user-images.githubusercontent.com/14874690/49697838-77f88800-fbbc-11e8-9ffe-0bafe28c1d6d.png)

I get the same annoyance also on the pop-up that appears when changing volume or brightness level using keyboard shortcuts:

![screenshot from 2018-12-09 14-21-29](https://user-images.githubusercontent.com/14874690/49697951-da05bd00-fbbd-11e8-96c1-9fa598fecad1.png)

![screenshot from 2018-12-09 14-21-49](https://user-images.githubusercontent.com/14874690/49697954-dd00ad80-fbbd-11e8-893e-a432bc9a0f66.png)

**Comment by nana-4** [comment]
Hi. How did you get Materia theme itself? Manually? Or from a distro package?

It seems you unexpectedly installed the **3.30** version of gnome-shell/gdm theme, even though your GNOME version is 3.28. I don't yet know why it happened.

**Comment by babba22** [comment]
Hi, I installed the package offered by the distribution and gnome-shell was already installed... so that means that probably I should tell to the mainteiners of the distro about this problem?

In the meanwhile, how can I solve this problem? Do I have to uninstall materia offered by the distribution and install from github?

Thank you for your help!

**Comment by nana-4** [comment]
Thanks for the info. Before telling to the maintainers of the distro, to make sure, please run the following commands and paste the logs:

```
gnome-shell --version
```

```
grep -c barlevel /usr/share/themes/Materia-dark/gnome-shell/gnome-shell.css
```

> EDIT: in /usr/share/gnome-shell/ I have two gresource file: gnome-shell-theme.gresource and gnome-shell-osk-layouts.gresource, is this a problem?

It is normal and should be no problem :) All distros have the two gresource files by default.

**Comment by babba22** [comment]
Here you are:

![screenshot from 2018-12-09 22-49-07](https://user-images.githubusercontent.com/14874690/49703382-af8b2280-fc04-11e8-8cfa-db71548e3704.png)

**Comment by nana-4** [comment]
Thanks! As expected, 3.30 version seems to be installed which is incompatible with 3.28.

> In the meanwhile, how can I solve this problem? Do I have to uninstall materia offered by the distribution and install from github?

Yup, that should solve this problem.

**Comment by nana-4** [comment]
After investigation, I found that [`materia-gtk-theme*-20181115-7-1-x86_64.eopkg` packages](https://packages.solus-project.com/unstable/m/materia-gtk-theme/) contain only 3.30 version of gnome-shell theme. So this problem should be specific to the Solus packages.

Could you tell to the maintainers of the distro about it?

**Comment by babba22** [comment]
Thank you very much!

Sure, I'll try to report this problem to the devs :+1:

**Comment by babba22** [comment]
[Problem solved](https://dev.getsol.us/T7303) :+1:

**Comment by nana-4** [comment]
@babba22 Good news. Thank you for your report! So I'm gonna close this :)
