### ISSUE TITLE
[Feature Request] Add Support for Light Themes on Apps When Materia Dark Variants are Enabled

### ISSUE THREAD

**Issue by btd1337** [nana-4/materia-theme#326]
Many new apps are coming with switch theme option. In Materia Light it's works fine but in Dark variant this switch doesn't works properly.

Look:

## Materia Default Theme

Sequeler App Using **Light** Variant: **Fine** (Just white labels isn't good)

![captura de tela de 2018-12-09 16-30-05](https://user-images.githubusercontent.com/11943860/49701152-b8153600-fbcf-11e8-8741-8013b83e46fa.png)

Sequeler App Using **Dark** Variant: **Fine**

![captura de tela de 2018-12-09 16-32-27](https://user-images.githubusercontent.com/11943860/49701178-0aeeed80-fbd0-11e8-98a5-b66b68f5ba6f.png)

## Materia Dark Variant

Sequeler App Using **Light** Variant: **Fail**

![captura de tela de 2018-12-09 16-14-22](https://user-images.githubusercontent.com/11943860/49701187-3bcf2280-fbd0-11e8-8150-965d0cbcf180.png)

Sequeler App Using **Dark** Variant: **Fine**

![captura de tela de 2018-12-09 16-36-59](https://user-images.githubusercontent.com/11943860/49701225-b26c2000-fbd0-11e8-8329-072b8a438829.png)

Could you add this same support on Dark variant theme?

Congratulations on this great work! Thank you in advance!

**Comment by nana-4** [comment]
HI. I think you are talking about elementary/Pantheon apps (as most of other GTK+ apps don't have the light/dark toggle).

In any case, having light theme variant while using dark theme is _technically_ impossible. Not only Materia-dark, but also all GTK+ dark theme can't have the option.

This is why elementaryOS doesn't have a global dark theme and instead its apps have the switch theme option...

**Comment by nana-4** [comment]
P.S.

> Just white labels isn't good

It should be another bug. And Materia doesn't officially support Pantheon at the moment. (See #69)
