### ISSUE TITLE
change_color: gtk2 theme is using MATERIA_VIEW for inputs and buttons

### ISSUE THREAD

**Issue by actionless** [nana-4/materia-theme#337]
i was trying to fix it but it seems what it could be problematic because in assets btn and entry are using the same background color

**Comment by nana-4** [comment]
It seems to work by adding the following code at the top of `sed`:

```bash
      -e '/color-surface/{n;s/#FFFFFF/%MATERIA_SURFACE%/g}' \
      -e '/color-base/{n;s/#FFFFFF/%MATERIA_VIEW%/g}' \
```

Maybe it would be better to apply this to all color vars of `assets.svg`...

p.s. Just FYI, I'm going to change the design of gtk2 entries like gtk3 one.

**Comment by actionless** [comment]
would you submit the fix or should i send a PR for those above?

**Comment by nana-4** [comment]
I'll submit the fix, thanks :)

**Comment by actionless** [comment]
also i think it could be added smth like this `ENTRY_BG=$(mix "$BG" "$FG" 0.04)` to use it in gtk2

**Comment by nana-4** [comment]
Thanks for the suggestion. But I'm going to change the entry background in SVG when I properly redesigned the gtk2 entries :)

**Comment by actionless** [comment]
good, let's just have at least some temporary solution so gtk2 will look more or less consistent for the users

**Comment by nana-4** [comment]
@actionless I've committed the fix. Sorry for being a bit late.

> Maybe it would be better to apply this to all color vars of assets.svg

I decided to do this after I review it more.

**Comment by actionless** [comment]
thanks a lot!
