### ISSUE TITLE
Material Design 2

### ISSUE THREAD

**Issue by vstyler96** [nana-4/materia-theme#341]
¡Hello! First of all, I would like to say that I love this theme for my gnome desktop, I want to say if is it possible to upgrade the theme to Material Design 2. I know that there are some new styles on the components, and that's all :heart: love you guys!
Here is an image:
![Material Design 2](https://blackcrawler.com/material.io.png)
And the site with components [Go to the components](https://material-components.github.io/material-components-web-catalog/#/)

**Comment by actionless** [comment]
or install `materia-theme-git` if you're running Arch

**Comment by vstyler96** [comment]
Great! That's true, I've just upgraded the theme, I love your hard work buddies :3

**Comment by actionless** [comment]
i am not working on materia, but just answering on some common questions on bug tracker sometimes because i am familiar with the theme internals a bit and so on

**Comment by vstyler96** [comment]
Thank you both guys! @nana-4 and @actionless, How can the thread be closed? D:

**Comment by nana-4** [comment]
@actionless I think you are rather a co-developer as you also frequently commit improvements in scripts and give various ideas for Materia :) Anyway thanks for your contribution!

@vstyler96 Thanks! Github issues can be closed with the "Close issue" button at the bottom of the page :) Anyway I'm gonna close this.
