### ISSUE TITLE
Default text color is too dark on vte-terminal

### ISSUE THREAD

**Issue by tliron** [nana-4/materia-theme#342]
Is there a way to avoid the bold font in the terminal? (I'm using Tilix, specifically)

It seems there is no way to change this within terminals, because they inherit the font selection from the theme. It would be great if there were a configuration option to avoid this.

**Comment by actionless** [comment]
i am not aware of tilix specifically but gnome-terminal for instance have it in it's own configuration

i guess you need to contact tilix developers on this

**Comment by tliron** [comment]
Actually, looking closely it is not just Tilix, and it's not exactly bold. I just noticed it most there. It seems that everywhere Materia causes fonts to be heavier. Do you know what causes this? Switching to a theme like Arc makes the issue disappear immediately.

**Comment by actionless** [comment]
try adding to your `~/.config/gtk-3.0/gtk.css`:

```css
* {
  text-shadow: none;
  font-weight: normal;
}
```

**Comment by tliron** [comment]
This had no effect (I restarted GNOME Shell). Is there somewhere in the Materia theme CSS that I can change the weight?

**Comment by actionless** [comment]
you can try doing it in some particular application using GtkInspector's CSS tab

**Comment by nana-4** [comment]
@tliron Is that only in the terminal apps? Could you attach screenshot(s) to know exactly which/where font you are talking about?

> Actually, looking closely it is not just Tilix, and it's not exactly bold. I just noticed it most there. It seems that everywhere Materia causes fonts to be heavier. Do you know what causes this?

If you are talking about **buttons** or **tabs**, it is intentional as in Material Design _medium_ font weight (`500`) is used for them. See:

- https://material.io/design/typography/the-type-system.html#type-scale
- https://material.io/design/components/buttons.html
- https://material.io/design/components/tabs.html

> Is there somewhere in the Materia theme CSS that I can change the weight?

Please search `font-weight: 500;` and try removing those lines.

**Comment by actionless** [comment]
the only difference i see in Materia screenhost text is slightly darker

**Comment by tliron** [comment]
The end effect is darker, but if you see it's either due to added weight or some change in anti-aliasing. It might seem subtle, but in everyday work it does make Materia unusable for me. I would happy to patch it myself, but first we need to figure out what is causing this. Removing the `font-weight` css did not change this.

Do you have some ideas that I can add as css overrides to GtkInspector to try it out?

**Comment by actionless** [comment]
try lighter fg color

**Comment by tliron** [comment]
Can you explain what you mean? Where would I change that in css?

**Comment by actionless** [comment]
for just testing purpose you can set it globally:

```css
* {
color: #999999;
}
```

**Comment by tliron** [comment]
This changes the colors for most things ... but not the terminal font. It seems that terminal font css comes from somewhere else. Actually you can try it yourself in GNOME terminal (Tilix uses the same VT widget).

**Comment by actionless** [comment]
anyway just for testing purpose could you override the foreground color in terminal preferences?

**Comment by tliron** [comment]
This changes the colors for most things ... but not the terminal font. It seems that terminal font css comes from somewhere else. Actually you can try it yourself in GNOME terminal (Tilix uses the same VT widget).

**Comment by tliron** [comment]
Overriding seems to work. But it seems that the defaults are somehow different in Materia as compared to other GTK themes.

**Comment by actionless** [comment]
just to clear it up, after changing font color "font rendering" problem got fixed?

**Comment by actionless** [comment]
if not please show the screenshots with the same fg/bg colors but different themes

**Comment by tliron** [comment]
If I set Tilix to use the internal color scheme, it is consistent across all GTK themes. But if I set Tilix to use "Use theme colors for foreground/background", then the problem appears.

**Comment by tliron** [comment]
By "problem" I mean the issue you can see in my attached photos above, which now we realize is probably due to a wrong "black" color.

There's no need to create a special theme for Tilix: actually, it already includes a material theme and there are many community themes. However ... the included material theme is dark, and I personally prefer my terminal to match the desktop theme (I use the default Materia, which is light). So I always have "Use theme colors for foreground/background" set and I'm usually happy with whatever GTK theme I use ... except Materia which has this issue. :)

**Comment by actionless** [comment]
> by "problem" you mean what Materia is not using your favorite color as terminal foreground?

> wrong "black" color.

that sounds like "yes" answer to the question above

**Comment by actionless** [comment]
do you mean in Materia TextView and Terminal colors are not matching?

**Comment by nana-4** [comment]
Ah, I got it. It seems the terminal screen (VT widget?) don't understand or ignore the **text alpha value**.

Materia uses `rgba(0, 0, 0, 0.87)` as primary dark text color, so the text color is supposed to be displayed like `#212121` on white background in RGB. However, in reality the text is displayed in `#000000` (pure black) on that terminal screen.

This problem should really be fixed upstream, but I'll add a workaround for this. Thanks for your report.

**Comment by nana-4** [comment]
@actionless 

> @nana-4 btw what do you think about generating some terminal themes for Materia users? 

I think it's better to talk about it in #157, but I will keep that in mind. Thanks for the suggestion.

**Comment by tliron** [comment]
Thanks @nana-4, I would be happy to help test. I'll subscribe to #157. Thanks also @actionless for your assistance!

**Comment by actionless** [comment]
@tliron to use those templates see this tutorial: https://gist.github.com/actionless/f9ad9e5ab9eac414dac8a3392beb3ad5

just at the last step choose `tilix` instead of `alacritty`

**Comment by tliron** [comment]
@actionless Thanks, there are quite a lot of themes already included in the repo linked above.

**Comment by actionless** [comment]
yeah, but you mentioned what you prefer light themes, and it's easier to swap light/dark colors from the UI

**Comment by nana-4** [comment]
So sorry for my delay in responding.

My guess was wrong. At first I thought adding this will work:

```css
vte-terminal { color: rgba(0, 0, 0, 0.87); }
```

In fact, however, VTE's text color is [hard-coded with `@theme_fg_color`](https://gitlab.gnome.org/GNOME/vte/blob/master/src/vtegtk.cc#L1676). That means, it won't be changed unless we change the color of that variable. But for some reasons I don't want do that in this theme.

So, please manually edit the [theme color variable](https://github.com/nana-4/materia-theme/blob/3073d51db843c3049e585ecc039fa16c47bb0aa7/src/gtk/3.0/gtk.css#L6169) (from `rgba(0, 0, 0, 0.87)` to `#212121`, for example), or report to the upstream that  transparency text color doesn't work.

I'm gonna close this as an upstream issue.
