### ISSUE TITLE
Suggest use of build hook to update GDM shell theme on Arch Linux

### ISSUE THREAD

**Issue by looselyrigorous** [nana-4/materia-theme#343]
On Arch Linux using a build hook could be suggested to re-apply the GDM shell theme. I have created such a hook [here](https://gist.github.com/looselyrigorous/a1aa931ce48627cc39daccc9253b30c7) and confirmed it works well.

It uses hard-coded values for the Materia-compact theme but this can be trivially changed to suit whatever Materia theme one uses. As the hook explicitly depends on the theme package it shouldn't ever break the `gnome-shell-theme.gresource` file (the hook will not run and will complain about missing deps).

**Comment by nana-4** [comment]
Thanks for your suggestion!

It seems like a good solution to avoid manually re-applying the GDM theme on Arch Linux. I'll mention it in `gnome-shell/README.md` and let me use your hook file as an example :)
