### ISSUE TITLE
Missing selection color when renaming files in Nemo

### ISSUE THREAD

**Issue by nrittsti** [nana-4/materia-theme#345]
- Materia version: v20181125
- GTK3 version: 3.24.2
- Distribution (and version): Manjaro 18.0.2
- Desktop environment (and version): Cinnamon 4.0.8 
- Related application (and version): Nemo 4.0.6

**Actual Issue**

User get no visual feedback by renaming files in Nemo.
The filename should be displayed as selected.
This issue is view dependent. "Icon View" and "Compact View" are effected.
Renaming in "List View" works fine.

![screenshot](https://user-images.githubusercontent.com/28309623/51083513-6c483600-1713-11e9-8ad6-26906b40c621.png)

**Steps to Reproduce**

1. Open Nemo
2. Switch to Icon View or  Compact View
3. Select a file or directory
4. Press F2

**Additional Info**
Other Themes, for examlpe Adapta, are not effected.

**Comment by nana-4** [comment]
Thank you for your report. I confirmed this bug.

**Comment by nrittsti** [comment]
Thank you for fixing the bug!
I will recommend Materia :-)
