### ISSUE TITLE
Selection Text Color or Сompatibility GTK with Qt

### ISSUE THREAD

**Issue by varlesh** [nana-4/materia-theme#350]
New selection colors looks different on GTK3-apps... but it's problem for port theme on Qt-apps
For example:
Selection color on Nautilus:
- sidebar - used **blue** translucent background with **blue** text color
- window - used **blue** translucent background with **white** text color
But this impossible doing for Qt-apps, because on Kvantum used single color text for all window elements and no division into sidebar or window
![screenshot_20190125_100258](https://user-images.githubusercontent.com/8083855/51728160-b4a71280-2088-11e9-9c9a-27745b70181a.png)

If use first variant (**blue** translucent background with **blue** text color) we have more problem with readable on some apps:
Qbittorrent
![image](https://user-images.githubusercontent.com/8083855/51728245-fcc63500-2088-11e9-9b37-6ffab74e15a7.png)
Clementine:
![image](https://user-images.githubusercontent.com/8083855/51728271-18c9d680-2089-11e9-88c1-a902eb142a34.png)

**Comment by varlesh** [comment]
Blue translucent background with white text color for sidebar more universal for GTK2, Qt, Oomox and others...

**Comment by varlesh** [comment]
@nana-4 Thx for your clarification, but If **Activated** style not possible use on more GTK3-apps, why you don't want use only **Selected** style for ALL? Now All apps looking different and this not good way and spoil unification and single style...
Please think about that before new release

**Comment by actionless** [comment]
also clementine is bad example -- it's rendering active playlist row with direct drawing commands, compare it with any other Qt app

**Comment by nana-4** [comment]
@varlesh Thanks for your suggestion. There are two reasons why I adopted the "Activated" style:

- Materia's policy is to follow the Material Design guidelines as much as possible.
- Optimistically I hope the Activated style will be able to use properly in the future with modern toolkits such as GTK & Qt.

But as you say, indeed using only "Selected" style as a workaround for consistency is an option worth considering. However, I want more feedback before doing that. After new release, if the new sidebar style is too unpopular, I'd like to consider removing the "Activated" style ;)

**Comment by nana-4** [comment]
@varlesh Can we close this now?

**Comment by varlesh** [comment]
yes
