### ISSUE TITLE
Materia Logos

### ISSUE THREAD

**Issue by varlesh** [nana-4/materia-theme#351]
How about Materia logo product?
For example:
![logo-materia-gtk](https://user-images.githubusercontent.com/8083855/51826102-b0d0f580-22ff-11e9-9aa7-6d9ae371bda8.png)
![logo-materia-kde](https://user-images.githubusercontent.com/8083855/51826110-b3cbe600-22ff-11e9-8f7b-49b45835469a.png)
SVG's:
[logos.tar.gz](https://github.com/nana-4/materia-theme/files/2802217/logos.tar.gz)

**Comment by nana-4** [comment]
Thanks for your excellent work! They look fantastic :)

However, I don't quite know where to use the logo, because this project is _just_ a theme.

Perhaps the only place where the logo can be used is **README** at the moment.

I don't quite know about KDE theme, but at least I think there is no suitable place to insert this logo into GTK/GNOME/Budgie/Cinnamon/MATE/Unity themes.

Do you have any idea where the logo can be used other than README?

**Comment by actionless** [comment]
going back to serious mood -- at least gnome interface guidelines discouraging using meaninful text on icons, idk about KDE

**Comment by nana-4** [comment]
_Side note:_ If we'll use the logo in the README of this repository, it would be better to remove the "GNOME" :footprints:  logo because in this repo we support Budgie/Cinnamon/MATE/Unity/etc as well.

**Comment by actionless** [comment]
> :eyes: 

icons doc is diverged in few different documents, see this one, 9.3.2:

https://developer.gnome.org/hig-book/unstable/icons-design.html.en

**Comment by varlesh** [comment]
@nana-4 you can remove GNOME logo on svg source.
It's logo for recognition, some themes have this... For example Adapta, Numix and etc...
@actionless it's only example mockup ))

**Comment by actionless** [comment]
i provided that point from HIG just as a topic to think, not as a suggestion

though i think it could make sense to split up to icon+only and textual logo versions

**Comment by nana-4** [comment]
> for recognition

I see. That makes sense :bulb::+1:

**Comment by Ghostium** [comment]
Maybe a bit overloaded? How about the M only but with split color like the Adapta logo.
![Adapta Logo](https://raw.githubusercontent.com/adapta-project/adapta-github-resources/master/images/logo_thumb.png)

**Comment by nana-4** [comment]
@varlesh Yeah, GTK logo version would be more neutral than the GNOME logo version :smiley: However, I have some concerns/issues about its icon design:

- The icon shape probably doesn't match any icon keyline shapes in the [Material icon guidelines](https://material.io/design/iconography/product-icons.html#grid-keyline-shapes). I'd love to follow the Material icon guidelines as much as possible.
- The small GTK logo and text (ATERiA) could be squished with smaller sizes (e.g. 48x48, 32x32).
- In Materia, Red is not one of the main colors (though I can understand why you picked the color, from the viewpoint of aesthetic).

**Comment by nana-4** [comment]
For the sake of argument, I made some logos based on the Material icon guidelines:

1. Horizontal rectangle shape (with subtle text?) like the design by @varlesh.

  ![materia-logo3-alt svg](https://user-images.githubusercontent.com/9556384/52105150-e728b080-2630-11e9-8e3c-946d60ea3cb3.png)

2. Another horizontal rectangle shape.

  ![materia-logo2-alt svg](https://user-images.githubusercontent.com/9556384/52105151-e8f27400-2630-11e9-893c-628b1eb6c240.png)

3. Circle shape (as @Ghostium suggested 🙂).

  ![materia-logo1 svg](https://user-images.githubusercontent.com/9556384/52102411-a5453d80-2623-11e9-86c0-112e9d1070ae.png)

I'm an amateur of icon making, so maybe there is room for improvement on these logos.
Any thoughts / ideas?

**Comment by ArchangeGabriel** [comment]
2. and 3. look good. :)

**Comment by Ghostium** [comment]
I agree with actionless it should not look like an envelope.

With split color I ment something like this:
![untitled](https://user-images.githubusercontent.com/15706162/52123980-1555c280-2628-11e9-8526-023f9a150c74.png)

But proper made in Inkscape and with better colors and shadows like the Papirus icons. @varlesh could you please?

**Comment by actionless** [comment]
what about such composition of elements?

![2019-02-01--1549026415_513x502_scrot](https://user-images.githubusercontent.com/1655669/52124780-ae85d880-262a-11e9-9a01-36f146a73d3d.png)


![2019-02-01--1549026340_715x388_scrot](https://user-images.githubusercontent.com/1655669/52124792-b80f4080-262a-11e9-973e-42f0bf3be001.png)

**Comment by ArchangeGabriel** [comment]
None of your propositions follow Material Design rules. And it’s not an envelope (even if it indeed looks like one), but the letter M.

**Comment by nana-4** [comment]
> why you both @varlesh and @nana-4 prefer to use envelope for the theme, which is far away from sending mails?
> what about trying to portray word "matter" but in material design style

I said *I'd love to follow the Material icon guidelines as much as possible* (because this theme is totally based on Material Design guidelines). According to the [icon guidelines](https://material.io/design/iconography/product-icons.html#design-principles):

> The tactile and physical quality of Material is reflected in the design of Material icons. Each icon is cut, folded, and lit as paper would be, but represented by simple graphic elements. The quality of Material is sturdy, with clean folds and crisp edges. Surfaces interact with light through subtle highlights and consistent shadows.

But I agree that my idea 1. looks too Gmail.

**Comment by actionless** [comment]
> None of your propositions follow Material Design rules.

>  and of-course re-draw them [circles] normally in material style

**Comment by nana-4** [comment]
> why you both @varlesh and @nana-4 prefer to use envelope for the theme, which is far away from sending mails?

Because Mateira encloses themes for _various_ DEs :)

**Comment by varlesh** [comment]
@actionless lol... my icons it's not envelope, it's **M**, but used form (circles, triangle and lines)

**Comment by varlesh** [comment]
@nana-4 yes, №3 very good... but maybe better change background to dark?
`#282828` or `#303030`
Why dark background? Because moctly sites used white page and colors merged

**Comment by nana-4** [comment]
> Because moctly sites used white page and colors merged

I personally don't think that's a matter, because in Material Design, shadows are used as borders :)

But for comparison, I made dark variations as well.

![materia-logo-alt2 svg](https://user-images.githubusercontent.com/9556384/52137958-36053300-268f-11e9-81de-2c60e327f063.png)![materia-logo-alt svg](https://user-images.githubusercontent.com/9556384/52137965-3998ba00-268f-11e9-900a-35ebf667eaf5.png)![materia-logo](https://user-images.githubusercontent.com/9556384/52137956-343b6f80-268f-11e9-9456-e999194a53dd.png)

**Comment by actionless** [comment]
still too much gmail

![](https://cdn.dribbble.com/users/4874/screenshots/1776423/inboxiconanimation_30.gif)

**Comment by nana-4** [comment]
@actionless Personally... disagree. They have different concepts (M vs. envelope) and different keyline shapes (circle vs. horizontal rectangle).

**Comment by varlesh** [comment]
![1 2019_02_01_21_16_04 0](https://user-images.githubusercontent.com/8083855/52139120-a64c8e00-2668-11e9-88fc-de95a058e071.png)

**Comment by actionless** [comment]
last one more precise, what about choosing the color shades in such way what M letter will be looking like a single stripe bended 3 times?

**Comment by varlesh** [comment]
with drop shadow
![Uploading Новый документ 1.2019_02_01_21_16_04.0.png…]()

**Comment by nana-4** [comment]
@varlesh Looks interesting 🧐 My only concern is that it may slightly deviate from the _keyline shape_ of the guidelines.

**Comment by varlesh** [comment]
@nana-4 i'm not use guidelines ))) Your color and forms only...
SVG if needed:
[Новый документ 1.2019_02_01_21_16_04.0.tar.gz](https://github.com/nana-4/materia-theme/files/2822672/1.2019_02_01_21_16_04.0.tar.gz)

**Comment by actionless** [comment]
and also i would change the angle, since 45 degree angle is not looking too much natural for M letter (and could be a reason why it causing those envelope associations)

**Comment by varlesh** [comment]
@actionless You really hate envelopes :rofl:

**Comment by nana-4** [comment]
@actionless  Logos are symbol, so it is not necessarily needed that the letter M looks natural :)

FYI, these are the official Material Design logos:

![image](https://user-images.githubusercontent.com/9556384/52140994-bd56a480-2697-11e9-9cde-d8bf606f6c0f.png)
![image](https://user-images.githubusercontent.com/9556384/52141127-1e7e7800-2698-11e9-9a77-7e4fab3f4b0e.png)

**Comment by actionless** [comment]
in official logo M shape is natural, exactly like in default github font for example:

M M M

**Comment by nana-4** [comment]
After some testing and reviewing, I decided to go with [this logo design](https://github.com/nana-4/materia-theme/blob/images/materia-logo.svg) because:

- It passes the Material icon guidelines completely.
- It looks the most modern among the candidates to me.
- It is somewhat similar (but not exactly the same) to the official Material Design logo.

So I'm going to close this issue. Thank you all for your participation and feedback!
