### ISSUE TITLE
Adapt to new GTK switch layout

### ISSUE THREAD

**Issue by flipflop97** [nana-4/materia-theme#352]
**Reporter Info**

- Materia version: https://github.com/nana-4/materia-theme/tree/831ea438e01d82b81d342eafb6db57cfa59ef8bf
- GTK3 version: 3.24.4+15+g80b5024239 (https://gitlab.gnome.org/GNOME/gtk/tree/80b5024239ee358ede8203666dfe9ea790a29b70)
- Distribution (and version): Arch Linux
- Desktop environment (and version): Gnome 3.30.2
- Related application (and version): GTK3

**Actual Issue**

GTK3 has updated their switch designs in the 3-24 branch to use on/off icons. These changes have now landed in the stable Arch Linux repositories. Using this new version in combination with Materia makes the switches look off/broken, see the image below. Materia should probably adapt to these changes.

![bug](https://user-images.githubusercontent.com/13943260/51939111-fb8d6300-240e-11e9-93b5-d58ec19cec41.png)  
*On/off icons look dark and out of place, selection circle and shadow are cut off and height has grown.*

**Comment by nana-4** [comment]
I've reported to the upstream: https://gitlab.gnome.org/GNOME/gtk/issues/1631

I'm gonna close this as upstream issue.
