### ISSUE TITLE
Materia-dark: Lack of contrast in nautilus side bar

### ISSUE THREAD

**Issue by memeplex** [nana-4/materia-theme#355]
The currently selected folder in Nautilus is barely legible because of lack of contrast between the foreground text and the selection background color:

![image](https://user-images.githubusercontent.com/2845433/52517570-f785f000-2c1b-11e9-9577-ca1d6118a55c.png)

```
[neu@archlinux ~]$ pkg-config --modversion gtk+-3.0
3.24.5

[neu@archlinux ~]$ yay -Qs materia
local/materia-gtk-theme 20190201-1
    A Material Design theme for GNOME/GTK+ based desktop environments

[neu@archlinux ~]$ uname -a
Linux archlinux 4.20.6-arch1-1-ARCH #1 SMP PREEMPT Thu Jan 31 08:22:01 UTC 2019 x86_64 GNU/Linux

[neu@archlinux ~]$ yay -Qs gnome-shell
local/gnome-shell 1:3.30.2-1 (gnome)
    Next generation desktop shell

[neu@archlinux ~]$ yay -Qs nautilus
local/nautilus 3.30.5-1 (gnome)
    Default file manager for GNOME
```

**Comment by actionless** [comment]
see https://github.com/nana-4/materia-theme/issues/350#issuecomment-457539922

**Comment by SmartFinn** [comment]
The new highlight makes the name of files unreadable:

![image](https://user-images.githubusercontent.com/819186/52524964-85f58280-2cab-11e9-9783-fa8db2807288.png)

**Comment by nana-4** [comment]
Thanks for filling the issue. In dark variant, indeed that contrast isn't very good.

I'll try to deal with it somehow.

**Comment by nana-4** [comment]
@SmartFinn Wow, I didn't notice that issue. However, in my opinion it is:

1.  a relatively minor problem in Materia.
2. rather an upstream issue in the old icon view ([related bug report](https://gitlab.gnome.org/GNOME/nautilus/issues/843)).
3. a resolved problem in the new icon view (try `gsettings set org.gnome.nautilus.preferences use-experimental-views true`):

  ![image](https://user-images.githubusercontent.com/9556384/52542182-922f2c00-2de0-11e9-8527-e958c8ae07af.png)
