### ISSUE TITLE
Check box bug

### ISSUE THREAD

**Issue by Degekai** [nana-4/materia-theme#356]
**Reporter Info**

- Materia version: latest
- GTK3 version: 3.24
- Distribution (and version): Arch Linux 
- Desktop environment (and version): 3.30
- Related application (and version): all

**Actual Issue**

![image](https://user-images.githubusercontent.com/29839093/52533129-475dd780-2d40-11e9-8079-69211a285f90.png)
![image](https://user-images.githubusercontent.com/29839093/52533131-5b093e00-2d40-11e9-8fb2-94b9ec39a493.png)
![image](https://user-images.githubusercontent.com/29839093/52533135-6a888700-2d40-11e9-9674-29c8853a093b.png)

**Steps to Reproduce**

1. Just check and uncheck checkboxes or radio

**Additional Info**

Remove this code from gtk.css fixes problem
```
check:focus,
radio:focus {
  box-shadow: inset 0 0 0 9999px alpha(currentColor, 0.12);
}

check:focus:hover,
radio:focus:hover {
  box-shadow: inset 0 0 0 9999px alpha(currentColor, 0.16);
}


switch:focus slider {
  box-shadow: 0 0 0 10px alpha(currentColor, 0.12), 0 1px 1px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
}

switch:focus:hover slider {
  box-shadow: 0 0 0 10px alpha(currentColor, 0.16), 0 1px 1px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
}

scale slider:focus {
  background-color: rgba(31, 132, 233, 0.12);
}

scale slider:focus:hover {
  background-color: rgba(31, 132, 233, 0.16);
}
```

**Comment by nana-4** [comment]
Hello,

Actually that is a **`:focus` state**, _not_ a bug.

I recommend you read the following Material Design Guidelines:

- https://material.io/design/interaction/states.html#focus
- https://material.io/design/components/selection-controls.html#checkboxes

Closing.
