### ISSUE TITLE
Add Firefox speficic settings

### ISSUE THREAD

**Issue by zeten30** [nana-4/materia-theme#358]
Hi, what about adding some Firefox specific settings to gtk/apps/. It think that Adapta theme (https://github.com/adapta-project/adapta-gtk-theme/blob/3559df9538505eaa91a22ecf4b08dc22928e9212/gtk/sass/3.20/_3rd-party.scss) can server like a good example. So far, there are small issues with text color and background. See attached screenshot (Firefox - show all bookmarks. Search filed is hardly readable).

![firefox-bookmars-materia](https://user-images.githubusercontent.com/1825873/52621728-52337c00-2ea8-11e9-88b4-f484da25c5fe.png)

**Comment by ArchangeGabriel** [comment]
This looks to me as https://bugzilla.mozilla.org/show_bug.cgi?id=70315.

**Comment by nana-4** [comment]
Thanks for your report.

We already had the Firefox-specific styling, but there was a bug in the entry, so I've fixed it.

**Comment by zeten30** [comment]
Fix works perfect. Thank you.
