### ISSUE TITLE
chrome PWA border color

### ISSUE THREAD

**Issue by k1nghat** [nana-4/materia-theme#359]
when chrome is using the gtk+ theme setting websites that are in PWA mode, or installed by creating a shortcut, have this border around them that is unstyled. when using a regular theme in chrome the PWAs will use whatever color style they have set in their manifest for the border color and websites that are installed via shortcut just have the unstyled border. i was wondering if its possible to be able to style the border of these PWAs/shortcuts? even better would be to allow the PWAs to use whatever color they have in their manifest and style the rest of the shortcuts via materia dark color. also, the titlebar text is black on dark when a website is installed:

![image](https://user-images.githubusercontent.com/16073360/52971215-3e8e8680-337c-11e9-832e-7da471618f4a.png)

**Comment by actionless** [comment]
is it happens only with Materia or also with other dark themes?

it is a known fact what new chrome UI have some colors hardcoded (let's say address bar), so i am just wondering if that border could be one of them




___________________



also as far as i know there is official Materia chrome theme available: https://github.com/nana-4/materia-theme#chrome-theme

**Comment by k1nghat** [comment]
>is it happens only with Materia or also with other dark themes?

>it is a known fact what new chrome UI have some colors hardcoded (let's say address bar), so i am just wondering if that border could be one of them

well its not hardcoded because when not using the gtk+ theme setting in chrome the actual PWAs with a manifest file can color that border whatever it wants. when using the gtk+ theme setting all windowed chrome apps, PWAs and installed shortcuts, get that uncolored border.

>also there is official Materia chrome theme available: https://github.com/nana-4/materia-theme#chrome-theme

ya the official materia chrome theme is just a theme and isnt nearly as thorough as the gtk+ theme setting.

**Comment by nana-4** [comment]
I'm sorry for my late response.

If I'm not mistaken, this problem seems to have already been fixed on the Chrome side. (tested with Chrome 74.0.3729.131)

Please let me know if this is still reproducible with the latest Chrome.

Closing for now.

**Comment by k1nghat** [comment]
> I'm sorry for my late response.
> 
> If I'm not mistaken, this problem seems to have already been fixed on the Chrome side. (tested with Chrome 74.0.3729.131)
> 
> Please let me know if this is still reproducible with the latest Chrome.
> 
> Closing for now.

yes, fixed.
