### ISSUE TITLE
XFCE Panel button text is unreadable

### ISSUE THREAD

**Issue by darcn181** [nana-4/materia-theme#360]
**Reporter Info**

- Materia version: https://github.com/nana-4/materia-theme/commit/bf4069d4d6a1cafbabfdfb87653932e299b6f1bc
- GTK3 version: 3.24.5
- Distribution (and version): Manjaro 18.0.4 Preview RC
- Desktop environment (and version): XFCE GTK3 4.13
- Related application (and version): XFCE4 Panel 4.13.4

**Actual Issue**

In XFCE gtk3 you cannot read the button titles
![captura de pantalla_2019-03-02_06-18-08](https://user-images.githubusercontent.com/28988467/53983632-8567d480-410f-11e9-8003-4f98345496ed.png)

This only happens if you have the option flat buttons disabled, Before:
![captura de pantalla_2019-03-02_06-19-10](https://user-images.githubusercontent.com/28988467/53983685-afb99200-410f-11e9-88c7-52ae4a7785b2.png)
After:
![captura de pantalla_2019-03-02_06-19-20](https://user-images.githubusercontent.com/28988467/53983691-b3e5af80-410f-11e9-8bf9-c72a289f424f.png)

**Comment by darcn181** [comment]
My ideas on how to resolve this issue:

- Make the text color change to black

- Make the button's background color #212121 and if the user wants this buttons transparent (for use in transparent panels) leave that button state when flat buttons are enabled (just as it is right now)

**Comment by nana-4** [comment]
Thanks for the report! I wasn't aware of the option 😅

I've fixed this problem by making the panel button always flat.
