### ISSUE TITLE
Quite invisible network icon on light theme (XFCE)

### ISSUE THREAD

**Issue by flakerZ** [nana-4/materia-theme#361]
Hi everyone! I'm using this amazing theme on **Xubuntu 18.04.2** with **XFCE 4.12** and **Materia v20190201**. I have an issue with the taskbar network icon, which isn't gray as other icons, but quite invisible, and I can't normally see my network status. Also, I'm using this theme combined with Papirus icon theme.
![изображение](https://user-images.githubusercontent.com/33183032/54051750-37280380-41eb-11e9-8c93-d7785eb6e7f6.png)

**Comment by flakerZ** [comment]
Okay, I probably "fixed" this bug with the maximum icon size option increasing, but this isn't the rightest way to fix this. Hope to see new version with fixes.

**Comment by actionless** [comment]
shouldn't it be up to your icon theme, not gtk theme?

have you tried switching to another icon theme in order to test?

**Comment by flakerZ** [comment]
No, it's not icon theme's fault (in my situation - Papirus), because I have tried Adapta theme with the same icon pack, and Adapta's panel icons was different and visible. Btw, this bug appears on application icons too, for example, Steam or anything else.

**Comment by flakerZ** [comment]
The latest version of Materia from Ubuntu repo fixed this issue.
