### ISSUE TITLE
Download bar in Chromium not matching dark theme - Chromium 73.0.3683.75 and GTK 3.24.7

### ISSUE THREAD

**Issue by ronasimi** [nana-4/materia-theme#362]
Since upgrading both Chromium and GTK today on Arch, download bar is light color and text is light color when using Materia dark.  Unsure if this is due to GTK update or Chromium update

![window-20190312-22:46:49](https://user-images.githubusercontent.com/3991859/54250221-47a4ea80-4519-11e9-9911-e55ffadd0ea3.png)

**Comment by ronasimi** [comment]
This is related to the dark mode being implemented in Chromium.  Adding --force-dark-mode to chromium-flags.conf fixed this on Arch.

**Comment by nana-4** [comment]
I can reproduce this even with the upstream **Adwaita-dark**. Which means it is not a Materia-specific bug.

Before reporting a bug, please, read the [issue template](https://raw.githubusercontent.com/nana-4/materia-theme/master/.github/ISSUE_TEMPLATE/bug_report.md) and check if it also occurs with the upstream theme. (In this case the upstream theme is "Adwaita-dark".)

I believe this is a bug on Chrome side, and I don't think it can be fixed on the theme side. So I'm going to close this as an upstream issue.
