### ISSUE TITLE
Wps office text theming in the UI is broken using Materia Dark

### ISSUE THREAD

**Issue by coreybruce** [nana-4/materia-theme#366]
**Reporter Info**

- Materia version: materia-theme-git r668.df19037-1 AUR
- GTK3 version: 3.24.5
- Distribution (and version): Manjaro Linux 18
- Desktop environment (and version): Cinnamon 4.0.9
- Related application (and version): WPS Office 10.1.0.6758

**Actual Issue**

Text is white on white on the page and the settings is unreadable/unusable when using Materia Dark

https://i.imgur.com/h6tBetG.png
https://i.imgur.com/vEpstwQ.png

**Steps to Reproduce**

1. install theme
2. switch to to theme dark for example
3. open WPS Office writer for example

**Additional Info**

**Comment by nana-4** [comment]
Sorry for my late response.

BTW, **did you check this when [submitting the new issue](https://github.com/nana-4/materia-theme/issues/new?assignees=&labels=&template=bug_report.md&title=)?**

> Before reporting a bug, please check whether it also occurs with other themes.
> If it also occurs with the upstream default theme, it is very likely an upstream issue.

I can reproduce this even with the upstream Adwaita-dark. So this is not an issue specific to Materia-dark.

Before reporting a bug, **please**, check whether it also occurs with other themes, especially upstream Adwaita (or Adwaita-dark).

I'm gonna close this as an upstream WPS Office issue.
