### ISSUE TITLE
Chrome materia-light scrollbar plugin does not work

### ISSUE THREAD

**Issue by xsrvmy** [nana-4/materia-theme#368]
Attempting to install chrome-scrollbar.crx throws the following error message:
Package is invalid: 'CRX_HEADER_INVALID'

Version info:
Distro - Ubuntu 18.04.2
Materia version - 20190201
Chrome version - 73.0

**Comment by nook-ru** [comment]
The same is for me

Fedora 29
Materia version - 20190315
Chrome version - 73.0.3683.86

**Comment by nana-4** [comment]
I confirmed this problem. Thanks for your report :)
