### ISSUE TITLE
[question] How to change window titlebar's buttons (minimise, maximise , close) appearance?

### ISSUE THREAD

**Issue by ParaSpl01t** [nana-4/materia-theme#370]
I am using Manjaro 18.0.4, Gnome Version 3.32.0.
Using gnome tweak I've already set application theme to Materia and shell theme to Materia Dark.
I want to edit minimise, maximise & close button's default and hover color. I checked the theme folder and there are many folders like chrome, gnome-shell gtk-* etc. which contains css and svg files. 
so my question is Which file contains titlebar's button styles?

I am new to gnome theming. If there is some info I didn't  provide, please let me know.

**Comment by ParaSpl01t** [comment]
> Alternatively, you can paste the code into `~/.config/gtk-3.0/gtk.css` to override the style of **all** the themes.

Thanks, this worked flawlessly. 
Is their any doc where I can find major css selector used in gtk themes?

**Comment by nana-4** [comment]
So sorry for the late reply..

> Is their any doc where I can find major css selector used in gtk themes?

As far as I know, there are the following:

- https://developer.gnome.org/gtk3/stable/chap-css-overview.html
- https://developer.gnome.org/gtk3/stable/chap-css-properties.html

Not a doc, but the source [_common.scss](https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/theme/Adwaita/_common.scss) is also a good file to find the major CSS selectors used in GTK :)

Also you can use the [GTK Inspector](https://blog.gtk.org/2017/04/05/the-gtk-inspector/) to directly inspect the selectors used in an app.

**Comment by ParaSpl01t** [comment]
Thanks for the links. very helpful.

**Comment by viz404** [comment]
> Hi,
> 
> On GNOME Shell, window titlebar's buttons are themed by GTK CSSs.

How to apply this to chrome and vscode and other third party applications ?
