### ISSUE TITLE
Issues displaying close button for window previews in dash to panel

### ISSUE THREAD

**Issue by ivaylo-iliev** [nana-4/materia-theme#373]
I am running latest Materia from github on Ubuntu 19.04 (Gnome 3.32). I noticed that the close buttons for the window previews in dash to panel are not displayed correctly and have small border around them. I managed to fix them by modifying the materia-theme/src/gnome-shell/3.32/gnome-shell*.css files and changing width, height and background-size for .window-close class from 36px to 32px wherever needed. 

Old version:
`.window-close {
  background-color: transparent;
  border-radius: 0;
  border: none;
  box-shadow: none;
  color: transparent;
  height: 36px;
  width: 36px;
  -shell-close-overlap: 18px;
  -st-background-image-shadow: 0 1px 1.5px rgba(0, 0, 0, 0.12), 0 1px 1px rgba(0, 0, 0, 0.24);
  background-image: url("assets/window-close.svg");
  background-size: 36px;
}`

New version:
`.window-close {
  background-color: transparent;
  border-radius: 0;
  border: none;
  box-shadow: none;
  color: transparent;
  height: 32px;
  width: 32px;
  -shell-close-overlap: 18px;
  -st-background-image-shadow: 0 1px 1.5px rgba(0, 0, 0, 0.12), 0 1px 1px rgba(0, 0, 0, 0.24);
  background-image: url("assets/window-close.svg");
  background-size: 32px;
}`

Please consider fixing this in future releases. Thanks for the great work.

**Comment by nana-4** [comment]
Thanks for your report.

Could you take a screenshot to clarify your problem? I don't see your problem at the moment.

![image](https://user-images.githubusercontent.com/9556384/56630692-234a3b00-668d-11e9-80f2-83cb214d53ed.png)


(Tested on Fedora Rawhide, GNOME Shell 3.32.0)

**Comment by ivaylo-iliev** [comment]
Hi, the issue was as seen on the screenshot, but the last pull from the repo fixed it. Thanks :)
![issue](https://user-images.githubusercontent.com/30646462/56659340-85169f00-66a5-11e9-811b-a63e91ad89d8.png)

**Comment by nana-4** [comment]
OK, then I'll close this issue :)
