### ISSUE TITLE
Some chrome/chromium completion popups look ugly and lacking contrast

### ISSUE THREAD

**Issue by memeplex** [nana-4/materia-theme#378]
![image](https://user-images.githubusercontent.com/2845433/57400725-85855e80-71aa-11e9-8352-0103ccb44617.png)

This screenshot is for the password manager autocomplete popup. The theme is materia dark compact. It happens with vanilla chromium and with chromium launched with the new `--force-dark-mode` switch, although contrast is improved in the second case.

Notice that when the popup first opens there is no problem. Then when you keep typing the prefix or navigate up/down the menu the background becomes darker as in the screenshot.

**Comment by memeplex** [comment]
Also reported to chromium issue tracker https://bugs.chromium.org/p/chromium/issues/detail?id=960939

**Comment by nana-4** [comment]
Thanks for your reports. I can reproduce this on Google Chrome 74.0.3729.131 with both Adwaita-dark and Materia-dark.

This is a problem common to all dark GTK themes, and it seems impossible to fix this on the GTK theme side.

I'm gonna close this as an upstream issue.

**Comment by memeplex** [comment]
Yes, my report in chromium tracker was merged as duplicate of many other similar reports. Hopefuly they will fix this, given that enough people are currently affected.

**Comment by nana-4** [comment]
Yeah. Just FYI, this problem doesn't happen when you apply the Materia-dark Chrome theme (`chrome-theme-dark.crx`). You can use it until the upstream solves the problem :)

**Comment by memeplex** [comment]
That's cool, thanks for the tip!

**Comment by memeplex** [comment]
Worked like a charm, indeed. Just out of curiosity, what is that chrome-scrollbar.crx that resides next to chrome-theme.crx?

**Comment by nana-4** [comment]
@memeplex It's an extension that changes the look of Chrome's scrollbars, literally...

**Comment by memeplex** [comment]
Do you know if it is possible to set materia theme for chromium standalone apps? I mean, the ones for which you create a shortcut and set to run in their own windows. These apps are always launched with the built-in theme despite the main configuration being gtk.

**Comment by memeplex** [comment]
Maybe I should open a FR for this. Using the .crx file you suggested shows a light titlebar, using the gtk materia dark theme shows a dark titlebar. Nevertheless, both bars have the title left-aligned and non-bold and are too compact, so it seems to me standalone apps require specific theming. What do you think?

**Comment by memeplex** [comment]
See https://github.com/nana-4/materia-theme/issues/380

**Comment by nana-4** [comment]
> Nevertheless, both bars have the title left-aligned and non-bold and are too compact, so it seems to me standalone apps require specific theming.

As I said in https://github.com/nana-4/materia-theme/issues/367#issuecomment-491680499, both GTK-level theme and Chrome-level theme only change the **color scheme** of Chrome, and cannot change other things such as font-weight, height of title bar, etc.
