### ISSUE TITLE
Provided chrome theme doesn't support standalone chrome apps

### ISSUE THREAD

**Issue by memeplex** [nana-4/materia-theme#380]
- Materia version: 20190315
- GTK3 version: 3.24.8
- Distribution (and version): Arch Linux 
- Desktop environment (and version): Gnome 3.32
- Related application (and version): chromium 74.0.3729.131

**Actual Issue**

Standalone apps don't have materia dark chrome theme when it has been correctly installed in chromium.

**Steps to Reproduce**

1. Install materia dark chrome theme in chromium. 
2. Go to some site and create an app shortcut from the More tools menu.
3. In the shortcut creation dialog check "Open as window".
4. Launch the created application.
5. Window theme doesn't match chromium theme.

**Comment by nana-4** [comment]
Thanks for the report. But I think it's an upstream bug. Even if you install any other Chrome themes, the title bar color of standalone chrome apps should not be changed.

So I'm gonna close this as an upstream issue. Please report it to the upstream.
