### ISSUE TITLE
Chrome Theme CRX Extension Error

### ISSUE THREAD

**Issue by irfanfadilah** [nana-4/materia-theme#382]
**Reporter Info**

- Materia version: 20190315
- Distribution (and version): Ubuntu 18.04
- Desktop environment (and version): GNOME3
- Related application (and version): 74.0.3729.157

**Actual Issue**

It raises `Package is invalid: CRX_HEADER_INVALID` when trying to install Chrome CRX files.

**Steps to Reproduce**

Drag and drop Chrome CRX files (theme and scrollbar) to `chrome://extensions/` page.

**Comment by irfanfadilah** [comment]
Might be related to https://github.com/nana-4/materia-theme/issues/368 since it has same error.

**Comment by nana-4** [comment]
Thanks for your report.

I don't know why the error happens, but we recently updated the .crx files.

So, could you try installing the latest .crx files and check if they are installable? (You can get the latest .crx files by [manually installing](https://github.com/nana-4/materia-theme#manual-installation) the materia-theme.)

**Comment by irfanfadilah** [comment]
@nana-4 `master` branch CRX files are worked fine and nice.

Also why don't you release these themes on Chrome Web Store too?

**Comment by nana-4** [comment]
> master branch CRX files are worked fine and nice.

That's good.

> Also why don't you release these themes on Chrome Web Store too?

Feel free to release these themes on Chrome Web Store. It requests US$5.00, though.

> The scrollbar extension raised this warning if installed using CRX file (load package worked fine tho)

Strange, I have not got that warning in my environment.

Anyway, if it works I would like to close this issue...
