### ISSUE TITLE
Reduce tabbar height in gnome terminal

### ISSUE THREAD

**Issue by memeplex** [nana-4/materia-theme#383]
I believe nobody likes the big tabbar in gnome terminal. Maybe I'm wrong, but what about reducing them a bit for the -compact variants, at least?

**Comment by nana-4** [comment]
Thanks for your suggestion.

Indeed, the tab bar in gnome-terminal is a little higher than other tab bars. This is due to the upstream has implemented the hard-coded spacing in that tab bar. But I will investigate if I can adjust the tab bar height only in gnome-terminal.

**Comment by memeplex** [comment]
It's certainly possible, it's a somewhat popular request, if you google it you will find many answers showing how to set gtk css.
