### ISSUE TITLE
Chrome theme uses different window icons than Gtk theme

### ISSUE THREAD

**Issue by memeplex** [nana-4/materia-theme#387]
This is in chrome (chromium) with the provided materia theme installed: 

![image](https://user-images.githubusercontent.com/2845433/58262203-344fa000-7d50-11e9-9081-bedb729d4f34.png)

This is in any other gtk app with the gtk materia theme installed:

![image](https://user-images.githubusercontent.com/2845433/58262235-49c4ca00-7d50-11e9-9183-2d5dc2a8da7c.png)

Notice how the maximize toggle differs (both screenshots were taken in maximized state).

Maybe the chrome theme cannot change that, I'm not sure.

**Reporter Info**

- Materia version: 
- GTK3 version: 3.24.8
- Distribution (and version): Arch Linux
- Desktop environment (and version): Gnome 3.32
- Related application (and version): Chromium 74.0.3729

**Comment by memeplex** [comment]
Oh, forget about this, I just discovered there is a toggle to use system titlebar that is independent of the current chrome theme.

**Comment by memeplex** [comment]
Rollback: this disable the headerbar... obviously... But now that I remember it is a headerbar we are talking about I have some additional faith that you can tweak that from the theme.

**Comment by memeplex** [comment]
Nevertheless this pushed me into another round of testing and I must say the native integration has advanced a bit in the latest chromium update, at least I'm not seeing the awful lack of contrast in some dropdowns.

**Comment by nana-4** [comment]
Thanks for the report.

It seems Chrome changes the icons from native icons to their own icons when applying the Chrome theme.
(FYI, both Materia GTK theme and Chrome theme don't provide any window icons on GNOME DE.)

And as you say, the Chrome theme cannot change the icons. So I'm going to close this issue as an upstream issue.

**Comment by nana-4** [comment]
> I remember it is a headerbar we are talking about I have some additional faith that you can tweak that from the theme.

Please remember: Chrome only reads **color information** from GTK themes or Chrome themes. Sizing, icon style, button style, etc. cannot be changed with GTK themes or Chrome themes.
