### ISSUE TITLE
DBeaver dark elements

### ISSUE THREAD

**Issue by rauldipeas** [nana-4/materia-theme#390]
DBeaver show weird dark elements and texts with Materia-dark.

I'm running on Ubuntu 19.04, with default version of GTK and DBeaver version is 6.0.5

The same has ocurring with Adwaita, light and dark.

![Dark](https://cdn1.ubugtrack.com/upload/upload_file-3401-360dd5cbc83e7e0b4759011681d6d2d5abe920c4-2019-05-28_18-39.png)

![Light](https://cdn1.ubugtrack.com/upload/upload_file-3401-6970026b403d72b34992d8edf11393978fec0ee9-image.png)

**Comment by nana-4** [comment]
Did you see the "**IMPORTANT NOTE**" [when submitting](https://github.com/nana-4/materia-theme/issues/new?assignees=&labels=&template=bug_report.md&title=) this issue?

> IMPORTANT NOTE:
>
> Before reporting a bug, please check whether it also occurs with other themes, especially Adwaita or Adwaita-dark. If it also occurs with the upstream default theme, it is very likely an upstream issue.

I mean, it is an issue that can be reproduced with Adwaita-dark, isn't it?

Also why did you skip the **Reporter Info**?

**Comment by rauldipeas** [comment]
This command won't work...
`pkg-config --modversion gtk + -3.0`

I'm getting this output:
`Unknown option -3.0`

**Comment by nana-4** [comment]
The issue template says "as much as possible" :-)

> Please provide the following information _as much as possible_.

If you don't know your GTK3 version, you can skip it -- as I can deduce your GTK3 version from your **distro version**. But in this case, the application version is more important.

**Comment by nana-4** [comment]
And could you test if this issue can be reproduced with **Adwaita-dark**, please?

**Comment by rauldipeas** [comment]
I  edited the first post, sorry for the mess.

**Comment by nana-4** [comment]
Thanks.

If it occurs with the upstream Adwaita-dark, we can't fix it on the theme side.

I believe this is a DBeaver issue. See https://github.com/dbeaver/dbeaver/issues/621 for example.

I'm going to close this as an upstream issue.
