### ISSUE TITLE
Include in upcoming snap common gtk themes?

### ISSUE THREAD

**Issue by memeplex** [nana-4/materia-theme#392]
I've requested your theme to be included as part of the ongoing initiative to enable theming of snap apps:

https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/issues/13

Eventually a snap app would be able to download arbitrary themes packaged as snaps, but a first step is to provide a snap bundle of common themes. I think yours is a good candidate for that list, even though it's not the default for any distro now (I don't understand Manjaro jumping from Adapta to anywhere else than Materia, but I don't understand many things Manjaro).

Further info:

https://forum.snapcraft.io/t/use-the-system-gtk-theme/496/43
https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235

**Comment by nana-4** [comment]
Sorry, but I don't understand why you filed this request here. I have no authority to include Materia in that snap package...

> even though it's not the default for any distro now

Not true. Materia is now the default for Ubuntu Studio 19.04 :)
(plus Condres OS, though it's not an Ubuntu-related distro)

**Comment by memeplex** [comment]
I filed it as a question just to let you know. I will mention the Ubuntu Studio fact there, then.

**Comment by nana-4** [comment]
Ah, thanks ;)

**Comment by memeplex** [comment]
@nana-4 now that you mention Ubuntu Studio is using materia, isn't there a ppa or official repo for ubuntu? I don't like installing the deb from debian sid a lot, plus I don't get update notifications.

**Comment by nana-4** [comment]
@memeplex There are official packages for Ubuntu: https://packages.ubuntu.com/search?keywords=materia-gtk-theme

**Comment by memeplex** [comment]
Cool, thanks! Shouldn't you add that to the README? It's misleading now because it refers to a PPA with packages for older Ubuntu versions and to SID. Clearly both options are worse for Ubuntu users.

**Comment by nana-4** [comment]
Did you see the word "**Ubuntu 18.04+**" in the README?

Ubuntu is a derivative of Debian, so Ubuntu packages are based on Debian packages. The package `materia-gtk-theme` for Debian and Ubuntu is also maintained by the Debian packager. This is why both "Debian testing / unstable" and "Ubuntu 18.04+" refer to the same package name/link.

But if the README is still misleading for some and if you have a clearer alternative, I'd be happy to update it :)

**Comment by memeplex** [comment]
Ok, what I found misleading is that it seems (at least to me) like if you're in ubuntu 18.04+ you must go to sid packages site, download a .deb, manually install it and hope it will work in your version of ubuntu. It was not clear to me that I could just have done `apt install materia-gtk-theme` because I didn't realize that it was in ubuntu repositories, just read that you may try luck with debian ones.

**Comment by memeplex** [comment]
Btw, the theme in ubuntu repository is outdated. It seems weird to me because the latest materia release was in March, which was before Ubuntu 19.04 release, but maybe that has to be with their feature freeze. Anyway, I ended up installing the deb by hand again :)

**Comment by nana-4** [comment]
Sorry for the late reply.

I've updated the README based on your feedback. I hope it'll no longer mislead someone... ;)

> Btw, the theme in ubuntu repository is outdated.

Yeah, but I'm not a maintainer of that package, so... 🤷

> Anyway, I ended up installing the deb by hand again :)

Alternatively you can [manually install the theme](https://github.com/nana-4/materia-theme#manual-installation), though :)
