### ISSUE TITLE
plank rclick menus are wonky

### ISSUE THREAD

**Issue by clumsyfingers** [nana-4/materia-theme#395]
everything that has been hovered stays with selected colour https://i.imgur.com/pvIlYPb.png

**Reporter Info**

- Materia version: 
- GTK3 version: 
- Distribution (and version): 
- Desktop environment (and version): 
- Related application (and version): 

**Actual Issue**

**Steps to Reproduce**

1. 
2. 
3. 

**Additional Info**

**Comment by nana-4** [comment]
It's duplicate of #300.

But thanks for your report :)
