### ISSUE TITLE
Dash to dock background is too dark

### ISSUE THREAD

**Issue by memeplex** [nana-4/materia-theme#396]
When docked and configured to follow the custom shell theme (which is Adwaita dark in my case), the extension uses a background that is too dark compared with the top bar background:

![image](https://user-images.githubusercontent.com/2845433/59064606-09ea0080-8881-11e9-9c17-331f4e88f495.png)

I think this mix of dark colors looks bad and unintentional.

- Materia version:  20190315
- GTK3 version: 3.24.8
- Distribution (and version): Arch (up to date), Ubuntu 19.04
- Desktop environment (and version): 3.32.2 
- Related application (and version): Dash to dock shell extension 61.1

**Comment by memeplex** [comment]
Moreover, setting a custom background color of #212121 is still not perfect because there is a tiny darker border between the dock and the top bar:

![image](https://user-images.githubusercontent.com/2845433/59065542-546c7c80-8883-11e9-8ff2-6d9fdbc6ef15.png)

**Comment by nana-4** [comment]
> Dash to dock background is too dark

It depends on your wallpaper. In Materia, dash-to-dock background is translucent black (`rgba(0, 0, 0, 0.6)`). So
- if your wallpaper is black, dash-to-dock appears in pure black.
- if your wallpaper is white, dash-to-dock appears in gray.

> there is a tiny darker border between the dock and the top bar

I can't reproduce it on Fedora. I guess you are on "Ubuntu" session, aren't you? If so, sorry but we won't GNOME sessions customized by distro. We only support non-customized GNOME sessions.

**Comment by memeplex** [comment]
I'm unable to reproduce it now, although it happened to me in the past both with Arch and with Ubuntu in many occasions. But recently I realized that after playing with the appearance settings of the extension it sometimes gets buggy and I need to reset some values from the dconf editor, specially regarding opacity mode (fixed, dynamic, etc). So it might be that I was in one of those "broken states" at the moment. Thanks!
