### ISSUE TITLE
[Feature Request] Decrease padding of panel buttons in  gnome-shell compact variant

### ISSUE THREAD

**Issue by ceyhunn** [nana-4/materia-theme#397]
It would be nice to decrease padding of panel buttons in gnome-shell compact variant, because in small resolution if user have many gnome extensions it captures a lot of places of gnome panel. I changed following code manually for fix.
From
```
.panel-button {
    -natural-hpadding: 12px;
    -minimum-hpadding: 6px;
    ....
}
```
to
```
.panel-button {
    -natural-hpadding: 6px;
    -minimum-hpadding: 4px;
    ....
}
```

**Comment by nana-4** [comment]
That makes sense, indeed.

Thanks for your suggestion!

**Comment by ceyhunn** [comment]
I tested. It works. Thank you so much..
