### ISSUE TITLE
Cursor invisible when renaming file in Caja (Mate)

### ISSUE THREAD

**Issue by ColdBooted** [nana-4/materia-theme#398]
This partains to Linux Mint 19.1 Mate with the version provided in the official repo. When renaming a file in Caja file manager, the cursor is invisible. There's no such problem with themes provided by the Mint team.
 
![Screenshot at 2019-06-09 15-39-14](https://user-images.githubusercontent.com/14140205/59159620-d3a0c100-8acc-11e9-86f6-93af72342f3b.png)

**Comment by nana-4** [comment]
Thanks for your report.

I'll investigate and fix it.
