### ISSUE TITLE
[Bug] Invisible border when selecting area to take screenshot in gnome-screenshot

### ISSUE THREAD

**Issue by ceyhunn** [nana-4/materia-theme#399]
**Reporter Info**

- Materia version: latest git
- GTK3 version: 3.24.8
- Distribution (and version): Manjaro Stable Branch
- Desktop environment (and version): Gnome 3.32.2
- Related application (and version): Gnome-Screenshot 3.32.0

**Actual Issue**
In gnome-screenshot I can't see which area is selected to take screenshot, because of invisible border.

**Steps to Reproduce**

1. Open Gnome Screenshot
2. Select area to grab
3. Take screenshot

**Additional Info**

**Comment by nana-4** [comment]
I can't reproduce it. The border is visible in my environment: Fedora 30; GNOME 3.32.2 on Xorg; gnome-screenshot 3.32.0.

What happens with Adwaita?

**Comment by ceyhunn** [comment]
Strange is that It also reproduced in Adwaita. It is not related to Materia. Sorry for wasting your time.

**Comment by nana-4** [comment]
I'm guessing you did _click_ instead of _drag-and-drop_ to select area :)

**Comment by ceyhunn** [comment]
Of course no :)). Seems like driver bug. I will test it in Wayland.

**Comment by nana-4** [comment]
@ceyhunn In case you were applying the Materia GDM theme, #422 was the cause. Sorry for the inconvenience.

**Comment by ceyhunn** [comment]
Yes, I use Materia gdm theme. Thank you for the info. I will test.
