### ISSUE TITLE
Metacity theme uses undefined variable

### ISSUE THREAD

**Issue by vladimir-didenko** [nana-4/materia-theme#400]
**Reporter Info**

- Materia version: latest master
- GTK3 version: 3.24.8
- Distribution (and version): Alt Linux Sisyphus
- Desktop environment (and version): Cinnamon 4.0

**Actual Issue**

Metacity theme (file metacity-1/metacity-theme-3.xml) uses variable "wm_unfocused_bg"
```
<constant name="C_titlebar_unfocused" value="gtk:custom(wm_unfocused_bg,gtk:bg[NORMAL])"/>
```
but this variable is not defined in gtk-3.0/gtk.css. Note that this variable mentioned in src/_sass/gtk/_colors-public.scss.

**Comment by nana-4** [comment]
Yeah, for some reasons I have not regenerated the CSSs yet in master. I will push the regenerated CSSs when the work in progress is done.

Thanks for reporting the issue anyway :)
