### ISSUE TITLE
Better Stylizing Budgie panel status icons.

### ISSUE THREAD

**Issue by SaucySauce** [nana-4/materia-theme#403]
As it stands right now Budgie's panel end region icons are set too close to one another and also inconsistently. 
I suggest increasing the padding or borders of each applet individually (the ones provided by the desktop and also the ones provided by the Budgie Applets section of Budgie's Welcome screen) to something more akin to Cinnamon dimensions or even GNOME shell ones. I can try to help out but Github is still new to me and git commands are a mess for me still.

**Comment by nana-4** [comment]
Can you provide some screenshots or paste the SCSS/CSS code you changed?

I'm still not exactly sure what kind of things you image.

**Comment by SaucySauce** [comment]
Truly sorry for the late reply. This is what I mean.
![Screenshot from 2019-06-25 22:53:20](https://user-images.githubusercontent.com/38703177/60139112-2f8d6a00-979c-11e9-86d6-e55d718b7eb5.png)

**Comment by SaucySauce** [comment]
There is a clear lack of sizing standards, I'm not sure who's to blame.
I've tried doing some changes to the border and padding values of several applets in the _budgie.scss and compiled them again, to no affect.

**Comment by SaucySauce** [comment]
As you can see the battery icon is far too close to the volume icon.

**Comment by hrdwrrsk** [comment]
According to budgie-desktop latest git version, it's possible to style these "icon indicators" padding via `.icon-popover` class, but for retaining backward compatibility with current stable version of budgie-desktop, 'hacky' classes needs to used. [plata-theme](https://gitlab.com/tista500/plata-theme) (Adapta's successor) uses this way:

```
.end-region > widget > widget {
  > box.horizontal { // 'Stats Indicator'
    > widget > widget > image { // 'bluetooth'
      &:dir(ltr) { margin: 0 2px 0 -1px; }
      &:dir(rtl) { margin: 0 -1px 0 2px; }
    }

    > widget.sound-applet > widget > image { // 'sound'
      min-width: $icon_size + 2px;
      margin: 0;
    }

    > widget > widget > box.horizontal > image,
    box.battery-icon.horizontal > image { // 'battery'
      min-width: $icon_size + 6px;
    }
  }

  box.battery-icon { // 'percent label'
    &.horizontal > label.percent-label {
      &:dir(ltr) { margin: 0 -6px 0 3px; }
      &:dir(rtl) { margin: 0 3px 0 -6px; }
    }

    &.vertical > label.percent-label {
      font-size: 75%;
      &:dir(ltr) { margin-right: -2px; }
      &:dir(rtl) { margin-left: -2px; }
    }
  }

  > image { // 'Notification' and 'User Indicator'
    min-width: $icon_size + 4px;
  }
}
```

I'm also suggests that whole budgie-desktop styling also needs a rework/visual change, especially Raven header widget to match with Headerbar ones, and support for new icon tasklist
