### ISSUE TITLE
[Accessibility] Update primary color for light variants

### ISSUE THREAD

**Issue by nana-4** [nana-4/materia-theme#404]
I've been feeling that the current primary color for light variants (`#4285F4`) is sometimes a bit too bright. Especially it's noticeable where the color is used for text.

![image](https://user-images.githubusercontent.com/9556384/60013395-5757d180-96b9-11e9-96b0-9db2745ff104.png)
![image](https://user-images.githubusercontent.com/9556384/60013426-69d20b00-96b9-11e9-8a20-ae03769b09d5.png)
![image](https://user-images.githubusercontent.com/9556384/60013346-32635e80-96b9-11e9-9cba-f1f472eb95a6.png)

The contrast ratio between `#4285F4` and `#FFFFFF` is [3.56:1](https://contrastchecker.com/?c=4285F4&b=FFFFFF
). It doesn't pass the  WCAG's passing score 4.5:1 which [Material Design recommends](https://material.io/design/color/text-legibility.html#legibility-standards).

We probably need a little darker primary color. Ideally it should pass the WCAG's level AA.

**Comment by nana-4** [comment]
I have 2 colors that I'm considering as a candidate:

1.  `#1A73E8`

![image](https://user-images.githubusercontent.com/9556384/60021442-005bf780-96cd-11e9-9e37-13271690c0b9.png)

- The contrast ratio is [4.51:1](https://contrastchecker.com/?c=1A73E8&b=FFFFFF
).
- Used in many Google products.
- Might be too dark/vivid?

2. `#3B78E7`

![image](https://user-images.githubusercontent.com/9556384/60021358-d6a2d080-96cc-11e9-8b2d-0231826d4895.png)

- The contrast ratio is [4.18:1](https://contrastchecker.com/?c=3B78E7&b=FFFFFF
).
- Softer than the above.
- Doesn't pass the WCAG level AA.

I'm leaning toward the former, because it passes Level AA.

**Comment by m-thorsen** [comment]
`#1A73E8` is "pixel blue", right?   
It's got my vote (for what it's worth)

**Comment by mjfa12** [comment]
I also like #1A73E8, again for what it's worth. Thank you for your work.

**Comment by 1612180** [comment]
I also like #1A73E8. It makes blue so blue :)

**Comment by nana-4** [comment]
Thanks for your feedback! I've changed the primary color to `#1A73E8` in master :)

By the way, this is not a final decision. If I got many complaints about the new primary color, I will consider another color :) So I'm going to keep this issue open for a while.

**Comment by mjfa12** [comment]
> Thanks for your feedback! I've changed the primary color to `#1A73E8` in master :)
> 
> By the way, this is not a final decision. If I got many complaints about the new primary color, I will consider another color :) So I'm going to keep this issue open for a while.

Thank you for your work.  I was surprised to hear there were complaints with the new primary color.  However, when I switched to the Dark Theme version I can see how some may find it too bland.  Of course this may have more do to with the transparency effect then the color itself. I look forward to seeing where you take things in the future.  Thanks again.

**Comment by PJSingh5000** [comment]
I'm obviously in the minority here, so I'll share my thoughts...

#1A73E8 is a great color. But it seems a bit too "cartoonish" and reminds me of the blue used in Windows 95; in other words, it doesn't feel very sophisticated.

Are there any other options to meet the 4.5:1 contrast ratio requirement, but still have a more professional or refined look?

(As always, I truly appreciate all the hard work put into this wonderful theme!).

**Comment by nana-4** [comment]
@PJSingh5000 Thanks for your feedback.

I opened this issue because of concerns similar to yours :)

At first I felt `#1A73E8` is a bit too strong and could be annoying. However after using it for a few weeks, I became very happy with it. Now it looks more professional and refined look to me.

I personally have relatively good eyesight, but that color benefited even me: It made it easier to work away from display. And I have less to bring my face close to the display.

It's probably a matter of getting used to it, I guess.

**Comment by nana-4** [comment]
Contrary to my expectation, there was little or nothing objection against this change.

Again, I'm very happy with this change - it's much easier to see 🙂

 So I'm going to close this issue.
