### ISSUE TITLE
Reducing roundness of windows?

### ISSUE THREAD

**Issue by Boolicious** [nana-4/materia-theme#406]
**Reporter Info**

- Materia version: 20190315
- GTK3 version: 3.24.9
- Distribution (and version): Arch Linux
- Desktop environment (and version): Cinnamon 4.2.0
- Related application (and version): None in particular

**Description**
Can the roundness at the top corners of windows be slightly reduced? I'm personally fine with the roundness itself but it seems inconsistent with the sharp edges at the bottom corners, especially with small windows. Or maybe figure out a way to make the bottom corners round as well?

**Comment by nana-4** [comment]
Hi,

> Can the roundness at the top corners of windows be slightly reduced?

Yes, but you'll need to edit the CSS and XML files as follows:

#### GTK's CSS

1. Open `/usr/share/themes/Materia/gtk-3.0/gtk.css` and  `/usr/share/themes/Materia/gtk-3.0/gtk-dark.css` in your text editor.
2. Search `.background .titlebar`.
3. Change the `4px` of [this highlighted part](https://github.com/nana-4/materia-theme/blob/v20190315/src/gtk/3.0/gtk.css#L1483-L1511) to your preferred radius (e.g. `2px`).

#### Metacity's XML

1. Open `/usr/share/themes/Materia/metacity-1/metacity-theme-2.xml` and  `/usr/share/themes/Materia/metacity-1/metacity-theme-3.xml` in your text editor.
2. Change the `4` of [this](https://github.com/nana-4/materia-theme/blob/v20190315/src/metacity-1/metacity-theme-2.xml#L22) & [this](https://github.com/nana-4/materia-theme/blob/v20190315/src/metacity-1/metacity-theme-2.xml#L76) to your preferred radius (e.g. `2`).

> Or maybe figure out a way to make the bottom corners round as well?

Unfortunately, there is no way to do it completely (unless GTK will support the CSS `overflow` property).

**Comment by nana-4** [comment]
And I'm not going to reduce the roundness in this theme, sorry.

**Comment by Boolicious** [comment]
I see, thanks for responding.
