### ISSUE TITLE
sassc compilation error: "compound selectors may no longer be extended."

### ISSUE THREAD

**Issue by wimstefan** [nana-4/materia-theme#407]
- Materia version: git 51e440a3
- GTK3 version: 3.24.10
- sassc: 3.6.1
- libsass: 3.6.1-15-g0f3d6
- sass2scss: 1.1.1
- sass: 3.5

Running `change_color.sh` throws the following error:
```sh
== Light background color detected. Setting color variant to light.
== Converting theme into template...
== Filling the template with the new colorscheme...
== Generating the CSS...
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
```

**Comment by nana-4** [comment]
I cannot reproduce this.

My `sassc` version is:

```bash
$ sassc --version
sassc: [NA]
libsass: 3.5.4
sass2scss: 1.1.1
sass: 3.5
```

Can you provide the command you input? (Possibly your command was wrong.)

**Comment by nana-4** [comment]
Also, could you please check if you get the same error by running `./parse-sass.sh`?

**Comment by wimstefan** [comment]
I've tried to compile my own theme as I always did with 
`./change_color.sh -o ta-materia-light-blue-2 ~/.config/oomox/colors/ta-materia-light-blue`

But the example command you gave in the --help gave me the same error:
`./change_color.sh -o my-theme-name <(echo -e "ROUNDNESS=0\nBG=d8d8d8\nFG=101010\nHDR_BG=3c3c3c\nHDR_FG=e6e6e6\nSEL_BG=ad7fa8\nMATERIA_VIEW=ffffff\nMATERIA_SURFACE=f5f5f5\nMATERIA_STYLE_COMPACT=True\n")`

Running `./parse-sass.sh` throws *exactly* the same error. Might be the slightly higher sassc version? I'm using the live ebuild on a Gentoo system ...

**Comment by wimstefan** [comment]
OK going back to dev-lang/sassc-3.6.0 solved the problem as far as I can tell :-)
```sh
sassc: na
libsass: 3.6.0
sass2scss: 1.1.1
sass: 3.5
```
Thank you so much for your time going into that issue and all the efforts for making such a great theme! :-D 👍🏽

**Comment by nana-4** [comment]
Thanks for providing the detailed info :smiley: 

TBH, I'm still not sure if this is a bug or an intentional change in the newer version of sassc/libsass. But if this will happen with even newer versions, I'll try to fix the error... ;)

**Comment by nana-4** [comment]
Okay. Apparently this is an intentional change [in Sass](http://bit.ly/ExtendCompound), and is unlikely to be reverted. (Still it's strange to me that they added the **breaking change** into the patch release, though.)

So, we will need to update our SCSS code drastically to deal with this... :man_facepalming: 

I'm going to reopen this.
