### ISSUE TITLE
White line drawn in image zoom percentage box of eog

### ISSUE THREAD

**Issue by torqueyy** [nana-4/materia-theme#410]
**Reporter Info**

- Materia version: https://github.com/nana-4/materia-theme/commit/7f84b1aacb20c37f25269263e32b63aeb71bab89
- GTK3 version: 3.24.10
- Distribution (and version): Fedora 30
- Desktop environment (and version): GNOME 3.32.2
- Related application (and version): Eye of GNOME - `eog` 3.32.2

**Actual Issue**

The text box showing the zoom amount in Eye of GNOME contains a white line cutting off the percentage symbol with Materia. With Adwaita, this issue is not repeated.

**Materia current**

![eog-materia](https://user-images.githubusercontent.com/40131158/61210769-a2fa1a00-a751-11e9-80bb-f7873d5c3ef7.png)

**Adwaita current**

![eog-adwaita](https://user-images.githubusercontent.com/40131158/61210781-a9889180-a751-11e9-9bb2-ed7319938c6e.png)

**Comment by nana-4** [comment]
I cannot reproduce this with the exact same GTK/Distro/DE/App versions as yours.

This may be related to the font. What font and font-size are you using?

**Comment by nana-4** [comment]
For reference, that dashed line is called `undershoot` and draws the underflow indications. In the refreshed Adwaita, that style has been removed due to the [issue](https://gitlab.gnome.org/GNOME/gtk/issues/1591).

**Comment by torqueyy** [comment]
> I cannot reproduce this with the exact same GTK/Distro/DE/App versions as yours.
> 
> This may be related to the font. What font and font-size are you using?

Thanks for the info on the undershoot.

The font in the screenshot is Source Sans Pro Regular at size 11. Roboto, Cantarell and Overpass all display without the undershoot, so it must be a font-specific issue. Do you think it's worth filing a bug with the font maintainer for Fedora?

**Comment by nana-4** [comment]
Thanks for the info. I now can reproduce this with Source Sans Pro :)

> Do you think it's worth filing a bug with the font maintainer for Fedora?

I'm not sure... but _if_ it's worth filing a bug, I think it should be to the `eog` maintainer, not to the font maintainer -  because the entry width is determined by `eog` programmatically.
