### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by 354651432** [nana-4/materia-theme#416]
unbound variable

**Reporter Info**
./install.sh: line 231: colors: unbound variable

- Materia version:  git cloned
- GTK3 version: 
- Distribution (and version):  centos 7
- Desktop environment (and version): 
- Related application (and version):

**Comment by moukoublen** [comment]
Same issue here.
I attempted to solve it with this:
https://github.com/nana-4/materia-theme/pull/417

**Comment by 354651432** [comment]
@moukoublen  it works ,thanks
