### ISSUE TITLE
[Feature request] Remove the dotted lines

### ISSUE THREAD

**Issue by Aurnytoraink** [nana-4/materia-theme#421]
I think the dotted lines look horrible and break the material design experience.
Here is a comparison:

with:
![Capture d’écran du 2019-08-22 15-47-19](https://user-images.githubusercontent.com/28545669/63519988-34e50780-c4f4-11e9-8188-d05f6bc0a2ba.png)

without:
![Capture d’écran du 2019-08-22 15-47-19(2)](https://user-images.githubusercontent.com/28545669/63520694-6f9b6f80-c4f5-11e9-9268-f4a2588317b5.png)

**Comment by ceiphr** [comment]
If possible, could we get a flag in the installation script to remove the dotted lines or even a separate variant of the theme without them?

Also is it possible to remove the dotted lines with Oomox?
