### ISSUE TITLE
The GDM theme makes gnome-screenshot selected area invisible

### ISSUE THREAD

**Issue by leomao** [nana-4/materia-theme#422]
**Reporter Info**

- Materia version: 20190315 or master
- GTK3 version: 3.24.10
- Distribution (and version): Archlinux  (latest update)
- Desktop environment (and version):  gnome-shell 3.32.2+11+g1c6abf378-1
- Related application (and version): gnome-screenshot 3.32.0

**Actual Issue**

When using the default GDM theme, we can get a blue rectangle preview for the selected area after pressing Shift+Print.  But after changing the GDM theme to Materia (following [the instruction](https://github.com/nana-4/materia-theme/blob/master/src/gnome-shell/README.md)), the selected area will be invisible.  Still can take the screenshot though.

**Steps to Reproduce**

1. Use the default GDM theme, press Shift+Print, draw a rectangle and verify that the selected area preview is visible.
2. Change the GDM theme to Materia (or any variant).
3. follow 1. and the area preview is invisible now.

**Comment by nana-4** [comment]
Oh... Apparently I missed adding that style 😖

Thanks for your report!
