### ISSUE TITLE
White lines in MATE panel

### ISSUE THREAD

**Issue by pedrofleck** [nana-4/materia-theme#425]
**Reporter Info**

- Materia version: 20180321-1 (distro default version) and 20190201-5 (ppa version)
- GTK3 version: 3.22
- Distribution (and version): Linux Mint 19.2
- Desktop environment (and version): MATE 1.22
- Related application (and version): mate-panel

**Actual Issue**

There are [white lines](https://i.imgur.com/B2x3MM8.png) next to separators in MATE panel that doesn't appear in other themes.

**Comment by nana-4** [comment]
IIRC this was intentional, but it could look better.

I'll investigate that. Thanks for the report.

**Comment by pedrofleck** [comment]
I didn't think it was intentional because the lines are not present on Gnome shell or Xfce and there are no equivalent in other themes for 2 of the 3 lines.

**Comment by nana-4** [comment]
Okay. I ended up with this dots design:

![image](https://user-images.githubusercontent.com/9556384/68729356-1bdc8600-060d-11ea-916d-5e6cc8044ff5.png)

**Comment by pedrofleck** [comment]
Sorry for the long time to answer. The issue is still present here, I tried last week with the latest git version. Did you tried with the latest MATE?

**Comment by nana-4** [comment]
@pedrofleck Sorry, in the latest git, CSSs are not regenerated yet. To test it, you need to run `./parse-sass.sh` before running `./install.sh`.
