### ISSUE TITLE
Add better support for HiDPI font scaling

### ISSUE THREAD

**Issue by alvaro-munoz** [nana-4/materia-theme#428]
Hi, I'm using your theme with a HiDPI monitor (2560x1440) and the default fonts are small in comparison with the system fonts I've set. I know that I can change them manually on the .css but if a "better" solution gets implemented that would be awesome.

**Comment by nana-4** [comment]
Please, follow the [issue template](https://github.com/nana-4/materia-theme/issues/new?assignees=&labels=&template=bug_report.md&title=).

(From your report I have no idea what desktop environment you are using.)

**Comment by alvaro-munoz** [comment]
Sorry about that.


**Reporter Info**


- Materia version: 20190831-1 (per pacman info)
- GTK3 version: 3.24.10
- Distribution (and version): Arch Linux (5.2.11.arch1-1)
- Desktop environment (and version): GNOME 3.32.0-1
- Related application (and version): 

**Actual Issue**

The font used by default (M+ if I'm not mistaken) appears too small.
![Screenshot from 2019-09-04 19-43-45](https://user-images.githubusercontent.com/34600352/64281851-5adac500-cf54-11e9-8822-416c618e7a9c.png)
![Screenshot from 2019-09-04 19-43-55](https://user-images.githubusercontent.com/34600352/64281863-629a6980-cf54-11e9-860d-de1bc42f460f.png)
![Screenshot from 2019-09-04 19-44-19](https://user-images.githubusercontent.com/34600352/64281864-64fcc380-cf54-11e9-9b78-ad38871d82c9.png)
It would be great if the system font and the shell font where matching, but at least the size should be similar.

**Additional Info**

I'm using GNOME on Xorg with 2.0x scaling.

**Comment by nana-4** [comment]
Thanks for your clear report :) I'll check that.

**Comment by nana-4** [comment]
Hmm, I couldn't reproduce this... In my environment, the shell font is properly scaled to 200%.

Does this issue happen even with the _default_ gnome-shell theme?

**Comment by alvaro-munoz** [comment]
You are correct, it was my fault.
I've set `GDK_SCALE=2` and `GDK_DPI_SCALE=0.5` because I'm also using other window managers that don't scale the applications. `GDK_DPI_SCALE` was the one at fault.

Sorry for the inconvenience.
