### ISSUE TITLE
Bugged header bar with GNOME Tweaks

### ISSUE THREAD

**Issue by torqueyy** [nana-4/materia-theme#432]
**Reporter Info**

- Materia version: v20190912
- GTK3 version: 3.24.11
- Distribution (and version): Fedora 31
- Desktop environment (and version): GNOME 3.34
- Related application (and version): GNOME Tweaks 3.33.90

**Actual Issue**

The header bar in GNOME Tweaks using the Fedora 31 Beta with all updates applied is completely black with jagged corners. This occurs using all variants, including compact ones. It does not occur using Adwaita or another theme (in this case, Qogir).

**Comment by nana-4** [comment]
Thanks for your report. I've confirmed this problem.

I'm pretty sure this is due to some upstream bug, not our failure. (In fact, in Adwaita, the top left border-radius is broken when the window width is narrowed.) But I will add some workaround :)

**Comment by nana-4** [comment]
Just as a supplement: A similar problem exists even with Adwaita. See:

https://gitlab.gnome.org/GNOME/gnome-tweaks/issues/236
https://gitlab.gnome.org/GNOME/gnome-tweaks/issues/238

**Comment by torqueyy** [comment]
Thanks for looking into it! It must be frustrating to have so many upstream changes mess with the beautiful look of Materia.
