### ISSUE TITLE
install.sh: Wrong version of gnome-shell theme installed with Docker

### ISSUE THREAD

**Issue by nana-4** [nana-4/materia-theme#434]
Re: https://github.com/nana-4/materia-theme/issues/433#issuecomment-535131936

**Comment by nana-4** [comment]
(Just copied from https://github.com/nana-4/materia-theme/issues/433#issuecomment-535418364:)


@Ghostium 

> I always thought that the install.sh script copies every version and gnome just picks the right folder,

Regarding GTK themes, that's true. But gnome-shell uses [St toolkit](https://developer.gnome.org/st/) instead of GTK, and it doesn't support versioned theme folders. So we need to pick a proper version of gnome-shell theme in the script.

> I build materia-theme in a Docker container so the gnome-shell package is not installed and the version can't be derived defaulting to $LATEST_GS_VERSION.

Sorry I'm not familiar with Docker, so I may be wrong something but: Does that mean you have installed gnome-shell in the OS directly, not in the Docker container? If so, why don't you build materia-theme in both OS (for gnome-shell & gdm) and the Docker container (for GTK apps)? 

> so I just run sed in my .spec file

Can you show me all the code/description in your .spec file? Then I can understand more background :)

**Comment by Ghostium** [comment]
> Sorry I'm not familiar with Docker, so I may be wrong something but: Does that mean you have installed gnome-shell in the OS directly, not in the Docker container? 

Yes I installed Gnome only in my desktop system. The RPM package is built every 24h following the latest commit master in a CI Docker container (hence no GUI) and uploaded to my repository. My desktop and laptop system run both dnf-automatic so changes get integrated no later than 24h after the package was built.

Here is my spec:
```spec
%global commit %(git ls-remote https://github.com/nana-4/materia-theme refs/heads/master | cut -c1-40)
%define projectdirname %name-%version
%define projectdir %{_builddir}/%projectdirname
%define build_timestamp %(date -u +"%Y%m%d%H%M")

%define projectdirname %name-%version
%define projectdir %{_builddir}/%projectdirname

Name:           materia-gtk-theme
Version:        20190912
Release:        3%{build_timestamp}git%{commit}%{?dist}
Summary:        A Material Design-like theme for GNOME/GTK+ based desktop environments

License:        GPLv2
URL:            https://github.com/nana-4/materia-theme

BuildArch:      noarch
BuildRequires:  bash
BuildRequires:  bc
BuildRequires:  sassc
BuildRequires:  git
Requires:       %{_bindir}/glib-compile-resources
Requires:       %{_datadir}/gtk-engines/murrine.xml
Requires:       gnome-themes-extra

%description
Materia is a Material Design theme for GNOME/GTK based desktop environments.
It supports GTK 2, GTK 3, GNOME Shell, Budgie, Cinnamon, MATE, Unity, Xfce, LightDM, GDM, Chrome theme, etc.

%prep
rm -rf %{projectdir} || true
mkdir %{projectdir}
cd %{projectdir}
git init
git remote add origin https://github.com/nana-4/materia-theme
git fetch --depth 1 origin %{commit}
git checkout FETCH_HEAD

%install
rm -rf $RPM_BUILD_ROOT
cd %projectdir
./parse-sass.sh
sed -i 's/\${GS_VERSIONS\[-1\]}/3.32/g' install.sh
./install.sh --dest %{buildroot}/%{_datadir}/themes

%files
%license %projectdirname/COPYING
%doc %projectdirname/README.md
%{_datadir}/themes/*

%changelog
```

**Comment by nana-4** [comment]
Ah, I misunderstood something.

Adding `sed` solved your problem for now, right? Then why do you think it's better to set `$GS_VERSION` as an environment variable than to run `sed`?

Initially I thought it's fixable by simply modifying `install.sh`. However if you use CI, `install.sh` won't be able to automatically determine your gnome-shell version through CI, I guess.

**Comment by Ghostium** [comment]
The sed solution works fine, but is hacky.

I would like to set $GS_VERSION as an env variable however $GS_VERSION is always overshadowed. A simple 'if' would help to check if $GS_VERSION is already defined.
Like this:
```patch
diff --git a/install.sh b/install.sh
index cc67147a..2e4ec4d8 100755
--- a/install.sh
+++ b/install.sh
@@ -14,21 +14,22 @@ GTK_VERSIONS=('3.0')
 GS_VERSIONS=('3.18' '3.24' '3.26' '3.28' '3.30' '3.32' '3.34')
 LATEST_GS_VERSION="${GS_VERSIONS[-1]}"
 
-# Set a proper gnome-shell theme version
-if command -v gnome-shell >/dev/null; then
-  CURRENT_GS_VERSION="$(gnome-shell --version | cut -d ' ' -f 3 | cut -d . -f -2)"
-  for version in "${GS_VERSIONS[@]}"; do
-    if (( "$(bc <<< "$CURRENT_GS_VERSION <= $version")" )); then
-      GS_VERSION="$version"
-      break
-    else
-      GS_VERSION="$LATEST_GS_VERSION"
-    fi
+if test -z "$GS_VERSION"; then
+  # Set a proper gnome-shell theme version
+  if command -v gnome-shell >/dev/null; then
+    CURRENT_GS_VERSION="$(gnome-shell --version | cut -d ' ' -f 3 | cut -d . -f -2)"
+    for version in "${GS_VERSIONS[@]}"; do
+      if (( "$(bc <<< "$CURRENT_GS_VERSION <= $version")" )); then
+        GS_VERSION="$version"
+        break
+      else
+        GS_VERSION="$LATEST_GS_VERSION"
+      fi
   done
-else
-  GS_VERSION="$LATEST_GS_VERSION"
+  else
+    GS_VERSION="$LATEST_GS_VERSION"
+  fi
 fi
-
 usage() {
   cat << EOF
 Usage: $0 [OPTION]...
```

**Comment by nana-4** [comment]
OK, I will change the script as you suggested then :)
