### ISSUE TITLE
Activities View Close Button GNOME Issue

### ISSUE THREAD

**Issue by SubhamSatyajeet** [nana-4/materia-theme#435]
**Reporter Info**
- Materia version: 20190201-1ubuntu2
- GTK3 version: 3.32.2
- Distribution (and version): Ubuntu 19.04
- Desktop environment (and version): Gnome
- Materia Theme, Materia-dark Shell Theme

**Actual Issue**

The close buttons for open apps in the Activies View are buggy and asymmetrical.

1) The regular close button looks as if there are two icons superimposed on each other; the first layer being dark blue and the inside layer having a red background with a white cross on it. 
2) The close button, on hover, changes the colour of the first layer to white, and the layer looks hand-drawn.
(Zoom in on the provided images to notice).

**Close Button**

![image](https://user-images.githubusercontent.com/7932787/66265313-1e8bd480-e832-11e9-8b8e-0aa16dfc04b1.png)

**Close Button (on hover)**

![image](https://user-images.githubusercontent.com/7932787/66265319-40855700-e832-11e9-8286-5376fb7b41f7.png)

**Comment by nana-4** [comment]
Thanks for your report.

This is due to the Ubuntu Disco repository distributes an outdated version of the `materia-gtk-theme` package. The version `20190201` doesn't support gnome-shell 3.32.

I reported the problem to the Ubuntu side:
https://bugs.launchpad.net/ubuntu/+source/materia-gtk-theme/+bug/1846934

Let's wait for the response from the Ubuntu package maintainers...

Alternatively, you can solve the problem by [manually installing the theme](https://github.com/nana-4/materia-theme#manual-installation).

**Comment by SubhamSatyajeet** [comment]
@nana-4 Thanks for replying! Also, if possible, can you distribute the theme using a Personal Package Archive (PPA) for distributions that use apt (such as Ubuntu)?

That way, you would not have to depend on the Ubuntu package maintainers for updating the package, and users would have access to the latest version of the theme as soon as it is published.

**Comment by SubhamSatyajeet** [comment]
@nana-4 I understand.

I don't think Ubuntu package maintainers are expected to update packages any sooner than 6 months. (That's the best-case scenario). Getting a maintainer to pay attention to your launchpad bug request is often hard and time-consuming.

That being said, the install script works flawlessly. Kudos to you for that.

**Comment by nana-4** [comment]
> I don't think Ubuntu package maintainers are expected to update packages any sooner than 6 months. (That's the best-case scenario). Maintainers usually don't pay attention to launchpad bug requests asking for software updates.

Thanks for the info. I didn't know that :)

Well, I'll reconsider about distributing with PPA.
