### ISSUE TITLE
Materia Shell - Workspaces Preview panel flicker issue

### ISSUE THREAD

**Issue by SubhamSatyajeet** [nana-4/materia-theme#437]
**Reporter Info**

- Materia version: v20190912
- GTK3 version: 3.24.8
- Distribution (and version): Ubuntu 19.04
- Desktop environment (and version): Gnome
- Materia GTK theme, Materia Gnome Shell theme 

**Issue**
When in the activities view, moving the mouse to the right edge of the screen (just past the 2 workspace previews) causes flickering of the workspaces preview sidebar.

Please see GIF for reference:
![Peek 2019-10-10 11-05](https://user-images.githubusercontent.com/7932787/66542073-2360c900-eb4f-11e9-8415-85b18c963d09.gif)

(Sorry about the low framerate in GIF)

**Comment by nana-4** [comment]
I can't reproduce it.

Does it really only happen with Materia theme? What happens with the _default_ gnome-shell theme?

**Comment by SubhamSatyajeet** [comment]
In the default Gnome Shell theme, the cursor moves to the right edge, and the workspace preview pane pops out from the right side **once**. This is true even if the mouse pointer stays on the right side edge.

This is also true in other Shell Themes (I've tried Arc and Pop).

In Materia Shell Theme, the preview pane starts to go back and forth, as shown in the GIF.

Try this:
1) Place the mouse pointer at the left hand side of the first workspace preview (the upper box among the two boxes you see at the workspace preview pane. The workspace preview pane is the pane on the right, which is automatically hidden by default)
2) Mouse your mouse toward the right until it touches the right edge of the screen. Stop after that.

Is your preview pane repeating the "reveal by sliding toward the right" animation, as shown in the GIF?

**Comment by SubhamSatyajeet** [comment]
@nana-4 I tried it on a fresh install of Ubuntu 19.04 and Gnome Shell 3.32.2. I **can't** reproduce it. Tried after disabling all extensions except user themes, and the problem persists on my machine.

The issue is specific to my setup - I'm not sure where the issue is coming from.

I'm closing the bug report. Sorry about this!

**Comment by nana-4** [comment]
No worries :smile: Thanks for your contribution :)
