### ISSUE TITLE
Add Ubuntu PPA

### ISSUE THREAD

**Issue by gargullia** [nana-4/materia-theme#44]
Add please repository for Ubuntu or allow to become a maintainer

**Comment by mbirth** [comment]
Maybe @hotice can help here…

**Comment by actionless** [comment]
btw Materia theme deb package is also available as part of oomox app: https://github.com/actionless/oomox#ubuntu (but the exported theme will be available only for the current user)

**Comment by nana-4** [comment]
@mbirth For now I'm waiting for @isaagar to finish his work (#164)... The package for Debian would work on Ubuntu as well.

@actionless Thanks for your work.

**Comment by Moulick** [comment]
Having a ubuntu PPA would be awesome

**Comment by igor-dyatlov** [comment]
@nana-4 created a repository. In beta status. Publishes packages for Bionic, Artful, and Xenial.

`sudo add-apt-repository ppa:dyatlov-igor/materia-theme`
`sudo apt update`
`sudo apt install materia-theme`

**Comment by nana-4** [comment]
@igor-dyatlov Great! Thank you very much!! I've added your PPA/commands to the README. (Please let me know if you have any issues.)

BTW, I'm not very sure but if the debian package (#164) becomes available, I may replace it from the README. :)

**Comment by igor-dyatlov** [comment]
@nana-4 I'm also waiting for the debian package from @isaagar, because then the repository will be useless. And I will stop supporting.

**Comment by nana-4** [comment]
@igor-dyatlov I agree with you. Thanks for your support, btw.
