### ISSUE TITLE
libglib2.0-dev-bin required for GDM theme on Debian

### ISSUE THREAD

**Issue by loicreynier** [nana-4/materia-theme#440]
I am running on Debian Buster with GNOME desktop 3.30.2 and GTK 3.24.5 and I couldn't install the GDM theme without installing the `libglib2.0-dev-bin` package. `./install.sh -g` couldn't succeed because the `glib-compile-resources` was not found. According to this [issue](https://github.com/juhaku/loginized/issues/3) the latter used to be provided by the `libglib2.0-bin` package which is installed by default. But now the `libglib2.0-dev-bin` package is required so I guess you should add it as a requirement at least for Debian based system. 

Thank you for your great work!

**Comment by nana-4** [comment]
Thanks for your feedback!

In [`gnome-shell/README.md`](https://github.com/nana-4/materia-theme/blob/master/src/gnome-shell/README.md) we already describe the Requirements for Debian, so I think it would be enough to prompt users to see the README file.

Also I'll change `libglib2.0-dev` to `libglib2.0-dev-bin` in the README, as the package seems much lighter ;)
