### ISSUE TITLE
Global-search results in Builder has a poor visibility

### ISSUE THREAD

**Issue by monday15** [nana-4/materia-theme#442]
Hey, @nana-4, please note, that I dont use Builder or Materia - I also maintain a theme with light selection background. I couldn't find a legit solution, may be you have an idea how to fix this. This is like very low priority bug. And thanks for a well-maintained/documented theme!

Here is how Global search in Builder 3.34 looks (flatpak).  
![b1](https://user-images.githubusercontent.com/42862490/68091316-01353f00-fea0-11e9-9371-232ff4b897d3.png)

Text color is hardcoded somewhere in builder, I could only found out that this is `revealer row.activatable:selected` - search "thing" is not clickable/visible with Inspector. Also, this revealer is not a part of 'window'. Ended up with adding a style for `revealer row.activatable` and right after then overriding it with `window revealer row.activatable` (so it doesn't affect other apps [i hope so], for example, fractal's sidebar). It should be a cleaner solution for the issue.

Also, noticed two minor issues: with regular Materia search icon in headerbar is invisble; key combination color in tooltip looks wierd.
![b4](https://user-images.githubusercontent.com/42862490/68091547-f7610b00-fea2-11e9-8f75-3bd18325cdf8.png)

**Comment by nana-4** [comment]
Thanks for your report and investigation!

> Text color is hardcoded somewhere in builder

Yeah, I found the CSS in [libdazzle](https://gitlab.gnome.org/GNOME/libdazzle/blob/master/data/themes/shared/shared-suggestions.css#L31-33) repo :)

> Ended up with adding a style for revealer row.activatable and right after then overriding it with window revealer row.activatable (so it doesn't affect other apps [i hope so], for example, fractal's sidebar).

Since the `color` is (unnecessarily) hard-coded, I think overriding it doesn't work in `gtk.css` (i.e. themes), even if it works in the Inspector. Instead we can style a darker `background-color` for it, though.

> with regular Materia search icon in headerbar is invisble

I'll try to add a workaround. (But maybe it should be fixed in the upstream, because that white background doesn't look great even with Adwaita IMO...)

> key combination color in tooltip looks wierd.

Thanks, I'll fix that :)

**Comment by monday15** [comment]
> Since the color is (unnecessarily) hard-coded, I think overriding it doesn't work in gtk.css (i.e. themes), even if it works in the Inspector. Instead we can style a darker background-color for it, though.

Yep, changing color doesn't work, I've changed background-color.

> I'll try to add a workaround. (But maybe it should be fixed in the upstream, because that white background doesn't look great even with Adwaita IMO...)

I read (somewhere in commit messages) that developers want to make this button more entry-like, that's why it has weird look/style.

Many thanks for libdazzle link with that widget "address"! Exactly what I was looking)

p.s.: One more thing - Polari app has similar behaviour in sidebar - color is hardcoded and background-color comes from row:selected style. Since Materia doesn't have a style for Polari, consider adding it - something like code below (it was made for 3.30, i didn't test it after).
```
.polari-room-list row,
.polari-room-list row * {
  &:selected {
    background-color: $selected_bg_color;
    color: $selected_fg_color;

    label, label:selected { color: $selected_fg_color; }

    &:hover { background-color: darken($selected_bg_color, 5%); }

    &.has-open-popup { background-color: $selected_bg_color; }
  }
}
```

**Comment by nana-4** [comment]
Thanks. I also added a workaround for Polari as well.

**Comment by monday15** [comment]
Workaround for Builder (`dzlsuggestionpopover >  revealer row.activatable:selected`) should also have separate background-color for hover state (iirc, otherwise it will inherit it from regular row:selected:hover).

**Comment by nana-4** [comment]
The hover style is already set in other place with ` box-shadow: inset 0 0 0 9999px alpha(currentColor, 0.08)` as an overlay :)

![builder](https://user-images.githubusercontent.com/9556384/68462475-f4be3700-024f-11ea-9d35-72f8512df581.gif)

**Comment by monday15** [comment]
Ahhh, ok)
