### ISSUE TITLE
Window button glitch

### ISSUE THREAD

**Issue by nathanielevan** [nana-4/materia-theme#444]
**Reporter Info**

- Materia version: 20191017-1
- GTK3 version: 3.24.12
- Distribution (and version): Arch Linux
- Desktop environment (and version): XFCE 4.14
- Related application (and version): xfce4-panel

**Actual Issue**

1. Window button of an open application sometimes disappears randomly from the panel. (To clarify, the window button I speak of is **not** the min/max/quit buttons at the top right corner of the window, **but** the buttons on the panel corresponding to each open application)
2. When closing an open application whose window button is left of other open application(s), occasionally said other window buttons don't align to the left.
![Screenshot_2019-11-10_22-29-50](https://user-images.githubusercontent.com/9361126/68546567-3f83ae80-040a-11ea-88de-1befc79b8ed4.png)
Both visual glitches either "rectify" themselves after about 15 seconds, or are "fixed" by switching to another theme.

**Steps to Reproduce**

Happens randomly - did not manage to find a pattern to reproduce the issue

**Comment by nana-4** [comment]
Thanks for the report.

I have never experienced them before, but they sound like upstream issues rather than the theme issues.

I'll investigate them, but it would be nice if you can check whether they can be reproduced even with **Greybird**, the upstream default theme.

**Comment by nana-4** [comment]
Maybe, this?: https://bugzilla.xfce.org/show_bug.cgi?id=14394

**Comment by nana-4** [comment]
I'm closing this as I'm now pretty sure that this is the linked upstream issue.
