### ISSUE TITLE
Grey button

### ISSUE THREAD

**Issue by meetdilip** [nana-4/materia-theme#447]
**Questioner Info**

- Materia version: Installed 1 month ago. Not sure how to check the version
- GTK3 version: 3.22.30
- Distribution (and version): Ubuntu 18.04
- Desktop environment (and version):  Gnome 3.28
- Related application (and version): GIMP 2.10

**Description**

![button too grey](https://user-images.githubusercontent.com/6965443/69117943-7cf5d500-0ab7-11ea-947b-880dd237b2ce.png)

First of all, thank you for this awesome theme. 

If possible, kindly help me change the button colour. The same colour is used in highlighting buttons inside Inkscape. I would happy if it is closer to white. Thanks.

**Comment by nana-4** [comment]
Hi,

Please try the latest Materia  by [manually installing it](https://github.com/nana-4/materia-theme#manual-installation). As written in the [README](https://github.com/nana-4/materia-theme#distro-packages), Ubuntu packages are **very** outdated. In the latest Materia, the activated button has a much lighter background-color :)

![image](https://user-images.githubusercontent.com/9556384/69119863-27cbba80-0adb-11ea-8a96-a6f96d483cc9.png)

Please tell me if it's still too dark for you.

**Comment by meetdilip** [comment]
Many thanks for the response. I was customizing Materia a bit with `#03a9f4` colour. I would like to change grey to a lighter shade of `#03a9f4`.  I would be happy to know where to find it in gtk.css.

I would like to install the new Materia. Just not sure how to remove the old one. Thanks.

**Comment by nana-4** [comment]
> I would be happy to know where to find it in gtk.css.

`gtk.css` is for GTK3, and what you are showing in OP is **GTK2**. GIMP and Inkscape are using GTK2. So you need to edit the GTK2 theme.

> I would like to install the new Materia. Just not sure how to remove the old one.

Usually you don't need to remove it. You can overwrite it while installing.

---

Try this:

1. Clone the source and move to `materia-theme` dir in your terminal:

  ```
  git clone --depth 1 https://github.com/nana-4/materia-theme
  cd materia-theme
  ```

2. Open `src/gtk-2.0/assets.svg` in your text editor and edit [this line](https://github.com/nana-4/materia-theme/blob/3f45b6e6a0abe070ed25c1f3a2612609ced7fdae/src/gtk-2.0/assets.svg?short_path=45f9757#L122) to:

  ```svg
        <use xlink:href="#base-button-box" fill="#03a9f4" fill-opacity="0.2"/>
  ```

  (you may want to adjust `fill-opacity` as well.)

3. Run `./render-assets.sh gtk2` in the terminal.
4. Run `sudo ./install.sh` in the terminal.
5. Reload the theme.

**Comment by nana-4** [comment]
We don't use SVG/PNG assets for activated buttons in GTK3.

**Comment by meetdilip** [comment]
I see. I am really new to this. Thanks.

**Comment by nana-4** [comment]
It's fine :) So can we close this now?

**Comment by meetdilip** [comment]
Sure, please. :)
