### ISSUE TITLE
How to change Gnome shell font

### ISSUE THREAD

**Issue by meetdilip** [nana-4/materia-theme#448]
**Questioner Info**

- Materia version: Old
- GTK3 version: 3.22.30
- Distribution (and version): Ubuntu 18.04
- Desktop environment (and version): Gnome 3.28
- Related application (and version): Gnome Shell

**Description**

Is it possible to use `Raleway` Google Font in Gnome shell theme ? If yes, please tell me how.

**Comment by nana-4** [comment]
Yes, it's possible. After downloading the source,

1. Open `src/_sass/gnome-shell/_variables.scss` in your text editor.
2. Edit [this line](https://github.com/nana-4/materia-theme/blob/master/src/_sass/gnome-shell/_variables.scss#L5) to 

```scss
$font-family: Raleway, Sans-Serif;
```

3. Run the following in the terminal:

```
./parse-sass.sh
sudo ./install.sh
```
