### ISSUE TITLE
Button colour change

### ISSUE THREAD

**Issue by meetdilip** [nana-4/materia-theme#450]
**Questioner Info**

- Materia version: Ubuntu package
- GTK3 version: 3.22.30
- Distribution (and version): Ubuntu 18.04
- Desktop environment (and version): Gnome 3.28
- Related application (and version): Error dialogue

**Description**

Can I change the grey shade of button to blue ? I have set an opacity of 58 . Thanks.

![pop up modal button](https://user-images.githubusercontent.com/6965443/69142172-42f2f600-0aec-11ea-9a90-eedcfa92f0b6.png)
![pop up modal button colour change](https://user-images.githubusercontent.com/6965443/69142173-42f2f600-0aec-11ea-952b-60f87317e947.png)

**Comment by nana-4** [comment]
Your Materia version is too old and we no longer have such a button design in the newer version. Here is what we currently have:

![image](https://user-images.githubusercontent.com/9556384/69143473-688ff780-0b0c-11ea-88f1-2ef988253285.png)

Although you can change that focused button's background-color, I don't remember the old code, so I can't help. Sorry.

Btw, from next time I recommend you play and investigate your questions by yourself before asking me, if you are interested in tweaking the theme. I'm a human, I don't have enough resources to answer every detailed question... [HACKING.md](https://github.com/nana-4/materia-theme/blob/master/HACKING.md) would probably help you...

**Comment by meetdilip** [comment]
Sorry about that. I really like this theme. Just wanted a few tweaks.
