### ISSUE TITLE
[Feature Request] align candidate box and input area

### ISSUE THREAD

**Issue by Titubery** [nana-4/materia-theme#451]
The candidate box of Ibus is a little left to the input area. I have thought this was a bug until I noticed it's the same in Default shell theme. So this is a feature request now.
materia-dark-compact:
![materia](https://user-images.githubusercontent.com/17917040/69179292-46b36680-0b46-11ea-81fa-afc558146071.png)
gnome-shell-deault:
![default](https://user-images.githubusercontent.com/17917040/69179381-677bbc00-0b46-11ea-8b35-0f6956583ecd.png)
[matcha-dark-azul:](https://github.com/vinceliuice/matcha)
![matcha](https://user-images.githubusercontent.com/17917040/69179424-79f5f580-0b46-11ea-96dd-c0914b2c3fdf.png)
And the last one shows what I desire. Sorry for the input word 'bug' and it's just for the cute bug emoji 🐛. Could you let the two aligned and it's even better to make the candidate box more compact. It is not compact enough because of gap between pre-edit and input area especially in contrast to the below. ( in personal 
![gap](https://user-images.githubusercontent.com/17917040/69181274-c4c53c80-0b49-11ea-8438-d3cc2e65a631.png) 
 I am not a fan of the chatting bubble style in Default which maybe just fit  for popup menu. Anyway, thanks for your works!

**Comment by nana-4** [comment]
Hm, I couldn't reproduce it. In my environment, the candidate box and the input area are aligned.

Here is my environment:

- Fedora 31
- GNOME Shell 3.34.1 on Xorg
- Intelligent Pinyin 1.11.1

And the results of typing `bug`:

Materia-dark-compact:
![image](https://user-images.githubusercontent.com/9556384/69237850-ee2da900-0bd9-11ea-97e0-657baad226d2.png)

Default gnome-shell theme:
![image](https://user-images.githubusercontent.com/9556384/69237714-a27aff80-0bd9-11ea-829c-54da91020d9d.png)

Matcha-dark-azul (built from the latest master):
![image](https://user-images.githubusercontent.com/9556384/69237792-cdfdea00-0bd9-11ea-8ad0-7bbaf1cd6bd0.png)

So I need more information. Please tell me:

- Which distribution (and version) are you using?
- What version of gnome-shell are you using?
- On Xorg? Wayland?
- Which IME are you using?

**Comment by nana-4** [comment]
Or maybe this is a gnome-shell's HiDPI-related bug, I guess? In your screenshot, the default theme's pointer position is wrong.

**Comment by Titubery** [comment]
Interesting. My env is Arch/GNOME Shell 3.34.1 on Xorg/Intelligent Pinyin 1.11.1-2.  I create a fresh account to login in and the candidate box is always more left, so that's nothing with materia and config files. It might be my PC's problem. Many thanks for your patience and time.

**Comment by Titubery** [comment]
Sorry for reopenning this. I found this might be a Firefox only bug. Thanks again.

**Comment by nana-4** [comment]
Oh, you're right. I can reproduce it on Firefox. I tested it only on Chrome :sweat_smile:
