### ISSUE TITLE
change_color.sh broken with inkscape error: "Unkown option: --export-png=<IMAGE>"

### ISSUE THREAD

**Issue by wimstefan** [nana-4/materia-theme#454]
- Materia version: master (currently 8f3cbed0 but this happens since October already)
- GTK3 version: 3.24.11
- Distribution (and version): Gentoo ~amd64
- Desktop environment (and version): none - just awesomewm
- Inkscape version: 1.0beta2 (2b71d25d45, 2019-12-03)

**Actual Issue**
change_color.sh isn't exporting a theme anymore and gives the following error messages when running:
```== Light background color detected. Setting color variant to light.
== Converting theme into template...
== Filling the template with the new colorscheme...
== Generating the CSS...
== Rendering GTK 2 assets...
Rendering 'assets/entry-active.png'

(org.inkscape.Inkscape:23064): Gtk-WARNING **: 11:53:53.482: Theme parsing error: gtk.css:254:4: Expected semicolon
Unknown option --export-png=assets/entry-active.png
Rendering 'assets/entry-background.png'

(org.inkscape.Inkscape:23029): Gtk-WARNING **: 11:53:53.477: Theme parsing error: gtk.css:254:4: Expected semicolon
Unknown option --export-png=assets/entry-background.png
Rendering 'assets/entry-background-disabled.png'

(org.inkscape.Inkscape:23040): Gtk-WARNING **: 11:53:53.481: Theme parsing error: gtk.css:254:4: Expected semicolon
Unknown option --export-png=assets/entry-background-disabled.png
Rendering 'assets/flat-button.png'
```
This error message is repeated about 40 times. Please let me know if you need the whole output ...
The `Theme parsing` error is something related to Inkscape but the `Unknown option` error is the problem. As a result the theme is not created - interestingly running the script via oomox *does* export the theme despite being the same script 🤔

**Steps to Reproduce**
1. ./change_color.sh -o ta-materia-light-blue ~/.config/oomox/colors/ta-materia-light-blue
2. script finishes with the error messages shown above without creating the theme

**Comment by nana-4** [comment]
Thanks for the report.

It seems the option `--export-png=foo.png` has been replaced by `--export-file=foo.png` in Inkscape 1.0beta2. (See `inkscape --help` for details.) So we'll need to address that in the scripts...

And once we properly set the option name, that `Theme parsing error` should go away, I guess.

**Comment by wimstefan** [comment]
Thank you so much for the swift response and for looking into it!  🙏🏼

Yes `inkscape --help` doesn't give `--export-png=foo.png` as an option anymore ... but `man inkscape` does ;-)
```man
-e FILENAME, --export-png=FILENAME
   Specify the filename for PNG export.  If it already exists, the file will be overwritten without asking. Use `-' as filename to write the image data to standard output.
```
Not so sure about the `Theme parsing error` btw ... it even shows up with `inkscape --version` ... 😉

**Comment by nana-4** [comment]
> but man inkscape does ;-)

`inkscape --export-png` prints it as an unknown option in version 1.0beta2, so I guess it's a documentation bug ;-)

Btw, I tried to fix this in the above commit. Can you check if it works for you and the error goes away?

**Comment by wimstefan** [comment]
*wow* that's really fast! Thanks for that :+1: 
And after replacing `--export-png` everywhere the export is working again :-D The output is quite verbose though ... do you want to see a log of that?

Here's the patch replacing all instances of  `--export-png` in any case:
``` diff
  diff --git a/src/gtk/render-asset.sh b/src/gtk/render-asset.sh
  index a7d7e194..30290291 100755
  --- a/src/gtk/render-asset.sh
  +++ b/src/gtk/render-asset.sh
  @@ -40,7 +40,7 @@ else
     "$INKSCAPE" --export-id="$i" \
                 --export-id-only \
                 --export-dpi=192 \
  -              --export-png="$ASSETS_DIR/$i@2.png" "$SRC_FILE" >/dev/null
  +              "$EXPORT_FILE_OPTION"="$ASSETS_DIR/$i@2.png" "$SRC_FILE" >/dev/null
   fi
   if [[ -n "${OPTIPNG}" ]]; then
     "$OPTIPNG" -o7 --quiet "$ASSETS_DIR/$i@2.png"
```

Thanks again for this fabulous product & support !!! 🙏🏼

**Comment by nana-4** [comment]
Oops, I forgot to replace that. I'll add the patch, thanks for finding the mistake :wink: 

> The output is quite verbose though

Indeed. I have to admit that I didn't test it exactly because I only installed the Inkscape 1.0beta2 from flatpak :P

I'll fix that as well. Thanks for pointing it out :smiley_cat:

**Comment by nana-4** [comment]
Hmm, I couldn't find a way to turn off the verbose output. Maybe the verbose output is because the application is still in beta... If you know, please let me know how to turn off the verbose output.

Anyway, I think we can close this issue now :)
