### ISSUE TITLE
Nautilus .destructive-action red text on red background

### ISSUE THREAD

**Issue by Ghostium** [nana-4/materia-theme#456]
**Reporter Info**

- Materia version: 80ded17b03c9bac4807fc9420e4fe254e7783715
- GTK3 version: 3.24.13
- Distribution (and version): Fedora 31
- Desktop environment (and version): Gnome 3.34.2
- Related application (and version): Nautilus 3.34.2-stable

**Actual Issue**

"Delete" text is red on red background resulting in invisible text.
![Screenshot from 2019-12-31 19-26-42](https://user-images.githubusercontent.com/15706162/71630599-24f8d500-2c04-11ea-8bc5-caa1e65c285a.png)

![Screenshot from 2019-12-31 19-33-28](https://user-images.githubusercontent.com/15706162/71630689-b5371a00-2c04-11ea-9a27-3ea07916a43a.png)

**Steps to Reproduce**

1. Delete file permanently with Shift+Del
2. "Delete" text is invisible

**Additional Info**

**Comment by ddnexus** [comment]
Same here also with b1e4c563146ae34fff6a697393b6a1bc66b612f5, dark theme. It applies also for other destructive actions, like for example closing an unsaved window of gedit.

**Comment by ramottamado** [comment]
AFAIK, this bug was introduced from commit c3d3555, where all the dialog buttons was forced to be flat button style.

**Comment by ramottamado** [comment]
Here a little patch I created to fix this issue for me:
```
diff --git src/_sass/gtk/_common-3.20.scss src/_sass/gtk/_common-3.20.scss
index 71a979fd..2ddf32ab 100644
--- src/_sass/gtk/_common-3.20.scss
+++ src/_sass/gtk/_common-3.20.scss
@@ -3442,7 +3442,7 @@ messagedialog { // Message Dialog styling
   }
 
   &.destructive-action:not(:disabled) {
-    @include ink-color($error);
+    @include ink-color($error, $activated: true);
   }
 }
 
```

**Comment by ddnexus** [comment]
```

**Comment by ddnexus** [comment]
A lot better. Thank you!

**Comment by nana-4** [comment]
Fixed. 

So sorry for the late response... and thanks for the report!

**Comment by ddnexus** [comment]
@nana-4 you are working a lot on this theme, and we are all very grateful for your work! No need to be sorry! 

I just noticed the reorganization of the gnome-shell scss: that's great (and a lot of work)! Thank you!
