### ISSUE TITLE
Small input box in Switcher

### ISSUE THREAD

**Issue by tuberry** [nana-4/materia-theme#457]
**Reporter Info**

- Materia version: 
- GTK3 version: 3.24.13
- Distribution (and version): Arch
- Desktop environment (and version): GNOME Shell 3.34.2 on Xorg
- Related application (and version): [Switcher](https://github.com/daniellandau/switcher)(gnome shell extension)

**Actual Issue**

The input box of Switcher  is not equal with the entries in Materia
Adwaita:
![swadw](https://user-images.githubusercontent.com/17917040/71680289-a13a1680-2dc4-11ea-8311-b85c6b4e7232.png)
Materia-dark:
![swmat](https://user-images.githubusercontent.com/17917040/71680293-a26b4380-2dc4-11ea-9e20-2dedbcf9a925.png)

**Steps to Reproduce**

1. Install [Switcher](https://extensions.gnome.org/extension/973/switcher/) 
2. Enable it in `Gnome Tweaks`
3. Use `Super+w` to launch

**Additional Info**

**Comment by nana-4** [comment]
My apologies for the late reply, and thanks for your report. 

I've been very busy lately, so I had no time to check this issue...

I will investigate this later, so reopening this.

**Comment by tuberry** [comment]
I think the culprit is the fixed font size of `StEntry`. I commented on this line:
https://github.com/nana-4/materia-theme/blob/a0dd1edc55c75ed042ac1542a539d30b86a7a71a/src/gnome-shell/3.36/gnome-shell.css#L59
And the switcher's entry looked just like I want it to be:
![image](https://user-images.githubusercontent.com/17917040/78733950-8655e000-7979-11ea-857d-0efb5e0ff6ad.png)
It's unnecessary to limit the font of `StEntry`. On the contrary, let it go and it will inherit the font from its parent. The screenshots below were taken on the same condition above.
Entry of `Run Dialog`:
![image](https://user-images.githubusercontent.com/17917040/78734278-6ffc5400-797a-11ea-8d54-cdb803d75f6a.png)
Entry of `overview`:
![image](https://user-images.githubusercontent.com/17917040/78734320-8b675f00-797a-11ea-9bc0-e3d987593ad6.png)
Thanks for reopenning.
