### ISSUE TITLE
Firefox menus have no borders on Wayland

### ISSUE THREAD

**Issue by berenddeschouwer** [nana-4/materia-theme#462]
- Materia version: 20191017
- GTK3 version: 3.24.13
- Distribution (and version): Fedora 31 
- Desktop environment (and version): Gnome
- Related application (and version): Firefox 72

**Actual Issue**
Menus have no borders.  Menubar and context menus are affected.

**Additional Info**
On Wayland, not on X11.

Triggered by css MozillaGtk > menu { border: none; }

**Comment by j6s** [comment]
Can confirm this issue also exists on X11.

* Materia version: 20200320-0.1 (installed through apt from debian testing repository)
* GTK3 version: 3.24.20-1
* GTK2 version (not sure if this matters?): 2.24.32-4
* Distribution (and version): Debian bullseye / testing
* Desktop environment (and version): i3 4.18-1
* Related application (and version): 79.0

Here is a screenshot of me right clicking on a page with white background:
![Screenshot_2020-09-03_09-05-32](https://user-images.githubusercontent.com/3374170/92082824-5ba37280-edc5-11ea-9fd5-2869de1ddbf5.png)

**Comment by nana-4** [comment]
My apologies for the delay in replying. I temporarily added the menu border back.

That said, it seems like an upstream bug that the drop shadow of the Firefox menus is not rendered on Wayland. I'm not sure about i3 though...

Please consider reporting upstream as well that the drop shadow is not rendered in those environments.
