### ISSUE TITLE
black line below address bar in firefox 

### ISSUE THREAD

**Issue by psh-yonsei** [nana-4/materia-theme#467]
- Materia version: git commit 0dfc4986e7ecebc35e49c672e463ccf34ccc5831
- GTK3 version: 3.22.30 (CentOS 8) or 3.24.13 (Fedora 31)
- Distribution (and version): 
- Desktop environment (and version): gnome
- Related application (and version): firefox 68 esr or 73

**Reproduce**
1. open firefox
2. menu->customization
3. uncheck title bar with default theme 

![bug](https://user-images.githubusercontent.com/25217445/75650238-ad453600-5c98-11ea-95f6-bd76e43d8ea0.png)

4. Black line appear!

**Additional info.**

1. This happen only with wayland, x11 gnome is fine.
2. When I check title bar in customization, the black line disappear.

![bug2](https://user-images.githubusercontent.com/25217445/75650339-ed0c1d80-5c98-11ea-9d0b-5ecfd853b0a6.png)

3. When the window is maximized, the black line disappear.

Thank you!

**Comment by gregorydk** [comment]
It's not a black line, it's a 1px transparent gap (you can see your wallpaper through it) between viewport and chrome.

**Comment by nana-4** [comment]
I added a workaround for this.

Sorry for the late response, and thanks for the report :)

**Comment by psh-yonsei** [comment]
Thank you for your response! I've read your commit log. I can give a short report.
Sadly, the firefox problem looks still persistence after applying the latest master commit (b6ccc2) for both CentOS 8 and Fedora 31.  

+ @gregorydk  My firefox black line is just black line, not a transparent. It seems that both problems are different kinds.

**Comment by gregorydk** [comment]
@nana-4 The issue isn't solved for me, the transparent gap is still there. It does not appear with Adwaita, Plata or any other theme.

GTK 3.24.14
GNOME 3.34.4
Firefox 74

**Comment by nana-4** [comment]
@psh-yonsei @gregorydk Sorry, while I updated the source SCSS, I haven't regenerated the CSS in master for some reason. To regenerate the CSS locally, please run `./parse-sass.sh` before running `./install.sh`.
