### ISSUE TITLE
Which fonts to use with the Materia GTK theme?

### ISSUE THREAD

**Issue by vinyanalista** [nana-4/materia-theme#468]
**Questioner Info**

- Materia version: [v20191017](https://github.com/nana-4/materia-theme/releases/tag/v20191017)
- GTK3 version: 3.24.13
- Distribution (and version): openSUSE Leap 15.2 Beta
- Desktop environment (and version): GNOME 3.34
- Related application (and version): N/A

**Description**

Hi, everyone! First of all, thanks for the great theme!

Could you please suggest a font setup to use with the Materia GTK theme? For example:

![gnome-tweaks-fonts](https://user-images.githubusercontent.com/1576506/76026939-809a5400-5f0e-11ea-951f-7298187c7193.png)

- **Interface Text:** Noto Sans Regular 11
- **Document Text:** Sans Regular 11
- **Monospace Text:** Hack Regular 11
- **Legacy Window Titles:** Cantarell Bold 11

[README.md](https://github.com/nana-4/materia-theme/blob/0dfc4986e7ecebc35e49c672e463ccf34ccc5831/README.md) just says:

> ## Recommendations
> 
> ### Font
> 
> - To properly display the theme, use a font family including **Medium** weight (e.g. [Roboto](https://github.com/google/roboto) or [M+](https://mplus-fonts.osdn.jp)).
> - Set the font size to `9.75` (= 13px at 96dpi) or `10.5` (= 14px at 96dpi).

Sorry, but for me that is somehow vague... maybe a screenshot, such as the one I did, would help more.

Thanks!

**Comment by psh-yonsei** [comment]
I'm using roboto 10.5 with regular, medium,bold mixing. If you see the [gnome-shell/gnome-shell.css], you can find the default fonts for gnome-shell are [font-family: "M+ 1c", Roboto, Cantarell, Sans-Serif] with 10.5pt.  AFAIK, the font is ordered in their priority. Because I'm lazy and I don't install mplus font, I just follow the pre-defined setting.

**Comment by DarthWound** [comment]
@vinyanalista the recommended stuff in `README.md` is if you want to tweak GNOME Shell, not GTK applications _("Interface Text")_. Be aware though that Shell fonts will be useless in GNOME 3.36 as the Shell theme will follow default GTK fonts, which is a good change imho.

FYI when I use Materia I set these fonts:
**- Interface Text:** Roboto 11
**- Document Text:** Roboto Slab 11
**- Monospace Text:** Roboto Mono Medium 11 _(size 9 in terminal)_
**- Legacy Window Titles:** Roboto Bold 11

**Comment by vinyanalista** [comment]
Thanks, @DarthWound, the theme looks great with your suggestion! 

![gnome-tweaks](https://user-images.githubusercontent.com/1576506/76239661-b8581300-6210-11ea-9a9f-f790bb325547.png)

I also thank you for [Materia Kolorizer](https://github.com/DarthWound/materia-kolorizer) and [Papirus Kolorizer](https://github.com/DarthWound/papirus-kolorizer). On my screenshot you can see the Materia theme customized with [openSUSE colors](https://en.opensuse.org/Help:Colors).

For Materia, I just changed:

```sh
readonly AccentColorLight="00A489"
readonly AccentColorDark="35B9AB"
```

And for Papirus:

```sh
readonly FrontColor="00A489"
readonly BackColor="006655"
```

Keep up the good work!
