### ISSUE TITLE
Changes for GNOME 3.36

### ISSUE THREAD

**Issue by Kibouo** [nana-4/materia-theme#469]
### **Reporter Info**
- Materia version: materia-gtk-theme 20191017-1
- GTK3 version: 3.24.14
- Distribution (and version): Arch Linux x86_64; 5.5.8.arch1-1
- Desktop environment (and version): X11; GNOME 3.35.91 (3.36 release candidate)

### **Actual Issue**
The new GNOME version makes some stuff look weird.

**Main issue:**
Separators are broken.
![Screenshot from 2020-03-09 20-30-42](https://user-images.githubusercontent.com/25766329/76251222-fb34dd80-6246-11ea-902d-080c38452b5a.png)
![Screenshot from 2020-03-09 20-30-51](https://user-images.githubusercontent.com/25766329/76251225-fbcd7400-6246-11ea-896b-1e1d9f0bc4c4.png)

They do work on Adwaita tho.
![image](https://user-images.githubusercontent.com/25766329/76251782-ef95e680-6247-11ea-8d01-265aac1a7f35.png)

**Side issues:**
These things look the same as on Adwaita but don't fit with this theme/material design (this is subjective obviously).

The borders around these widgets in the notification centre.
![Screenshot from 2020-03-09 20-31-05](https://user-images.githubusercontent.com/25766329/76251865-10f6d280-6248-11ea-815a-b9248c730a59.png)

The blue bar when expanding the notification centre.
![Screenshot from 2020-03-09 20-30-a](https://user-images.githubusercontent.com/25766329/76251917-2b30b080-6248-11ea-8957-deb7f6f96938.png)

The dark background for search items.
![Screenshot from 2020-03-09 20-33-09](https://user-images.githubusercontent.com/25766329/76251946-397ecc80-6248-11ea-81c1-5b7d88533291.png)

Note: this might not be a complete list of broken/changed items. It's simply what I noticed on first sight. Feel free to add more.

**Comment by mon0theist** [comment]
+1 for the dividers being too big, looks the same on my desktop:

https://imgur.com/a/N4gLCV6

**Comment by RenanSL** [comment]
+1 gnome3.36 also on arch 5.5.8

![Screenshot from 2020-03-11 08-14-18](https://user-images.githubusercontent.com/24928343/76411417-8c53a380-6370-11ea-8b01-fa9c386a9322.png)

**Comment by nana-4** [comment]
GNOME Shell 3.36 has now been supported with #466.

I will make a new release as soon as possible, but if you want to try it quickly, don't forget to run `./parse-sass.sh` before `./install.sh` :)
