### ISSUE TITLE
GDM not work in Ubuntu 19.10

### ISSUE THREAD

**Issue by fakhamatia** [nana-4/materia-theme#471]
**Reporter Info**

- Materia version: Last version from git
- GTK3 version: 3.24.12
- Distribution (and version): Ubuntu 19.10
- Desktop environment (and version): Gnome 3.34.2

**Actual Issue**

GDM theme not work in Ubuntu 19.10 ,its default 
I use manual installation  `sudo ./install.sh -g`

**Comment by nana-4** [comment]
Sorry for the late reply.

I guess you are using "Ubuntu session" which is not supported by Materia theme. See:
https://github.com/nana-4/materia-theme#unsupported

Please install `gnome-session` and reboot. If your GDM is still Ubuntu's purple even after reboot, you probably need to run:

```
sudo update-alternatives --config gdm3.css
```

See this article for reference:
https://vitux.com/how-to-install-vanilla-gnome-desktop-on-ubuntu/

**Comment by nana-4** [comment]
By the way, as written in the README, `sudo ./install.sh -g` is **for advanced users**. Plus it's not a complete implementation...

I'd recommend the way written in [gnome-shell/README.md](https://github.com/nana-4/materia-theme/blob/master/src/gnome-shell/README.md).
