### ISSUE TITLE
Add Manjaro color palette script

### ISSUE THREAD

**Issue by SaucySauce** [nana-4/materia-theme#475]
Since there's an old Flat Plat palette scheme script it would be awesome to add a Manjaro color script and maybe even a Ubuntu one too. I'm just talking about the accent colors like the Manjaro green and Ubuntu orange.

**Comment by actionless** [comment]
you can create such palettes using [Themix/Oomox GUI](https://github.com/themix-project/oomox/) and add a PR there: https://github.com/themix-project/oomox/tree/master/colors/Modern

**Comment by SaucySauce** [comment]
Thank you. I'll do it once I figure out how to install oomox on Manjaro.

**Comment by actionless** [comment]
from AUR

**Comment by SaucySauce** [comment]
dependency issues

**Comment by actionless** [comment]
https://github.com/themix-project/oomox/#install

**Comment by SaucySauce** [comment]
I've been trying to not use pikaur but it seems like I have not choice.

**Comment by SaucySauce** [comment]
Nice, thanks. I'm installing it now.
