### ISSUE TITLE
[Question] Change font color text panel

### ISSUE THREAD

**Issue by Philippe734** [nana-4/materia-theme#477]
**Questioner Info**

- Materia version: 20190831
- GTK3 version: 3.22.30
- Distribution (and version): Ubuntu Mate 18.04
- Desktop environment (and version): Mate 1.20.1
- Theme used: Materia light compact

**Description**

I wish to modify the font color of the text of the panel bar, in order to set white. Currently, the original font text color used by materia-light-compact is grey. Please, could you tell me what file in the theme folder modify and what variables in the file to modify. I already investigated and tested some changes in gtk.css as the value of insensitive_fg_color but with no success. What file and what variable(s) to modify in order to change the color of text in panel bar ? I mean the font of text as the date and the titles windows opened in the panel bar:
![font date color](https://user-images.githubusercontent.com/24923693/77230401-34007b00-6b94-11ea-941d-08d9e29ded38.png)
) ? Thanks in advance.

**Comment by nana-4** [comment]
Hi @Philippe734, try this:

1. Clone the repository.
2. Open [`src/_sass/gtk/apps/_mate.scss`](https://github.com/nana-4/materia-theme/blob/master/src/_sass/gtk/apps/_mate.scss) with your text editor.
3. Replace _all_ `text2` string with `text`.
4. Run `./parse-sass.sh`.
5. Run `sudo ./install.sh`.
6. Reload the theme.

> what variables

We use our Sass function `on()` instead of Sass variables for the text colors in  MATE Panel :)

**Comment by Philippe734** [comment]
> Hi @Philippe734, try this:
> 
>     2. Open [`src/_sass/gtk/apps/_mate.scss`](https://github.com/nana-4/materia-theme/blob/master/src/_sass/gtk/apps/_mate.scss) with your text editor.
Thank you to taken time to reply to me. I did your suggestion. But the result is not correct. Font text color of panel is the same and many buttons are blue without shadow effect, see the date:

![before](https://user-images.githubusercontent.com/24923693/77245119-85544d00-6c1c-11ea-8e8b-c02ed84553b6.png)
![after](https://user-images.githubusercontent.com/24923693/77245121-87b6a700-6c1c-11ea-832b-f08986e36157.png)

**Comment by nana-4** [comment]
> but many buttons are blue without shadow effect

It's unrelated with my suggestion - it's just an intended change in the latest Materia :)
(But I’m planning to revert that change because I thought it was not a very good idea.)

**Comment by Philippe734** [comment]
OK ! So, you answered well to my question : solved. I will waiting for a next release with grey ripple button style
