### ISSUE TITLE
Make combobox menu vertical padding dependent on corner-radius

### ISSUE THREAD

**Issue by ettlz** [nana-4/materia-theme#478]
For those of us who like a bigger corner radius, please consider making the padding in combo-box menus equal to that radius - 2px, e.g. in _common-3.20.scss:

    combobox {
    ...
    menu {
        padding: ($corner-radius - 2px) 0;
       
        menuitem {
        ...

That way the top and bottom menu item highlight won't visibly clash with the corner round.

**Comment by nana-4** [comment]
Thanks for your suggestion.


The current 2px vertical padding of the menu is a _workaround_ for the upstream hard-coded 2px top margin of the combobox menu. Unless we hard-code the padding to 2px, the menu label will be misaligned vertically from the parent button label.

Here is the result of the current hard-coded 2px padding (with larger `$corner-radius`);
labels are perfectly aligned:

![combo-2px](https://user-images.githubusercontent.com/9556384/77270917-9a021500-6cf0-11ea-8160-c93c521ac4e8.gif)

Here is the result of your suggestion (with larger `$corner-radius`);
labels are vertically misaligned:

![combo-var](https://user-images.githubusercontent.com/9556384/77270990-ccac0d80-6cf0-11ea-8177-a265b302b94c.gif)

Which one is preferable is probably a subjective matter, but I would prefer the aligned labels. So closing, sorry.

**Comment by nana-4** [comment]
FYI, in GTK4 we won't have this problem because the GTK4 combobox has been redesigned (to be closer to the Material Design's one) and the hard-coded margin has been removed :)

**Comment by ettlz** [comment]
Thank-you for your explanation -- I see it now. I came up with something rather pleasing instead in my own private fork by adding 2px side padding, dropping the menuitem side padding to 6px, and giving the highlight a border radius.
