### ISSUE TITLE
Issue With Colour Picker

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [nana-4/materia-theme#484]
When building the theme with Oomox I get this issue with the delete button. I reported it there and was pointed here.

![77836034-7ef93000-714a-11ea-972b-35739fd07753](https://user-images.githubusercontent.com/7698035/77837867-15871a80-7166-11ea-9b21-62257bedd5da.png)

**Comment by nana-4** [comment]
Strange, this should have already been fixed in b6ccc2a.

You may be using an older version of Oomox which doesn't ship this fix.

What version of Oomox are you using?

**Comment by KUPOinyourWINDOW** [comment]
Release 1.12.6, the latest Deb over on that Github

**Comment by nana-4** [comment]
Okay. So as I expected, you're using an older version of Oomox that doesn't ship the fix. See: https://github.com/themix-project/oomox/tree/1.12.6/plugins/theme_materia

In master of Oomox, the materia submodule has been updated and fixed the problem. See: https://github.com/themix-project/oomox/tree/master/plugins/theme_materia

So, to fix the problem, please use a newer version of Oomox.

**Comment by actionless** [comment]
i see,
so @KUPOinyourWINDOW wait for 1.13.1 release of Themix or build it yourself from git following instructions from README

**Comment by actionless** [comment]
https://github.com/themix-project/oomox/releases/tag/1.13.2
