### ISSUE TITLE
Checkbox doesnt appear

### ISSUE THREAD

**Issue by enzosanchezewe** [nana-4/materia-theme#485]
I am running linux mint with gnome Shell 3.28.4
the checkbox doesnt appear, but i can click it. but i dont know when is it on or off.
![Screenshot from 2020-03-31 17-33-22](https://user-images.githubusercontent.com/62959641/78072726-f959c800-7375-11ea-947d-4ac9dc34113b.png)
HELP I LIKE THIS THEME SO MUCH I INSTALL IT ON EVERY LINUX DISTRO THAT I TOUCH ;(

**Comment by nana-4** [comment]
Hi,

How did you installed the theme? What version of Materia are you using?

FYI, I recently changed the icons directory of the GTK theme in e32fd2abae0753bedd772c3e64f249bf0b5ac41c, so that could be relevant. Reinstalling the theme may help you...

**Comment by enzosanchezewe** [comment]
Hello, sorry i didnt saw your msg. i just solve it with an app "themix", i changed some colors and it solved my checkbox issue. I can share the theme with you if you want. Also, i forgot to say that i also had a problem with the recent apps that appears when you hit start (the x button didnt appear) but it was solved with themix too. sorry for the grammar, i am learning english

**Comment by enzosanchezewe** [comment]
https://drive.google.com/drive/folders/1tDZnxQFzSeJ1aDU5Mc2eShTiqvSHyFTL?usp=sharing

**Comment by actionless** [comment]
i guess in Mint repos they have an older version of Materia than in Themix plugin
