### ISSUE TITLE
`./change-color.sh` - change compact mode

### ISSUE THREAD

**Issue by gsbhasin123** [nana-4/materia-theme#489]
Unless this is already supported, in which case please tell me how!
A great way would be to add `--compact`

**Comment by actionless** [comment]
in example from `--help` output replace `MATERIA_STYLE_COMPACT=True` to `MATERIA_STYLE_COMPACT=False` or use Themix GUI to generate the full config for change_color.sh:

https://github.com/themix-project/oomox/

**Comment by gsbhasin123** [comment]
oomox crashes for me  too much. I prefer using a custom gui script w/ zenity that i wrote.
So in the array like `<(COLOR=Val COLOR=Val)` and so on I add `MATERIA_STYLE_COMPACT`?
This is for that gui script btw

**Comment by actionless** [comment]
i've tested it only on Arch Linux, please report the issues if it's slow or freezes on Manjaro

**Comment by gsbhasin123** [comment]
It's just laggy and slow, sometimes freezes up. i installed from the aur

**Comment by actionless** [comment]
does that happens only with the themes with Terminal "Theme Options" set to "Advanced"? or any other way to reproduce that behavior?

**Comment by gsbhasin123** [comment]
turns out the issue was with gtk3-nocsd. I reverted to csd and it worked.

However I still prefer having my own script
