### ISSUE TITLE
Strange "blue corner" when using materia in the Xfce ristretto image viewer

### ISSUE THREAD

**Issue by eeickmeyer** [nana-4/materia-theme#490]
**Reporter Info**

- Materia version: 2020-03-20
- GTK3 version: 3.36
- Distribution (and version): Ubuntu (Studio) 20.04
- Desktop environment (and version): Xfce 4.14
- Related application (and version): 0.10.0

**Actual Issue**

Per bug report in [Launchpad Bug #1873244](https://launchpad.net/bugs/1873244):

"when i open a photo in ubuntu studio 20.04 (beta) the image viewer has a blue corner. it looks like a gui bug. if i open the app itself without loading any photo, it look ok. its happening on the materia theme."

![Screenshot_2020-04-16_12-35-46](https://user-images.githubusercontent.com/7434781/79467359-8c1f7700-7fb2-11ea-8559-74a07fe79542.png)

**Steps to Reproduce**

1. Open any image in the ristretto image viewer
2. "Blue Corner" appears

**Additional Info**

Bug has been confirmed by 3 people.

**Comment by eeickmeyer** [comment]
Further information: This bug doesn't happen in any other theme.

**Comment by philipzae** [comment]
Clarification: It seems to be on all themes, but most themes have this corner as a gradient, while Materia has it as a solid color.

Numix
![preview](https://imgur.com/juhhCIh.png)

Greybird-Dark
![preview](https://imgur.com/S61uOKM.png)

Adwaita
![preview](https://imgur.com/1weNSVf.png)

**Comment by eeickmeyer** [comment]
Clearly it's not a theme issue then, it's just more apparent in Materia. I'll close this.
