### ISSUE TITLE
Settings: unaligned prompt for gnome-shell when requiring authentication

### ISSUE THREAD

**Issue by maxice8** [nana-4/materia-theme#491]
**Reporter Info**

- Materia version: 20200320
- GTK3 version: 3.24.18
- Distribution (and version): Alpine Linux Edge
- Desktop environment (and version): Gnome 3.36.0
- Related application (and version): gnome-control-center (Settings) 3.36.1 and gnome-shell 3.36.1

**Actual Issue**

When the authentication prompt appears for one to input the password, the elements are slightly unaligned in the Dark compact version.

**Steps to Reproduce**

1. Open settings
2. Go to user
3. Click unlock when the user is prompted

**Additional Info**

Below are screenshots, of the version with Dark compact and then with Adwaita, don't mind the edges i took this with manual area select, couldn't do it with Select active window.

![image](https://user-images.githubusercontent.com/30738253/79812000-f1c28900-834d-11ea-9840-8e3dbffc4420.png)

![image](https://user-images.githubusercontent.com/30738253/79812019-fdae4b00-834d-11ea-902a-1499683fbbe7.png)

**Comment by maxice8** [comment]
Another thing is that the subtitle is darker than in Adwaita, i don't know if that is as intended or another issue

**Comment by maxice8** [comment]
And my username (enty) is not in the middle, below the icon as well (Just noticed that now looking at it)

**Comment by stevenjaycohen** [comment]
Confirmed in Ubuntu 20.04 using locally installed theme (~/.theme) from the head on this site.

**Comment by maxice8** [comment]
Can confirm this is fixed with the commit mentioned @tuberry

![image](https://user-images.githubusercontent.com/30738253/82743619-39b93f00-9d44-11ea-9421-e5a8e3c54044.png)
