### ISSUE TITLE
Prompts are of the wrong size

### ISSUE THREAD

**Issue by maxice8** [nana-4/materia-theme#492]
**Reporter Info**

- Materia version: 20200312
- GTK3 version: 3.28.14
- Distribution (and version): Alpine Linux Edge
- Desktop environment (and version): GNOME 3.36
- Related application (and version): gnome-shell (i guess) 3.36.1

**Actual Issue**

![image](https://user-images.githubusercontent.com/30738253/79921473-9c977d80-8408-11ea-8b1a-a6da35984d0e.png)

**Steps to Reproduce**

1. 
2. 
3. 

**Additional Info**

**Comment by zzhanabek** [comment]
Reporter Info

    Materia version: 20200320-1.fc31
    GTK3 version: 3.24.13-2
    Distribution (and version): Fedora 31
    Desktop environment (and version): GNOME 3.34.5

Actual Issue

![Screenshot from 2020-04-24 16-30-50](https://user-images.githubusercontent.com/6214884/80203606-3cdbe500-8649-11ea-8e82-4145e1c561b1.png)

**Comment by nana-4** [comment]
Sorry for the late reply.

Can you check if it's fixed with the latest master?

I added some fixes, but I'm not sure it was fixed because I can't show up the "not responding" dialog...

**Comment by zzhanabek** [comment]
Sorry for the late reply too

Issue has been resolved in next release after 20200320-1.fc31
