### ISSUE TITLE
No address in Google Chrome using materia-dark crx theme

### ISSUE THREAD

**Issue by dbasinge** [nana-4/materia-theme#498]
The address bar in the materia-dark chrome theme does not show the first part of any address.

- Materia version: Latest master
- GTK3 version: 3.24.18
- Distribution (and version): Fedora 32 
- Desktop environment (and version): GNOME 3.36.0
- Related application (and version): Google Chrome 81.0.4044.122
![Screenshot from 2020-04-27 08-53-21](https://user-images.githubusercontent.com/2634758/80387403-d7187480-8865-11ea-95bc-bf4af55e1ca8.png)

**Comment by Vap0r1ze** [comment]
I fixed this by adding the flags `--enable-features=WebUIDarkMode --force-dark-mode` to my google chrome launcher.
![image](https://user-images.githubusercontent.com/20448879/103192402-89e21c00-48a6-11eb-94d5-8fe6ac976962.png)
