### ISSUE TITLE
Howto tweak colors

### ISSUE THREAD

**Issue by dlyr** [nana-4/materia-theme#501]
**Questioner Info**

- Materia version: last git b36b379
- GTK3 version: 3.24.18
- Distribution (and version): debian bullseye

**Description**
I use to have a tweaked version of [zukitre](https://github.com/lassekongo83/zuki-themes) and, but do not get satisfaction, after few test (make a even more compact theme), I have what I want with materia-theme. But I would like to set a bit lighter dark theme.
So I try to manage color change with oomox, and I don't think I understand the process.

Is there any howto ? (i.e do I need to first install the theme, and then modify it ?)
oomox seems perfect to change the different colors, but I really don't get the main usage principles.

If you have any resources to point me to so I can manage the change of colors (I prefer to change as little as possible, and if I understand well, by last resort will be to changes the colors in scss, but it seems to be a bit tedious.

**Comment by actionless** [comment]
https://github.com/nana-4/materia-theme/blob/master/HACKING.md#how-to-tweak-the-theme

or use themix/oomox

**Comment by dlyr** [comment]
Thanks for the quick reply. 
So I rephrase the question, how to use oomox to customize materia theme ?
When I open oomox, I haven't the actual theme displayed, and I don't know which file I should import.

**Comment by actionless** [comment]
you could check some video youtube or one of those articles explaining how to use it:
https://github.com/themix-project/oomox/#review-articles-and-videos

**Comment by dlyr** [comment]
thanks, but still I may miss something. 
There is no way to modifiy the current theme ? just to save from (tweaked) presets ? 
also I have an issue with oomox export, but that maybe an oomox issue 
the rendering asset fail:
`Rendering 'assets-dark/entry-background.png'
Unknown option --export-file=assets-dark/entry-background.png`

**Comment by actionless** [comment]
weird error, like some of the dependencies have too old version or so, try flatpak release, as its dependencies are all isolated inside the package, so it should work everywhere the same

**Comment by dlyr** [comment]
I have use .deb 1.13.2 , then git master version. same behavior.
I do not see a flatpak thing available in releases.

**Comment by actionless** [comment]
https://flathub.org/apps/details/com.github.themix_project.Oomox

**Comment by dlyr** [comment]
Thanks ... after few tests with oomox (using oomox numix) it seems to be hard to tweak finely, for instance unfocused text gets not readable when I set my prefered background.
Tweaking _colors.scss and _variables.scss matches my needs.
![Screenshot from 2020-05-10 21-26-54](https://user-images.githubusercontent.com/11328509/81508566-171b3500-9305-11ea-8d03-a02ff96a5d24.png)

**Comment by actionless** [comment]
glad what at least one of two ways worked well for you at the end
