### ISSUE TITLE
Label trembling when rename file on FileZilla

### ISSUE THREAD

**Issue by athus775** [nana-4/materia-theme#503]
Hi guys,
I use Ubuntu Remix 20.04 (Cinnamon) on theme MateriaOrange_GTK variant MateriaOrange-light-compact.
When i rename file or folder on Filezilla, the label show 'trembling'.
For fix, i got on ../gtk-3.0/gtk.css under line 234 on propertie  'padding: 0 8px;' set for  'padding: 0 3px;', for me works.

Filezilla version: 3.46.3

Image with issue and fix in attached.
![issue-gtk](https://user-images.githubusercontent.com/65315261/81871321-f09c0a80-954d-11ea-805e-aeba39b2ad99.png)
![fix-gtk](https://user-images.githubusercontent.com/65315261/81871333-f72a8200-954d-11ea-95a6-874aa5c02a73.png)

Thank you guys, this theme is amazing.

**Comment by dlyr** [comment]
Confirmed for me, but I still have strange behavior (the rename entry blurs with the underground old name)
