### ISSUE TITLE
`prefers-color-scheme` for Chrome theme

### ISSUE THREAD

**Issue by AlexWayfer** [nana-4/materia-theme#520]
Hello.

I want to have correct `prefers-color-scheme` in Chromium browser (`dark` for `Materia Dark`).

But I don't know how it should be managed (set) for Chrome.

I guess, it depends on Chrome Theme. Please, correct me if I'm wrong.

**Comment by nana-4** [comment]
My apologies for the late reply.

As far as I know, "[Chrome theme](https://developer.chrome.com/extensions/themes)" does not have properties related to `prefers-color-scheme` at the moment.

But I suppose you're asking me that you want to automatically set `prefers-color-scheme` to `dark` in Chromium when you select Materia-dark GTK theme, correct? Unfortunately, I think we can't do that until GTK supports a [system-wide dark preference](https://gitlab.gnome.org/GNOME/gtk/-/issues/1919).

In any case, I think it's not something we can control with the theme, at least for now.

**Comment by AlexWayfer** [comment]
> My apologies for the late reply.
> 
> As far as I know, "[Chrome theme](https://developer.chrome.com/extensions/themes)" does not have properties related to `prefers-color-scheme` at the moment.
> 
> But I suppose you're asking me that you want to automatically set `prefers-color-scheme` to `dark` in Chromium when you select Materia-dark GTK theme, correct? Unfortunately, I think we can't do that until GTK supports a [system-wide dark preference](https://gitlab.gnome.org/GNOME/gtk/-/issues/1919).
> 
> In any case, I think it's not something we can control with the theme, at least for now.

OK, I got it, thank you.
