### ISSUE TITLE
[Gnome Shell] Spamming the syslog with `Ignoring excess values in shadow definition`

### ISSUE THREAD

**Issue by tuberry** [nana-4/materia-theme#521]
**Reporter Info**

- Materia version: pacman / 20200320-1
- GTK3 version: 3.24.22
- Distribution (and version): Arch Linux (rolling)
- Desktop environment (and version): Gnome Shell 3.36.5
- Related application (and version): Gnome Shell

**Actual Issue**

GNOME Shell apparently doesn't support more than a single shadow [definition](https://github.com/pop-os/gnome-shell-theme/commit/e65a7829f8bdaf04672c14f939cea7def619ec7f) per box-shadow. 
It's related to several `box-shadow`s in gnome-shell.css 

**Steps to Reproduce**

1. enable the theme in gnome-tweaks 
2. run `journalctl -f -o cat /usr/bin/gnome-shell` in terminal

**Additional Info**

screenshot:
![image](https://user-images.githubusercontent.com/17917040/90517696-54ab1c00-e198-11ea-8935-87beefdaac22.png)

**Comment by nana-4** [comment]
Sorry for the late response, and thanks for the report.

This should be fixed now with d0ad103b139a45ad70f8b1cd28e0dfbe2f784942. Please reopen this if you still have this problem with the latest version.
