### ISSUE TITLE
Errors: unexpected identifier and invalid string constant

### ISSUE THREAD

**Issue by ViNi-Arco** [nana-4/materia-theme#522]
**Reporter Info**

- Materia version: 20200320-1 Distributed by ArchLinux
- GTK3 version: 1:3.24.22 and GTK2 2.24.32
- Distribution (and version): Arch Linux
- Desktop environment (and version): Lxqt 15.1
- Related application (and version): Steam 1.0.0.64

**Actual Issue**

When opening Steam through the terminal he accuses:
/usr/share/themes/Materia-compact/gtk-2.0/main.rc:790: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Materia-compact/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
![relatedbug](https://user-images.githubusercontent.com/57958460/90963875-faf56b00-e491-11ea-9f33-31491b9ed1b7.png)

**Steps to Reproduce**

1. Run Steam from the terminal

**Comment by actionless** [comment]
can you reproduce it with `awf-gtk2`? (from package `awf-git`)

**Comment by ViNi-Arco** [comment]
@actionless 
> can you reproduce it with awf-gtk2? (from package awf-git)

Hi, There is still the same problem reported, thanks for trying to help

**Comment by ViNi-Arco** [comment]
> So sorry for the late reply.

Hello @nana-4  don't worry, if you were busy that's fine.

> I can't reproduce it, unfortunately. Can you reproduce it with Adwaita?

So, oddly enough, the same error occurs with Adwaita:
![adwaita-ste](https://user-images.githubusercontent.com/57958460/93491441-0f395600-f8e0-11ea-9070-835cf633bfb2.png)

Apparently Steam expects a specific String that doesn’t have themes or isn’t as he expected

**Comment by nana-4** [comment]
Thanks :)

Materia GTK2 theme is based on Adwaita GTK2 theme, so it's an expected behavior for me.

And since you reported you get the same errors with `awf-gtk2`, it should be a GTK2-related issue, not a Steam-specific issue.

However, given that no one has reported this issue to the [upstream](https://gitlab.gnome.org/GNOME/gnome-themes-extra/-/issues), I think this is likely a problem specific to your environment.

In any case, this happens in your environment even with the upstream theme, so this is not a Materia-specific issue. You can report the issue to upstream.

**Comment by nana-4** [comment]
And please, don't miss this sentence in the  [issue template](https://github.com/nana-4/materia-theme/issues/new?assignees=&labels=&template=bug_report.md&title=) from the next time when reporting a bug :)

> IMPORTANT NOTE:
> 
> Before reporting a bug, please check whether it also happens with other themes, especially Adwaita or Adwaita-dark. If it happens even with the upstream default theme, it is very likely an upstream issue.

**Comment by actionless** [comment]
i think you need to install something like `lib32-gtk2-engine-adwaita` or smth called like that

**Comment by ViNi-Arco** [comment]
It's a problem with Adwaita, I've been researching if there was anyone else with the same problems as me, and I saw that it's more common than I imagined.

as you can see in the logs these people linked has the problem similar to mine:
error: unexpected identifier `direction', expected character `}'
error: invalid string constant "normal_entry", expected valid string constant

https://forums.gentoo.org/viewtopic-t-1063880-start-0.html
https://sylpheed.sraoss.narkive.com/WTSxHQLq/sylpheed-36641-sylpheed-invalid-string-constant-errors
https://www.reddit.com/r/linux_gaming/comments/8dvvjb/steam_crashes_on_startup_in_arch/

I looked at the code more closely and found the line that Steam accuses is wrong and that's the one in `main.rc`:
![Erro Adwaita](https://user-images.githubusercontent.com/57958460/93597578-a6121b00-f991-11ea-80da-d5684037a1d8.png)

And on line 790 that Steam accuses on `main.rc`, the `direction =` is apparently missing, an example
![Erro Adwaita04](https://user-images.githubusercontent.com/57958460/93598336-ef169f00-f992-11ea-9c17-5e5f9e07a38d.png)

Inside `main.rc` you already have this warning that it's a horrible hacks, so you don't have much to do ?
![Erro Adwaita01](https://user-images.githubusercontent.com/57958460/93598620-52083600-f993-11ea-9b67-713a6d79e3b6.png)


@nana-4 I really like the work you did here, but while I have this problem I can't use it, I'm sad about it because I really liked your theme, have a nice day.

**Comment by nana-4** [comment]
@ViNi-Arco Have you tried (re)installing `lib32-gnome-themes-extra`, as @actionless suggested? It might be `gnome-themes-extra` in Arch Linux though.

Looking at your error logs, it seems the GTK2 theme engine called `adwaita` is not properly installed in your environment. Like the upstream Adwaita GTK2 theme, Materia also requests it, as written in the README: https://github.com/nana-4/materia-theme#requirements

**Comment by ViNi-Arco** [comment]
> @ViNi-Arco Have you tried (re)installing lib32-gnome-themes-extra, as @actionless suggested? It might be gnome-themes-extra in Arch Linux though.

@nana-4 Installed more did not solve.



I found the solution here: https://classicforum.manjaro.org/index.php?topic=22524.0
