### ISSUE TITLE
Focus selector Treeview

### ISSUE THREAD

**Issue by sapomuyverde** [nana-4/materia-theme#524]
Hi,
I'm trying to use this theme in an application under Windows 10/Gtk2, in the treeview selector if I go through the rows with the selection arrows the focus of the row has an appearance and if I click with the mouse the focus takes another appearance

here are the images for better reference:

using the arrows
![img1](https://user-images.githubusercontent.com/15135396/91650875-d2014700-ea4a-11ea-9edc-95c978fcfd6c.png)

using mouse click
![img2](https://user-images.githubusercontent.com/15135396/91650878-df1e3600-ea4a-11ea-9546-0579a54c09c6.png)

Is there any way to modify the theme so that the focus always remains as the first image, i.e. with the border around the selector?

I would really appreciate your help.

Regards,
Javier

**Comment by actionless** [comment]
those are two different effects, selection (light blue background) and keyboard focus (dark blue border)

when the item is both selected and focused by keyboard it have both

**Comment by sapomuyverde** [comment]
Hi,
Thanks for answering

Is there something you can help me to modify if I want the effect to always be a dark blue border, it doesn't matter if I use a keyboard or mouse.

I appreciate your help.

Regards,
Javier

**Comment by actionless** [comment]
here: https://github.com/nana-4/materia-theme/blob/master/src/gtk/sass/_common-3.20.scss#L1714

**Comment by sapomuyverde** [comment]
It's supposed that in that line I can modify the value e.g. 1..2 or 3 and it should have the dark blue border?, if so, doesn't work for me, I am using gtk2 (as required by my GUI), maybe it can be a version issue or maybe I need to modify in some other file...?.

**Comment by actionless** [comment]
right, gtk2 stuff is all here: https://github.com/nana-4/materia-theme/tree/master/src/gtk-2.0

**Comment by sapomuyverde** [comment]
I don't want to bother you much with this issue, but I can't find nothing regarding border-radius 
at c:\test_gui\themes\materia-theme\gtk-2.0

do you have any other tip?.

**Comment by nana-4** [comment]
So sorry for the late reply from me.

GTK2 is not CSS-based, so there is no border-radius property there.

GTK2 is a really old toolkit, so unlike GTK3, you can't change the appearance so freely, unfortunately. So:

> Is there any way to modify the theme so that the focus always remains as the first image, i.e. with the border around the selector?

The answer is no, as far as I know. Sorry.
