### ISSUE TITLE
A `Darkest` variant of this theme.

### ISSUE THREAD

**Issue by mansoorahmedmemon** [nana-4/materia-theme#525]
Can you please create a darkest variant of this theme like the `Flat Remix GTK Theme`.

**Comment by actionless** [comment]
also you could create it easily yourself, the instructions are here: https://github.com/nana-4/materia-theme/blob/master/HACKING.md#how-to-change-the-color-scheme

**Comment by mansoorahmedme** [comment]
I will check!

**Comment by mansoorahmedme** [comment]
Its difficult for me to do so cause I don't know scss. Can you make a variant permanently as part of this repo.

I think many people will like it.

**Comment by mansoorahmedme** [comment]
Can there be an option to select accent during install.sh runs

Like: ./install.sh teal

**Comment by actionless** [comment]
i don't see how that's related to CSS:

![2020-09-01--1598987181_1261x191_scrot](https://user-images.githubusercontent.com/1655669/91895220-2a2c8900-ec97-11ea-8238-6c6bb849c010.png)

those are just hex colors, you can get them from color picker

**Comment by mansoorahmedme** [comment]
Okay!

How to replace all the blue with teal.

**Comment by actionless** [comment]
adjust value for `SEL_BG` in the command above

**Comment by mansoorahmedme** [comment]
I got it bro thanks.

But I just want to change to SELL_BG variable and generate the theme.

**Comment by mansoorahmedme** [comment]
Can I get the default values of these variables for both light and dark variants.

**Comment by actionless** [comment]
Current (and previous) Materia color schemes are stored here: https://github.com/themix-project/oomox/tree/master/colors/Modern

**Comment by mansoorahmedme** [comment]
I tried these files but there is a difference between these and the original one. The dark variants is totally different.

I don't want to alter or modify anything but the accent of this theme both dark and light, from blue to teal.

I am requesting you to try it on your PC and tell me the exact command. I can then run it on my PC and just change the hex code of the accent.

PS. I am sorry to annoy you.
