### ISSUE TITLE
Gnome-mines have the "mine field" squares too close to each other.

### ISSUE THREAD

**Issue by pedrofleck** [nana-4/materia-theme#528]
**Reporter Info**

- Materia version: 20200320
- GTK3 version: 3.24.22
- Distribution (and version): Fedora 32
- Desktop environment (and version): Gnome 3.36
- Related application (and version): gnome-mines 3.36.1

**Actual Issue**

Materia makes Gnome-Mines hard to play because the squares are too close to each other, I tested several themes and it just happens with Materia (both compact and dark variants too).
Adwaita-dark:
![Captura de tela de 2020-09-15 02-05-40](https://user-images.githubusercontent.com/761321/93168064-67adff00-f6f8-11ea-9200-7cb4dd66431a.png)
Materia-dark:
![Captura de tela de 2020-09-15 02-05-22](https://user-images.githubusercontent.com/761321/93168087-772d4800-f6f8-11ea-8ee8-5250d5d98a2d.png)

**Comment by nana-4** [comment]
Thanks for reporting this. Fixed.
