### ISSUE TITLE
request to stick to one _colors.scss

### ISSUE THREAD

**Issue by rudrab** [nana-4/materia-theme#530]
Hi,
I generally modify `_colors.scss` for my own preference. 
But the master `_colors.scss` changes the complete format on every 1-2 gnome release.

May I request to stick to a single format or am I the only one editing the `_colors.scss` directly?

**Comment by actionless** [comment]
i guess, not sooner than that will happen in GTK/GNOME themselves :)

https://gitlab.gnome.org/GNOME/gtk/-/issues/79

**Comment by nana-4** [comment]
The fact that `_colors.scss` is frequently changed means, in other words, this theme is well-maintained and constantly improving. You could instead use a stable but less-maintained theme. Or you could stick to an old version of this theme for stability :-)

For improvement, it is inevitable that `_colors.scss` will be changed constantly. That said, I'm not going to change its format as much as 8bd7548cfe689b5db6e535ab84937b4e558e27cd & ff166632a2ba997cce56c7266c038e1abc9315e0 for the time being.

**Comment by rudrab** [comment]
Dear @nana-4 
I absolutely appreciate your time and effort that you are giving to the project and it is well maintained. I have also checked that for some cases, it might be necessary. what I am saying is, in the latest git version, it has changed from `if dark\\primary:` to `$primary-on-dark` etc. I am just requesting to keep these things more stable.

**Comment by nana-4** [comment]
I see. The reason why I changed the format is I hadn't liked `if($variant = "light", $foo, $bar)` for a while and wanted to change those to more readable, flexible, and useful. So, yes, in that sense it's stable now and I'm going to keep that format.

**Comment by rudrab** [comment]
Thanks a lot.
