### ISSUE TITLE
Show Desktop Button has white background

### ISSUE THREAD

**Issue by bjo81** [nana-4/materia-theme#533]
**Reporter Info**
- Materia version: 20200320
- GTK3 version: 3.24.23
- Distribution (and version): Arch (rolling)
- Desktop environment (and version):  MATE 1.24.1
- Related application (and version): marco

**Actual Issue**
Using the Materia Light theme, the panels are light transparent, so the dark backgrounds shines throgh. The Show Desktop Button still has a white background
![Bildschirmfoto zu 2020-09-28 20-22-18](https://user-images.githubusercontent.com/1674578/94470993-b6fc3100-01c8-11eb-8b7d-ee987c20149e.png)

**Comment by nana-4** [comment]
Thanks for reporting this.

If I remember correctly, I've already fixed it. Can you try the latest version from git and check it?

**Comment by bjo81** [comment]
You're correct, it's fixed in git.
