### ISSUE TITLE
Enormous icons in app grid on gnome 3.38.1 

### ISSUE THREAD

**Issue by mansoorahmedmemon** [nana-4/materia-theme#536]
With Materia as shell theme:

![Screenshot from 2020-10-06 14-19-52](https://user-images.githubusercontent.com/60285282/95183731-d0f8cd80-07df-11eb-87d6-a549bc0e9c1a.png)

Default shell theme:

![Screenshot from 2020-10-06 14-20-29](https://user-images.githubusercontent.com/60285282/95183818-f08ff600-07df-11eb-8d43-d3897f9c2a53.png)

**Comment by mansoorahmedmemon** [comment]
Any update?

**Comment by nana-4** [comment]
My apologies for the late response.

I tried to fix this. Please reopen this if you still have this problem with the latest git version. Thanks!
