### ISSUE TITLE
[Gnome Shell 3.38] Text of lookingGlass's actor tree inspector is indistinct with Materia or Materia-light

### ISSUE THREAD

**Issue by tuberry** [nana-4/materia-theme#541]
**Reporter Info**

- Materia version:  20200916
- GTK3 version: 3.24.23
- Distribution (and version): Arch Linux
- Desktop environment (and version): Gnome Shell 3.38
- Related application (and version): gnome-shell 

**Actual Issue**

![image](https://user-images.githubusercontent.com/17917040/97102489-ef682f80-16e0-11eb-83bd-d12ffcf69d47.png)

**Steps to Reproduce**

1. set Gnome Shell theme to `Materia` or `Materia-light` in gnome-tweaks;
2. press <kbd>Alt</kbd>+<kbd>F2</kbd> then type `lg` to open looking glass;
3. switch to `Actors` tab

**Additional Info**

**Comment by nana-4** [comment]
My apologies for the late response.

I can't reproduce this with GNOME Shell 3.38.3. Considering this together with your report  https://github.com/nana-4/materia-theme/issues/537, there are the following possibilities:

- Your Materia version isn't `20200916` in actuality.
- In your environment the result of `gnome-shell --version` is not `GNOME Shell 3.38.x` for some reason.
- You had manually specified a version below `3.38` for build option `gnome_shell_version`. (Usually you don't need to specify it manually.)

Please try reinstalling the theme with the latest version. Thanks!
