### ISSUE TITLE
Not possible to compile with `alpha`, `beta` new GNOME versions.

### ISSUE THREAD

**Issue by tim77** [nana-4/materia-theme#551]
Due to new versioning scheme in GNOME 40 not possible to compile with `alpha`, `beta` GNOME versions.

**Reporter Info**

- Materia version: v20200916
- GTK3 version: 3.24.26
- Distribution (and version): Fedora 34+
- Desktop environment (and version): GNOME 40.beta
- Related application (and version): Whole Fedora 34 branch

**Actual Issue**

```meson
src/gnome-shell/meson.build:9:45: ERROR: String 'beta' cannot be converted to int
```

**Steps to Reproduce**

Try to compile materia-theme for Fedora 34 or any other distro with alpha/beta GNOME version suffix. Probably this will affect released new GNOME version in future.

**Additional Info**
- materia-gtk-theme: FTBFS in Fedora rawhide/f34
https://bugzilla.redhat.com/show_bug.cgi?id=1923286

- [build log](https://bugzilla.redhat.com/attachment.cgi?id=1752934)

**Comment by nana-4** [comment]
Fixed. Thanks for your report.

**Comment by tim77** [comment]
Wow, that was quick. Thank you! /me going to update and fix build for f34+...
