### ISSUE TITLE
Migrate from sassc to dart-sass

### ISSUE THREAD

**Issue by nana-4** [nana-4/materia-theme#553]
As the Sass team [officially announced](https://sass-lang.com/blog/libsass-is-deprecated) in October 2020, [LibSass](https://github.com/sass/libsass) and [SassC](http://github.com/sass/sassc) have been deprecated. It's time for us to consider migrating to [Dart Sass](https://github.com/sass/dart-sass).

**Comment by nana-4** [comment]
The blocker here is that most major distros don't yet have the `dart-sass` package at the moment.

My current plan is to install [the `sass` package](https://www.npmjs.com/package/sass) using `npm` through `meson` if `sass >= 1.23.0` is not installed. This means `npm` will be an optional dependency.

**Comment by actionless** [comment]
> LibSass and Node Sass will continue to be maintained indefinitely on a best-effort basis, including fixing major bugs and security issues and maintaining compatibility with the latest Node versions.

i think such state is good enough for the time being

**Comment by nana-4** [comment]
Yeah, but the real reason why I want to switch to `dart-sass` early is that it's the only Sass implementation that supports [the new module system](https://sass-lang.com/blog/the-module-system-is-launched), which would make maintenance of our SCSS code easier.

And I think we have to migrate to it sooner or later :)

**Comment by actionless** [comment]
i see, thanks for info :)

**Comment by nana-4** [comment]
If `dart-sass >= 1.23.0` is not found, we may be able to install it locally without `npm`. E.g.:

`meson.build`:

```meson
if not sass.found() or sass_is_ruby_sass or not sass_has_module_system
  message('dart-sass >= 1.23.0 not found, installing it locally')
  sass_tar_url = 'https://github.com/sass/dart-sass/releases/download/1.32.8/dart-sass-1.32.8-linux-x64.tar.gz'
  run_command('get_sass.sh', sass_tar_url, meson.current_build_dir(), check: true)
  sass = find_program(join_paths(meson.current_build_dir(), 'dart-sass', 'sass'))
endif
```

`get_sass.sh`:

```sh
#!/bin/bash

wget -qO - "$1" | tar -xz -C "$2"
```

Pros:

- No additional dependency `npm`.
- The source dir would be a little cleaner. (No `package.json`, `package-lock.json` and `node_modules/`)
- The stand-alone executable is faster than the pure JS `npm` version. (Though it's probably a trivial matter for end users, and theme devs can install the stand-alone version themselves if needed.)

Cons:

- Probably a bit harder to maintain.
- Probably need to download the `*-linux-ia32.tar.gz` version if cpu family is ia32. How?
- Does it work on systems other than Linux?

Unless these questions are solved, I think we should go with the `npm` method as a fallback.

**Comment by actionless** [comment]
i could imagine lots of distro maintainers wouldn't like this auto-downloading behavior, i recommend making it configurable via meson options/variables (not sure how it's called there)

**Comment by nana-4** [comment]
> i could imagine some of distro maintainers might not like this auto-downloading behavior

Indeed, I had that concern too. Thanks for your advice.
