### ISSUE TITLE
address bar hides part of link using materia-dark

### ISSUE THREAD

**Issue by Vap0r1ze** [nana-4/materia-theme#555]
The address bar in the materia-dark chrome theme has a white background when not selected, which hides the first part of any address. (Same issue as #498)
- Materia version: 20200320-0ubuntu1
- GTK3 version: 3.24.20
- Distribution (and version): Ubuntu 20.04.2
- Desktop environment (and version): GNOME 3.36.8
- Related application (and version): Google Chrome 89.0.4389.90

![image](https://user-images.githubusercontent.com/20448879/111841149-df412e80-88d3-11eb-98c8-4ac35b6e6070.png)
![image](https://user-images.githubusercontent.com/20448879/111841164-e8320000-88d3-11eb-81af-a72e12b55b88.png)

**Comment by nana-4** [comment]
> Materia version: 20200320-0ubuntu1

You have a very old version of Materia, while you have the latest version of Google Chrome.

This bug is already fixed as you can see in https://github.com/nana-4/materia-theme/issues/498. To fix this in your environment, please reinstall the Chrome theme using the latest version of Materia.
