### ISSUE TITLE
Can't compile on Debian stable

### ISSUE THREAD

**Issue by fblais** [nana-4/materia-theme#562]
Hi.
Trying to compile on Debian stable and get:

francois@francois-PC:~/Téléchargements/materia-theme$ meson build
The Meson build system
Version: 0.49.2
Source dir: /home/francois/Téléchargements/materia-theme
Build dir: /home/francois/Téléchargements/materia-theme/build
Build type: native build
Project name: materia-theme
Project version: 20210322
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program sassc found: **YES** (/usr/bin/sassc)
Configuring Materia.index.theme using configuration
Configuring Materia-compact.index.theme using configuration
Configuring Materia-light.index.theme using configuration
Configuring Materia-light-compact.index.theme using configuration
Configuring Materia-dark.index.theme using configuration
Configuring Materia-dark-compact.index.theme using configuration
Configuring Materia.cinnamon.scss using configuration
Program sh found: **YES** (/usr/bin/sh)
Configuring Materia-compact.cinnamon.scss using configuration
Configuring Materia-light.cinnamon.scss using configuration
Configuring Materia-light-compact.cinnamon.scss using configuration
Configuring Materia-dark.cinnamon.scss using configuration
Configuring Materia-dark-compact.cinnamon.scss using configuration
Program gnome-shell found: **YES** (/usr/bin/gnome-shell)
Message: Set gnome-shell version to 3.30
Configuring Materia.gnome-shell.scss using configuration
Program sh found: **YES** (/usr/bin/sh)
Configuring Materia-compact.gnome-shell.scss using configuration
Configuring Materia-light.gnome-shell.scss using configuration
Configuring Materia-light-compact.gnome-shell.scss using configuration
Configuring Materia-dark.gnome-shell.scss using configuration
Configuring Materia-dark-compact.gnome-shell.scss using configuration
Configuring Materia.gtk.scss using configuration
Program sh found: **YES** (/usr/bin/sh)
Configuring Materia.gtk-dark.scss using configuration
Configuring Materia-compact.gtk.scss using configuration
Configuring Materia-compact.gtk-dark.scss using configuration
Configuring Materia-light.gtk.scss using configuration
Configuring Materia-light.gtk-dark.scss using configuration
Configuring Materia-light-compact.gtk.scss using configuration
Configuring Materia-light-compact.gtk-dark.scss using configuration
Configuring Materia-dark.gtk.scss using configuration
Configuring Materia-dark-compact.gtk.scss using configuration
Program gtk4-launch found: **NO**
Message: gtk4-launch not found, using styles for last gtk4 version availible
Message: Set gtk4 version to 4.0
Configuring Materia.gtk.scss using configuration

src/gtk-4.0/meson.build:73:4: **ERROR**:  Tried to create target "Materia.gtk.css", but a target of that name already exists.

A full log can be found at /home/francois/Téléchargements/materia-theme/build/meson-logs/meson-log.txt
[meson-log.txt](https://github.com/nana-4/materia-theme/files/6213147/meson-log.txt)

**Comment by nana-4** [comment]
Thanks for reporting this. This seems to happen only with meson < 0.50.0. I'll fix this soon.

**Comment by fblais** [comment]
Thanks for the quick reply!
