### ISSUE TITLE
/wiki/GDM-Theme should point to INSTALL_GDM_THEME.md

### ISSUE THREAD

**Issue by ObiDriftKenobi** [nana-4/materia-theme#565]
![image](https://user-images.githubusercontent.com/35656715/112723978-6fedbf00-8f11-11eb-9d9c-a17ea69972cd.png)

The wiki currently points to gnome-shell/readme.md, which, when opened, just results in a 404 page. The wiki page should redirect the reader to the INSTALL_GDM_THEME.md instead.

**Comment by nana-4** [comment]
Fixed. Thanks for pointing it out :)
