### ISSUE TITLE
GDM theme breaks Gnome 40

### ISSUE THREAD

**Issue by Errore418** [nana-4/materia-theme#572]
**Reporter Info**

- Materia version: 20210322-1
- GTK3 version: 3.24.28
- Distribution (and version): Arch linux
- Desktop environment (and version): Gnome 40.0
- Related application (and version): GDM 40.0

**Actual Issue**

Using the gdm theme completly breaks the new animations of the workspaces.
[Here](https://imgur.com/a/8FOrLYX) is a recording of the issue, i tried  the gnome recording feature but for some reason it doesn't record the actual problem. Sorry for the phone screen recording but i couldn't find a better way.

**Steps to Reproduce**

I set the gdm materia theme as described [here](https://github.com/nana-4/materia-theme/blob/master/INSTALL_GDM_THEME.md). I use materia-dark as my main them, gnome-shell included.

**Comment by nana-4** [comment]
> Materia version: 20210322-1

Hi, I think you installed Materia gnome-shell theme for 3.38 not for 40, and you have the same experience as https://github.com/nana-4/materia-theme/issues/569.

It seems the Arch package maintainer bumped the `materia-gtk-theme` version to `20210322-2`, so please try it again with the new version and see if it still happens.

**Comment by Errore418** [comment]
Yes, now it works like a charm!
Thanks a lot!
