### ISSUE TITLE
New `change_color.sh` script doesn't work well

### ISSUE THREAD

**Issue by codic12** [nana-4/materia-theme#573]
Wanted to make a Gruvbox colored Materia, so I did this:
```
bash change_color.sh -o Materia-Gruvbox <(echo -e "ROUNDNESS=5\nBG=302C2C\nFG=EBDBB4\nHDR_BG=2c2826\nHDR_FG=EBDBB4\nSEL_BG=76AD62\nMATERIA_VIEW=3C3836\nMATERIA_SURFACE=3C3836\nMATERIA_STYLE_COMPACT=True\n")
```

But at the end I get:
```
mv: cannot move '/tmp/tmp.dBFCE6lkrh/share/themes/Materia-dark-compact' to '/home/user/.themes/Materia-Gruvbox': No such file or directory
```

It also forced me to pull in the monstrosity of npm, just for one thing. Perhaps consider reverting?

**Comment by codic12** [comment]
Temporary solution, but it works. Stub out the `rm` in post_clean_up, look at the logs, copy manually.

**Comment by codic12** [comment]
Never mind, still broken.

**Comment by nana-4** [comment]
Thanks for reporting this.

> It also forced me to pull in the monstrosity of npm, just for one thing. Perhaps consider reverting?

No, I'm not planning on reverting that. But if you have the [standalone `dart-sass`](https://github.com/sass/dart-sass#standalone) installed, Materia won't require `npm`.

**Comment by codic12** [comment]
Works as expected now. Cheers

**Comment by codic12** [comment]
Never mind, sets structure up all wrong
![image](https://user-images.githubusercontent.com/48339289/116511129-d5b7c880-a87a-11eb-9ae1-a571bc6825dc.png)

**Comment by actionless** [comment]
my bad, didnt knew til now how mkdir -p handles the `..`:

```
$ mkdir -p /tmp/foo/bar/spam/../..

$ tree /tmp/foo
/tmp/foo
└── bar
    └── spam
```
