### ISSUE TITLE
Window gets misplaced when maximized

### ISSUE THREAD

**Issue by alissonlauffer** [nana-4/materia-theme#575]
**Reporter Info**

- Materia version: Latest commit from git
- GTK4 version: 4.2.0
- Distribution: Arch Linux
- Desktop environment: Cinnamon v4.8.6
- Related application: gtk4-demo v4.2.0

**Actual Issue**
After maximizing a window, it gets misplaced. The same is not reproducible with the Adwaita theme. In the demo video below I show how it looks.

https://user-images.githubusercontent.com/29029632/114772160-da8d6000-9d43-11eb-9600-9b1922b6993b.mp4

**Steps to Reproduce**

1. Open gtk4-demo.
2. Maximize the window.

**Comment by nana-4** [comment]
Thanks for reporting this.

FWIW, I cannot reproduce this on GNOME Shell 3.38.4 under X11. Maybe it only happens on Cinnamon?

**Comment by alissonlauffer** [comment]
> Maybe it only happens on Cinnamon?

I did some testing and it only happens on Cinnamon window manager (Muffin). When I replaced the window manager with mutter and openbox, the issue just "disappeared".

It's funny because the same issue is not reproducible with the Adwaita theme. Maybe I'll forward this issue to the Cinnamon team too.

**Comment by alissonlauffer** [comment]
Just did some additional tests and I could reproduce the issue with the default theme too. It is related to muffin and gtk4 window shadows. Materia theme has bigger shadows, making the issue easier to reproduce. Adwaita theme has smaller shadows.

I'll go ahead and report this to their bugtracker (If someone didn't already) and try other desktop environments for now.
