### ISSUE TITLE
Make a theme for alacritty.

### ISSUE THREAD

**Issue by AadityaThapaAce** [nana-4/materia-theme#585]
Make a yml theme for alacritty. I like the materia theme on konsole and want the same on alacritty.

**Comment by actionless** [comment]
if you're using Materia from Themix GUI, you can do it there: https://github.com/themix-project/oomox/wiki/How-to-import-and-export-Base16-themes-in-Themix-Oomox

there are some Base16 material design palettes available, however none of them are officially endorsed as part of Materia theme project
