### ISSUE TITLE
Pamac has light color in Preferences menu, and no active tab highlight

### ISSUE THREAD

**Issue by Zorrototo** [nana-4/materia-theme#586]
**Reporter Info**

- Materia version: materia-gtk-theme 20210322-2
- GTK3 version: 3.24.29
- Distribution (and version): Manjaro 21.0.4
- Desktop environment (and version): KDE Plasma 5.21.5
- Related application (and version): Pamac 10.1.2

**Actual Issue**

Some parts of the Preference menu in Pamac have very light gray color for some "sub-list". Also, the active tab is not highlighted anymore (see the Adwaita screenshot below for comparison). Here is a screenshot to visualize the issue: https://i.imgur.com/wgilcNi.png
Here is what it looks like with Adwaita: https://i.imgur.com/ZigxcSb.png

[Pamac developer says](https://gitlab.manjaro.org/applications/pamac/-/issues/1025#note_21604) it is a theme issue so here I am trying to have it fixed from the theme author now.

**Steps to Reproduce**

1. Open pamac-manager
2. Go to Preferences menu
3. Observe the very light color in menu, and the non highlighted active tab

**Comment by dotiful** [comment]
I got the same problem. Is there a quick way at least temporarily fix it?
