### ISSUE TITLE
Inkscape consuming all my resources in render-assest.sh

### ISSUE THREAD

**Issue by giuli635** [nana-4/materia-theme#589]
**Reporter Info**

- Materia version: 20210322
- GTK3 version: 3.24.29
- Distribution (and version): Arch Linux
- Desktop environment (and version): Xfce 4.16
- Related application (and version): Inkscape 1.1

**Actual Issue**

When I run change-color or render-assest, Inkscape start consuming all my resources.
![imagen](https://user-images.githubusercontent.com/75577897/120648400-f82c9b00-c451-11eb-8a38-69a429d745fd.png)

**Steps to Reproduce**

I have no idea of how to reproduce it, because days ago this didn't happen. I suppose is an update error.

**Comment by zonotope** [comment]
I'm seeing this as well. It's not only consuming all of my system cpu and ram resources, but it's also taking a really long time to finish.

I have an 8 core, 2.6 GHz cpu with 16 gigs of ram. I'm trying to modify the colors by running the bundled `change-color.sh` script (which calls `render-asset.sh`) to modify the theme. It has been running for about 7 hours at this point, and it has consistently consumed 100% of both my system's cpu capacity and ram. After 7 hours it hasn't even made it past the "rendering gtk2 assets" phase. 

There are 8 inkscape processes running (I'm assuming it's one process per core) that are each consuming >95% of a core.

**Comment by actionless** [comment]
are you able to reproduce the same if running just the command on which it hanged manually?

**Comment by actionless** [comment]
i mean smth like 
![Uploading 2021-06-03--1622735067_640x23_scrot.png…]()

**Comment by giuli635** [comment]
![imagen](https://user-images.githubusercontent.com/75577897/120683497-11deda00-c474-11eb-8163-e2b2dd34312f.png)
![imagen](https://user-images.githubusercontent.com/75577897/120683571-2de27b80-c474-11eb-93ce-c7595c7fca2f.png)

I can reproduce it manually.

**Comment by actionless** [comment]
then i guess it worth reporting it to inkscape -- even if the used SVG asset have some weird issues -- inkscape shouldnt just hang like that

**Comment by actionless** [comment]
also, since you're on arch, try to `downgrade inkscape`

**Comment by giuli635** [comment]
@AbdelrhmanNile I found a workaround, you have to edit the script that modifies the assets in the materia-theme repo and erase all gtk2 related code. You would lose gtk2 support but I did't have any issue.
