### ISSUE TITLE
Support XFWM

### ISSUE THREAD

**Issue by Baerbeisser** [nana-4/materia-theme#596]
Applying materia theme and choosing another window-theme, some tools (using CSD) display materia theme, while others (not-csd)  like viewnior, libreoffice display the window-theme.
Looks like this:
![Bildschirmfoto_2021-08-22_18-56-24](https://user-images.githubusercontent.com/22264628/130363524-6a37ae56-ac2d-4c50-becb-d4003f8535fa.png)

I noticed you have gnome, metacity and unity folders in your theme, but no xfwm4 or openbox.
Please support xfwm4 too.

**Comment by Ammako** [comment]
This is not a theme issue, but an xfce issue. CSD windows simply don't use window manager theme, so of course if you purposefully use a different base theme from your window them, it'll end up mismatched like this.

You have two (three) options: use the same base theme as your window manager theme, or use gtk3-nocsd to force window manager theming on csd windows. Or complain to xfce enough until they cave in and stop using csd (unlikely.)
