### ISSUE TITLE
 Color of progress bar with custom color

### ISSUE THREAD

**Issue by matteoalessiocarrara** [nana-4/materia-theme#61]
Some elements of the xfce panel allow to customize the color of their progress bar. However with this theme the custom color is replaced by the default color. It's not a big deal, but it would be nice if there was a generic and clean way to solve it.
![screenshot_2016-08-12_12-17-25](https://cloud.githubusercontent.com/assets/7833001/17619601/c052be32-6086-11e6-94e4-3d9fbc066a57.png)

**Comment by nana-4** [comment]
I think this is a particular issue of Xfce, so I'd like to close this as a duplicate of #60.
