### ISSUE TITLE
LXQt support

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [nana-4/materia-theme#614]
I realize that this theme doesn't support Openbox, so I installed XFWM4... this issue is regarding the Qt portion of Lubuntu not getting themed with the rest of the system. Please consider supporting Qt as well as GTK2/3.

**Comment by actionless** [comment]
since Materia-KDE is already mentioned in the README here, i think we can close this one:

https://github.com/nana-4/materia-theme#related-projects
