### ISSUE TITLE
Build succeeds but theme is solid black

### ISSUE THREAD

**Issue by ObsidianChickenz** [nana-4/materia-theme#621]
**Reporter Info**

- Materia version: Latest git commit
- GTK3 version: 3.24.34
- Distribution (and version): Arch (latest)
- Desktop environment (and version): AwesomeWM 4.3 stable
- Related application (and version): LXAppearance 0.6.3

**Actual Issue**

Whenever I build the theme from source, it is entirely pitch black except for the text.

**Steps to Reproduce**

1. Follow the instructions on INSTALL.md.
2. Attempt to select the theme in LXAppearance.

**Additional Info**

I'm running Arch as a guest on VirtualBox, the host machine is running Windows 10. I don't think this will affect anything, but it's worth mentioning IMO. I have all dependencies installed. The prebuilt version that can be installed on Arch via Pacman works fine, but I'm trying to customize the colors. I get the black theme even if I make no modifications to the theme.

**Comment by actionless** [comment]
i heard the rumors smth changed in Inkscape interface which might cause it (i myself dont use it and neither have time to check RN)

**Comment by ObsidianChickenz** [comment]
Since this repository is seemingly dead, I'm closing.
